package com.who.tlv.ServicesWebsites.server.DB;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.ElementCollection;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "computers")
public class Computers implements java.io.Serializable {
	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	private int computerId;
	//@ElementCollection(fetch=FetchType.EAGER)
	@OneToMany
	@JoinTable(name="computer_tests",joinColumns=@JoinColumn(name="computer_Id"), inverseJoinColumns=@JoinColumn(name="tests_Id"))
	@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
	private Collection<Tests> testss = new ArrayList<Tests>();
	
	private String computerIP;

	public Computers() {
	}
	
	public Computers(Collection<Tests> testss, String computerIP) {
		this.testss = testss;
		this.computerIP = computerIP;
	}

	public String getCompuerIP() {
		return computerIP;
	}

	public void setCompuerIP(String compuerIP) {
		this.computerIP = compuerIP;
	}

	public int getCompuerId() {
		return computerId;
	}

	public void setCompuerId(int compuerId) {
		this.computerId = compuerId;
	}

	public Collection<Tests> getTestss() {
		return testss;
	}

	public void setTestss(Collection<Tests> testss) {
		this.testss = testss;
	}

}
