package com.who.tlv.ServicesWebsites.server.DB;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.ElementCollection;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tasks generated by hbm2java
 */
@Entity
@Table(name = "tests")
public class Tests implements java.io.Serializable {
	
	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	private int testsId;
	private String testName;
    private String ProcessName;
    private String Params;
    private int TimeOut;
    private String cronExpress;
    private Date lastRun;
    private String ErrorDesc;
    private String Result;
    private int Retry;
    private int RetryDelay;
    private String Email;

	public Tests() {
	}

    public Tests(String testName, String ProcessName, String Params, int TimeOut,
    		String cronExpress, Date lastRun, String ErrorDesc, String Result, int Retry, int RetryDelay, String Email) {
      this.testName = testName;
      this.ProcessName = ProcessName;
      this.Params = Params;
      this.TimeOut = TimeOut;
      this.cronExpress = cronExpress;
      this.lastRun = lastRun;
      this.ErrorDesc = ErrorDesc;
      this.Result = Result;
      this.Retry = Retry;
      this.RetryDelay = RetryDelay;
      this.Email = Email;
    }
    
	public int getTestsId() {
		return testsId;
	}
	public void setTestsId(int testsId) {
		this.testsId = testsId;
	}
	public String getTestName() {
		return testName;
	}
	public void setTestName(String testName) {
		this.testName = testName;
	}
	public String getProcessName() {
		return ProcessName;
	}
	public void setProcessName(String processName) {
		ProcessName = processName;
	}
	public String getParams() {
		return Params;
	}
	public void setParams(String params) {
		Params = params;
	}
	public int getTimeOut() {
		return TimeOut;
	}
	public void setTimeOut(int timeOut) {
		TimeOut = timeOut;
	}
	public String getCronExpress() {
		return cronExpress;
	}
	public void setCronExpress(String cronExpress) {
		this.cronExpress = cronExpress;
	}
	public Date getLastRun() {
		return lastRun;
	}
	public void setLastRun(Date lastRun) {
		this.lastRun = lastRun;
	}
	public String getErrorDesc() {
		return ErrorDesc;
	}
	public void setErrorDesc(String errorDesc) {
		ErrorDesc = errorDesc;
	}
	public String getResult() {
		return Result;
	}
	public void setResult(String result) {
		Result = result;
	}
	public int getRetry() {
		return Retry;
	}
	public void setRetry(int retry) {
		Retry = retry;
	}
	public int getRetryDelay() {
		return RetryDelay;
	}
	public void setRetryDelay(int retryDelay) {
		RetryDelay = retryDelay;
	}
	
    public String getEmail() {
		return Email;
	}

	public void setEmail(String email) {
		Email = email;
	}
	
}