(function(z){
'use strict';var j$=function(a){z.L.call(this);this.w(a)},g5a=function(a,b){this.user=a;this.quotes=b},h5a=function(a,b){b=b.g();if(b===Number||b.$isProtoEnum)return a=Number(a),Number.isNaN(a)?void 0:a;if(b===Boolean)return!!a;if(b===String)return String(a)},k$=function(a){return a.tA.best||null},l$=function(a,b){b=b.filter(function(a){return"anon"!=a.lb()});b=z.hb(b,function(a){return a.lb()},a);return z.nb(b).map(function(a){return new g5a(a[0].mc(),a)},a)},i5a=function(a,b,c,d){return(0,z.sd)(a.wt[b.name]||
[],function(a){return a.Bd()==c&&a.ze()==d})},m$=function(){this.RF=1},n$=function(a){z.dk.call(this);this.w(a)},j5a=function(a,b){return z.K(a,"slots",b)},k5a=function(a,b){return z.K(a,"requestContext",b)},o$=function(a){z.L.call(this);this.w(a)},p$=function(a){return z.J(a,"inResponseToMediaResource")},q$=function(a){return z.J(a,"mediumQuote")},l5a=function(a,b){a.HO=b;return a},r$=function(a,b){return k$(a)?z.wE(k$(a)).filter(function(a){return this.x3(a)==b},a):[]},m5a=function(a,b,c){c=c.zx;
b=b.getAttribute("name").split(" ");var d=z.yb(b);a=(a.wt[c.name]||[]).filter(function(a){return d[a.Ti()]});return a.length?z.Msa(a):null},n5a=function(a,b,c,d){b=i5a(a,b,c,d);return l$(a,b)},o5a=function(a,b){var c=0;(a.wt[b]||[]).forEach(function(a){"anon"==a.lb()&&(c+=a.Re())});return c},p5a=function(a){var b=z.pP(a.Uj.Us,a.Uj.or(),a.Zl.Us,a.Zl.or()).Ga().trim();0<a.Uj.or()&&(b="…"+b);var c=z.IG(a.Cc,a.Zl.Us);a.Zl.or()<c.Ga().length&&(b+="…");return b},q5a=function(a){var b=z.uD(a.rwa),c=a.Uj.Us,
d=c?b.indexOf(c):-1,e=(c=a.Zl.Us)?b.indexOf(c):-1;if(-1==d||-1==e)return"";for(c=[];d<=e;d++)c.push(z.IG(a.Cc,b[d]));b=z.Qa(c);a=z.ex(c.indexOf(c[0]),a.Uj.or(),c.indexOf(b),a.Zl.or(),!1);return z.tia(new z.Rw(z.Tq,z.Eya),c,a,!0)},r5a=function(a,b,c){var d=a.la.ka(z.iAa,{postId:b},{filter:c});return z.uG(a,d,function(){return this.Bb.Aj(d)})},s5a=function(a,b){z.zw(a,7);var c=new z.qw("",1,a.Ga());b.forEach(function(a){z.xw(c,z.iw(a.startOffset,a.endOffset,[a.quoteId],[a.userId]))},a);b=z.gia(c);for(var d=
z.hia(c,b),e=0;e<b.length;e++){var g=d[e];if(g.length){for(var k={},l=[],p=0;p<g.length;p++){var r=g[p];k[z.J(r,"creatorIds")]=!0;l.push(r.getName())}g=b[e];p=e<b.length-1?b[e+1]:a.Ga().length;z.xw(a,z.iw(g,p,l,Object.keys(k)))}}},t5a=function(a,b,c){b="";a.lEa?a=z.n("Top highlight"):(c=""+z.A(z.uR(z.D({B4:!0,zja:!c.useragent.isMobile},a),c)),1==a.zi&&a.isActive&&(a=z.n("highlighted"),c+=" "+a),a=(0,z.y)(c));b+=a;return(0,z.y)(b)},s$=function(a,b){this.ji=a;this.fqa=b;this.Ne=(this.Hk=b=z.pD(a.node,
b))&&b.getAttribute("name");this.qO=b?z.Uz(a,b):-1},u5a=function(a,b,c){return(0,z.y)(z.TQ(z.D({user:c.currentUser,type:"quoteResponses"},a),c))},v5a=function(a,b,c){b='\x3cdiv\x3e\x3cdiv class\x3d"buttonSet u-inlineBlock"\x3e'+z.A(z.En({action:"quote",source:"quote_popover",icon:(0,z.O)(""+z.A(z.$ca())),l:(0,z.O)("button--highlightMenu u-sm-height42 u-sm-lineHeight44 u-accentColor--highlightStrong js-quoteAttributions-pileOn"),cc:!0,Ai:!0,Aea:"quote",wa:!0,isActive:a.isActive},c))+(c.supportsEdit?
z.A(z.En({action:"quote-respond",source:"quote_popover",icon:(0,z.O)(""+z.A(z.hda())),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",cc:!0,wa:!0},c)):"")+(a.rU?z.A(z.En({action:"twitter",source:"quote_popover",icon:(0,z.O)(""+z.A(z.np())),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",cc:!0,wa:!0},c)):"")+'\x3cdiv class\x3d"buttonSet-separator"\x3e\x3c/div\x3e\x3c/div\x3e';b+='\x3cdiv class\x3d"'+z.F(z.E("js-quoteAttributions-info u-inlineBlock u-verticalAlignTop u-noWrapWithEllipsis u-maxWidth414 u-paddingTop14 u-paddingRight18 u-paddingBottom0 u-paddingLeft10 u-xs-paddingTop13 u-xs-paddingLeft4 u-xs-maxWidth160"))+
'"\x3e'+t5a(a,0,c)+"\x3c/div\x3e\x3c/div\x3e";return(0,z.y)(b)},t$=function(a){z.Uq.call(this);var b=z.bs();this.Uj=b&&new s$(z.Ds(b,!0),a);this.Zl=b&&new s$(z.Ds(b,!1),a)},u$=function(a){z.L.call(this);this.w(a)},v$=function(a,b){var c=new z.Wk(z.Oq(b)),c=new z.Yd(c.ka(z.eza)),d=new z.Yd("https://www.facebook.com/v2.7/dialog/share");z.ge(d,z.Ie({app_id:b.facebook.key,href:a.toString(),display:"popup",redirect_uri:c.toString()}));return d},w5a=function(){var a=z.n("Highlights");return(0,z.y)(""+a)},
x5a=function(a,b,c){b=a.post.virtuals.responsesCreatedCount>=c.j.Q5&&(a.post.creator.userId==c.currentUser.userId||(null==a.post.homeCollection?null:null==a.post.homeCollection.virtuals?null:null==a.post.homeCollection.virtuals.permissions?null:a.post.homeCollection.virtuals.permissions.canManageAll));var d=z.D({I6:b},a),d=d||{},d=d.I6;a=""+('\x3cdiv class\x3d"container u-maxWidth740"\x3e\x3cdiv class\x3d"responsesStreamWrapper u-maxWidth640 u-hide js-responsesStreamWrapper"\x3e'+(0,z.y)('\x3cdiv class\x3d"container responsesStream-title u-paddingTop15"\x3e\x3cdiv class\x3d"row"\x3e'+
z.A(z.Mp({title:(0,z.O)(""+z.A(z.Zn())),iC:!0,Ff:(0,z.O)(""+(c.supportsEdit&&d?z.GNa(null,c):""))},c))+"\x3c/div\x3e\x3c/div\x3e")+z.ENa(z.D({Te:b},a),c)+(b?z.FNa(a,c):"")+z.DNa(c)+"\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(a)},y5a=function(a,b,c){b=z.y;var d;d=d={l:"u-flex1 u-paddingTop60"};d=d.l;var e="",g=z.n("Explore your homepage"),e=e+z.KFa({jea:(0,z.O)(""+z.A(z.Q({href:(0,z.M)(""+z.H(z.il(c))),s:(0,z.O)(""+g),ce:"homepage-link-clicked",Va:!0,isPrimary:!0,eha:!0,sc:!0,l:"u-width230 u-contentSansRegular u-fontSize14 u-borderRadius10"},
c))),l:d},c);d=(0,z.y)(e);return b('\x3cdiv class\x3d"drawer u-heightAuto u-zIndex2 js-drawer"\x3e\x3cdiv class\x3d"u-flexTop u-maxWidth1000 u-marginAuto u-paddingBottom40"\x3e'+d+'\x3cdiv class\x3d"u-flexColumnTop"\x3e\x3cdiv class\x3d"u-marginLeftAuto u-paddingTop20 u-paddingBottom10 u-paddingRight35"\x3e'+z.A(z.Bn({text:(0,z.O)("\x26times;"),action:"toggle-drawer",l:"u-fontSize32 u-lineHeight0"},0,c))+"\x3c/div\x3e"+z.JFa(a,c)+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e")},z5a=function(a,b,c){b=z.y;
var d="",e=z.n("Explore your homepage for more \x26rarr;"),g=z.n("Here are some handpicked stories for you."),k=z.n("Welcome"),l;l=l={user:c.currentUser};var p="u-size88x88 u-xs-size80x80"+(l.ZI?" "+l.ZI:""),p=z.E(p);l=""+z.up(z.D({width:88,height:88,wh:p},l),c);l=(0,z.y)(l);d+='\x3cdiv class\x3d"u-flexCenter"\x3e\x3cdiv class\x3d"u-flex0 u-paddingRight20"\x3e'+z.A(l)+'\x3c/div\x3e\x3cdiv class\x3d"u-flex1"\x3e\x3cdiv class\x3d"u-contentSansBold u-fontSize22"\x3e'+k+", "+z.A(c.currentUser.name)+'!\x3c/div\x3e\x3cdiv class\x3d"u-contentSansBold u-fontSize22"\x3e'+
g+"\x3c/div\x3e"+z.A(z.Q({href:(0,z.M)(""+z.H(z.il(c))),s:(0,z.O)(""+e),ce:"homepage-link-clicked",rb:!1,l:"u-contentSansRegular u-fontSize14 u-lineHeightLoose"},c))+'\x3c/div\x3e\x3cdiv class\x3d"u-flex0 u-alignSelfStart"\x3e'+z.A(z.Bn({text:(0,z.O)("\x26times;"),action:"toggle-drawer",l:"u-fontSize32 u-lineHeight0"},0,c))+"\x3c/div\x3e\x3c/div\x3e";e='\x3cdiv class\x3d"drawer u-heightAuto u-zIndex2 js-drawer"\x3e\x3cdiv class\x3d"u-maxWidth1000 u-marginAuto u-paddingTop40 u-paddingBottom60"\x3e'+
(0,z.y)(d);g='\x3cdiv class\x3d"u-flex u-paddingTop40"\x3e';a=a.placements;k=a.length;for(d=0;d<k;d++)g+='\x3cdiv class\x3d"u-size4of12'+(0!=d%3?" u-marginLeft10":"")+(0!=(d+1)%3?" u-marginRight10":"")+' u-xs-size12of12"\x3e'+z.A(z.YFa({placementCard:a[d],index:d,Zp:c.j.Ac.x8},c))+"\x3c/div\x3e";c=(0,z.y)(g+"\x3c/div\x3e");return b(e+c+"\x3c/div\x3e\x3c/div\x3e")},A5a=function(a){return(0,z.y)(z.A(z.Wn(String(a.content)))+" — "+z.A(z.VH(a))+" "+z.A(a.url))},B5a=function(a,b,c){return(0,z.Ck)("https://"+
z.Si(c.textshotHost)+"/image")},C5a=function(a,b,c){return(0,z.Ck)("https://twitter.com/"+z.Si(c.currentUser.twitterScreenName)+"/status/"+z.Si(a.id))},D5a=function(){var a=z.y,b;b=z.n("Failed to load image");b=(0,z.y)(""+b);return a('\x3cspan class\x3d"tweetEditor-imageStatusIcon"\x3e\x26times;\x3c/span\x3e'+z.A(b))},E5a=function(a,b,c){b=z.y;a='\x3cdiv class\x3d"tweetEditor u-sizeFullWidth"\x3e\x3cdiv class\x3d"js-tweetEditor-error tweetEditor-error u-paddingBottom10 u-textAlignCenter u-textColorRed"\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-avatar"\x3e'+
z.A(z.zp({user:a.user,Qe:!0},c))+'\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-tweetContainer"\x3e\x3cdiv class\x3d"tweetEditor-textContainer"\x3e\x3cdiv class\x3d"js-tweetEditor-text textInput textInput--chromeless u-textAlignLeft"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-textshot"\x3e\x3cdiv class\x3d"js-tweetEditor-imageStatus tweetEditor-imageStatus"\x3e';var d;d=z.n("Loading image attachment…");d=(0,z.y)(""+d);a=a+z.A(d)+"\x3c/div\x3e";d={};d=(0,z.y)(z.uo(z.D({name:"addCircled",
size:"21px",content:(0,z.O)('\x3csvg class\x3d"svgIcon-use" width\x3d"21" height\x3d"21" viewBox\x3d"0 0 21 21" \x3e\x3cpath d\x3d"M2.286 12.691a8.358 8.358 0 0 0 2.192 3.831A8.298 8.298 0 0 0 8.3 18.715c.73.19 1.462.288 2.192.29a8.363 8.363 0 0 0 2.2-.29 8.286 8.286 0 0 0 3.822-2.193 8.264 8.264 0 0 0 2.201-3.82c.19-.732.285-1.462.285-2.193a8.248 8.248 0 0 0-.285-2.2 8.265 8.265 0 0 0-2.2-3.823 8.258 8.258 0 0 0-3.822-2.2A8.66 8.66 0 0 0 10.5 2a8.188 8.188 0 0 0-2.192.286 8.33 8.33 0 0 0-3.831 2.2 8.298 8.298 0 0 0-2.193 3.822A8.66 8.66 0 0 0 2 10.5c0 .731.095 1.461.286 2.191zm1.557-.413a6.74 6.74 0 0 1-.239-1.773c0-.592.08-1.184.24-1.773a6.77 6.77 0 0 1 1.786-3.09 6.73 6.73 0 0 1 3.085-1.79c.59-.16 1.181-.24 1.777-.24.596 0 1.188.08 1.777.24a6.736 6.736 0 0 1 3.094 1.786 6.801 6.801 0 0 1 1.787 3.094c.16.59.239 1.178.239 1.768 0 .59-.08 1.182-.24 1.778a6.75 6.75 0 0 1-1.786 3.093 6.801 6.801 0 0 1-3.094 1.787 6.707 6.707 0 0 1-3.545 0A6.74 6.74 0 0 1 5.63 15.37a6.746 6.746 0 0 1-1.787-3.093zm2.937-2.055c0-.134.049-.25.148-.345a.494.494 0 0 1 .359-.143H9.23a.478.478 0 0 0 .35-.148.475.475 0 0 0 .147-.35V7.303c0-.141.048-.262.144-.363a.458.458 0 0 1 .345-.152h.562c.134 0 .25.05.35.152a.502.502 0 0 1 .147.363v1.934c0 .135.048.252.143.35a.46.46 0 0 0 .345.148h1.945c.14 0 .26.048.358.143.099.096.148.21.148.345v.562a.476.476 0 0 1-.148.35.486.486 0 0 1-.358.147h-1.945a.472.472 0 0 0-.345.143.47.47 0 0 0-.143.345v1.944c0 .14-.05.262-.148.36a.478.478 0 0 1-.35.147h-.56a.498.498 0 0 1-.489-.507V11.77a.461.461 0 0 0-.148-.345.487.487 0 0 0-.35-.143H7.287a.488.488 0 0 1-.36-.147.476.476 0 0 1-.147-.35v-.562z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
d)));d=(0,z.O)(""+z.A(d));var e;e=z.n("Include quote image");e=(0,z.y)(""+e);a=a+z.A(z.En({icon:d,isPrimary:!0,wa:!0,l:"js-tweetEditor-addTextshot u-hide",action:"add-textshot",text:(0,z.O)(""+z.A(e))},c))+'\x3cdiv class\x3d"js-tweetEditor-imageContainer tweetEditor-imageContainer"\x3e';d=(0,z.O)("\x26times;");e=z.n("Remove quote image from tweet");e=(0,z.y)(""+e);return b(a+z.A(z.An({s:d,Bc:!0,l:"js-tweetEditor-removeTextshot tweetEditor-removeTextshot",title:(0,z.O)(""+z.A(e)),action:"remove-textshot"},
c))+'\x3cimg class\x3d"js-tweetEditor-image tweetEditor-image" data-action\x3d"toggle-expand-image"\x3e\x3c/img\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'+(c.variants.textshots_userid?'\x3cdiv class\x3d"u-textColorRed"\x3eTweet to test account @fuzzyoctopusfee\x3c/div\x3e':""))},F5a=function(){var a=z.n("An error occurred, and the tweet wasn’t posted to Twitter.");return(0,z.y)(""+a)},G5a=function(a,b,c){var d="";b=z.n("Tweet posted.");a=a.lIa;var e;e=z.n("View the tweet");e=(0,z.y)(""+
e);d+=b+" "+z.A(z.Q({rb:!0,href:a,s:(0,z.O)(""+e)},c));return(0,z.y)(d)},H5a=function(){var a=z.n("Tweet must be 140 characters or less.");return(0,z.y)(""+a)},w$=function(a,b,c){z.R.call(this);this.ve=a.get("quotes-data");var d=this.ve.Vo;d.subscribe("add",this.Gca,this);d.subscribe("remove",this.Gca,this);this.cb=b;this.Qd=b.Wl;this.em=c;this.g$=[];this.Ja=a.get("app");this.Ea=a.get("popover");this.la=a.get("route-builder");this.rY=a.get("global-event-bus");this.Ewa=a.get("progressive-media-loader")},
J5a=function(a,b,c,d){var e=I5a(a,b);if(e){var g=a.cb.isPublished(),k=z.fta(a.cb);e.rU=g&&k;if(c=z.TG(z.TE(z.SE(z.UE(z.RE(z.VE(a.Ea).eb(v5a,e),z.WE),c),{DS:!0,zu:!0,Ba:!0}),"popover--quoteAttributions"),d).qa())c.jo("deactivate",function(){this.gp===b&&x$(this,null)},a),c.Mn().ia("quote",a.fra.bind(a,c)).ia("quote-respond",a.gra.bind(a,c)).ia("twitter",a.hra.bind(a))}},I5a=function(a,b){if("anon"==b.lb())return{isActive:!1,lEa:!0};var c=y$(a,b),d=b.Bd();b=b.ze();a=n5a(a.ve,c,d,b);if(!a||!a.length)return null;
a=(0,z.zb)(a,function(a){return a.user});c=(0,z.sd)(a,function(a){return a.userId!=z.lu().userId});return{isActive:(0,z.Xc)(a,function(a){return a.userId==z.lu().userId}),social:c,zi:a.length}},K5a=function(a,b){a=a.Qd.querySelectorAll('.markup--quote[name~\x3d"'+b.Ti()+'"]');return z.Za(a)},y$=function(a,b){b=b.jc()[0].name;return(b=z.Vv(a.Qd,b))?a.cb.Si(b):null},L5a=function(a,b){var c=z.cs(b);return(c=z.EH(a.em,c))?m5a(a.ve,b,c):null},x$=function(a,b){a.gp!==b&&(a.gp&&M5a(a,a.gp,!1),b&&M5a(a,b,
!0),a.gp=b)},M5a=function(a,b,c){K5a(a,b).map(function(a){z.vd(a,"is-targeted",c)})},z$=function(a,b){(b=N5a(a,b))&&z.CH(a.gk(),b)},N5a=function(a,b){var c=b.jc(),d=z.Vv(a.Qd,c[0].getName());a=z.Vv(a.Qd,z.Qa(c).getName());return z.pP(d,b.Bd(),a,b.ze())},A$=function(a,b,c,d){a={postId:a.cb.La(),quoteId:b,source:d};z.WA(c?z.Tsa:z.FBa,a)},O5a=function(a,b){z.tD(a,z.sD,z.Ob(b,z.Lb(!0)),void 0)},B$=function(a){z.dk.call(this);this.w(a)},C$=function(a){z.dk.call(this);this.w(a)},P5a=function(a,b,c){z.qa(a)||
(a=a.toString());var d=window,e={scrollbars:!0,XGa:!0,toolbar:!1,location:!0,width:670,height:690};z.wb(e,c||{});e.left||e.top||(e.width=(0,window.parseInt)(e.width,10),e.height=(0,window.parseInt)(e.height,10),e.left=Math.max(d.screenX+Math.round(d.outerWidth/2-e.width/2),0),e.top=Math.max(d.screenY+Math.round(d.outerHeight/2-e.height/2),0));var g={scrollbars:"scrollbars",XGa:"resizable",toolbar:"toolbar",location:"location",width:"width",height:"height",left:"left",top:"top"};c=z.Cga(e,function(a,
b,c){g[c]&&("boolean"==typeof b&&(b=b?"yes":"no"),a.push(g[c]+"\x3d"+b));return a},[]).join();return d.open(a,b,c)},Q5a=function(a){var b=z.mz(z.tua,{dFa:!0});b&&(b=b.split(/\s+/),b=b.filter(function(a){return!z.Ea(a)}),b.length&&z.qd(a,b))},R5a=function(a){if(!a)return"";var b=[],c=z.ub(["grafId","noteId","command","startIndex","endIndex"]),d;for(d in a)b[c[d]]=a[d];return b.join("-")},D$=function(a){z.rA.call(this);this.Cc=a.get("dom-model-converter");this.Cba={};this.uaa={};this.z_={};this.ra=
a;this.al=a.get("request");this.la=a.get("route-builder");this.ya=a.get("model-store");this.jb="";this.eca=z.Gq;this.d$=!1;this.Hh=null},E$=function(a,b){var c=a.Cba[b];c||(c=a.Cba[b]=new z.qE,a.za("new_note_list",c,a));return c},S5a=function(a,b){if(!b)return!1;var c=b.Ga();if(a.content==c.substring(a.startIndex,a.endIndex))return!0;var d=new RegExp(z.Ha(a.content),"gi"),c=(b=d.exec(c))&&d.exec(c);return b&&!c?(c=a.endIndex-a.startIndex,a.startIndex=b.index,a.endIndex=b.index+c,a.content=b[0],!0):
!1},F$=function(a,b,c){var d=b.La(),e=b.Cg(),g=E$(a,b.pe()),k=g?g.indexOf(b):-1,l=b.KB();b.bv(c);"HIDDEN"==c?a.ya.remove(b):b=z.mE(a.ya,b);var p=g?g.indexOf(b):-1;return{ql:a.al.put(a.la.ka(z.nza,{postId:d,noteId:e}),{state:c}),NJ:function(){b.bv(l);-1==p&&(-1==k?g.add(b):z.tE(g,b,k))}}},G$=function(a,b,c,d,e,g){var k=z.J(a.Bp(c,e),"replies"),l=z.Ra(k,function(a){return a.sx()==b}),p=k[l];"HIDDEN"==g&&z.Va(k,l);c=a.la.ka(z.qza,{postId:d,noteId:c,replyId:b});a=a.al.put(c,{state:g});var r=z.Ra(k,function(a){return a.sx()==
b});return{ql:a,NJ:function(){-1==r&&z.bb(k,l,0,p)}}},T5a=function(a,b,c){this.range=a;this.anchor=b;this.aB=b.getAttribute("name");this.highlight=c},H$=function(a,b,c){z.R.call(this);this.hP=b;this.owa=c;this.Na=a.get("screen");this.fb=a.get("screen-request")},U5a=function(a,b){b=b.querySelectorAll(".js-trackedPostPromotion");null!=a.hP.postPageContext&&null!=a.hP.postPageContext.postId&&z.Za(b).forEach(function(b){var d=a.hP.postPageContext.postId,e=b.getAttribute("data-post-id"),g=b.getAttribute("data-post-promotion-source");
b=b.getAttribute("data-location-id");z.WA(z.iCa,{hostPostId:d,targetPostId:e,promotionSource:g,locationId:b})})},V5a=function(){},W5a=function(a){this.pO=a},I$=function(a,b){return b?z.Vv(a.pO,b):null},X5a=function(a,b,c){O5a(a.pO,function(a){var e=a.getAttribute("name");e&&b.call(c,a,e)})},Y5a=function(a,b){return z.Jh(a.pO,b)?a.pO:null},J$=function(a,b,c,d,e){z.XX.call(this,a,b);this.bb(new z.oX(c));this.bb(new z.FY(!1));this.bb(new z.HY(a));this.bb(new z.YX);this.bb(new z.pZ(a,!1,!1));this.bb(new z.JZ(d,
!0));this.Yk=!0;this.dm=d;this.al=a.get("request");this.Fa=a.get("dialog");this.f_=e;this.qa()},Z5a=function(){var a=z.n("Saving failed. You may be having connectivity issues or notes might be disabled on this post. Please try again.");return(0,z.y)(""+a)},$5a=function(){var a=z.n("Yikes! Something happened and we couldn’t dismiss this note.");return(0,z.y)(""+a)},a6a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this note.");return(0,z.y)(""+a)},b6a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this reply.");
return(0,z.y)(""+a)},c6a=function(){var a=z.n("The note has been dismissed.");return(0,z.y)(""+a)},d6a=function(){var a=z.n("The note has been deleted.");return(0,z.y)(""+a)},e6a=function(){var a=z.n("The reply has been deleted.");return(0,z.y)(""+a)},f6a=function(){var a=z.n("Write a note…");return(0,z.y)(""+a)},g6a=function(){var a=z.n("Cancel");return(0,z.y)(""+a)},K$=function(a,b,c,d,e){J$.call(this,a,b,e||"Leave a note",400,d||null);this.jb=c;this.la=a.get("route-builder");this.vf=a.get("notes-data")},
L$=function(a,b,c,d,e,g){J$.call(this,a,b,"Leave a reply…",200,d);this.la=a.get("route-builder");this.vf=a.get("notes-data");this.jb=c;this.Cca=g||null;this.Ne=e},i6a=function(a,b,c){var d='\x3cdiv class\x3d"quoteResponses js-quoteResponses"\x3e',e=a.quotes.length,g=a.responses.length||a.k7;b=a.notes.length||a.oU;if(e||g||b){if(e){var e='\x3cdiv class\x3d"quoteResponses-section"\x3e'+z.A(z.Np({title:(0,z.O)(z.A(w5a())+" ("+z.A(a.quotes.length)+")"),yf:!0},c)),k;k={Iia:a.quotes,JIa:!0};var l='\x3cdiv class\x3d"js-quotesList"\x3e';
if(!k.JIa)var p=z.n("Learn more"),l=l+z.A(z.Np({title:(0,z.O)(""+z.A(w5a())),yf:!0,Ff:(0,z.O)(""+z.A(z.Lp({href:(0,z.M)(""+z.H((0,z.Ck)("https://medium.com/the-story/introducing-highlights-a4df69e8ed43"))),moreText:(0,z.O)(""+p),tb:!0},c)))},c));for(var p="list u-marginTop5 u-marginBottom15"+(k.Iia.length?"":" u-hide"),p=(0,z.O)(p),l=l+('\x3cul class\x3d"'+z.F(p)+'"\x3e'),p=k.Iia,r=p.length,t=0;t<r;t++){for(var v=p[t],C="",G=v.quotes,N=G.length,P=0;P<N;P++)C+=""+G[P].quoteId+(P!=N-1?",":"");C=z.E(C);
l+='\x3cli class\x3d"list-item list-item--inline u-border0" data-quote-ids\x3d"'+z.F(C)+'" data-quote-creator-id\x3d"'+z.F(v.user.userId)+'" data-action\x3d"highlight-quote" data-action-type\x3d"hover"\x3e'+z.A(z.xp(z.D({user:v.user,Ee:!0},k),c))+"\x3c/li\x3e"}k=(0,z.y)(l+"\x3c/ul\x3e\x3c/div\x3e");e=e+z.A(k)+"\x3c/div\x3e"}else e="";g?(g='\x3cdiv class\x3d"quoteResponses-section'+(a.k7?" is-withEditor":"")+'"\x3e'+z.A(z.Np({title:(0,z.O)(""+z.A(z.Zn())),yf:!0},c)),a.k7&&c.supportsEdit&&c.isAuthenticated?
(k={},k=(0,z.y)('\x3cdiv class\x3d"js-inlineNewPostControl inlineNewPostControl inlineNewPostControl--quoteResponses"\x3e'+z.TQ(z.D({user:c.currentUser,isCollapsed:!0,fC:!0,type:"quoteResponses",Ou:(0,z.O)(""+z.A(z.ho()))},k),c)+"\x3c/div\x3e"),k=z.A(k)):k="",g=g+k+h6a(a,0,c)+"\x3c/div\x3e"):g="";d+=e+g;if(a.kGa&&b){g=z.n("Who can see this?");d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed u-paddingLeft0 u-paddingRight0"\x3e';e=b="";k=a.post.homeCollection;k=a.post.creator.userId!=
c.currentUser.userId?k?z.n("Private notes are visible to you, the author, and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you, the author, and the editors of any publication this story is added to."):k?z.n("Private notes are visible to you and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you and the editors of any publication this story is added to.");e+=k;e=(0,z.y)(e);e=""+z.A(e);e=(0,z.O)(e);b+='\x3cspan data-tooltip\x3d"'+z.F(e)+
'"\x3e'+g+"\x3c/span\x3e";g={};g=(0,z.y)(z.uo(z.D({name:"lock",size:"19px",content:(0,z.O)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14 14.052a1 1 0 0 1-.992.998H5.992A.99.99 0 0 1 5 14.052v-4.004a1 1 0 0 1 .992-.998h7.016a.99.99 0 0 1 .992.998v4.004zM7 5.445C7 4.187 8.114 3.15 9.5 3.15c1.385 0 2.5 1.04 2.5 2.295V8.05H7V5.445zm6.008 2.605H13V5.445c0-1.822-1.578-3.295-3.5-3.295C7.577 2.15 6 3.618 6 5.445V8.05h-.008A2 2 0 0 0 4 10.048v4.004a1.99 1.99 0 0 0 1.992 1.998h7.016A2 2 0 0 0 15 14.052v-4.004a1.99 1.99 0 0 0-1.992-1.998z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
g)));g=(0,z.O)(""+z.A(g));e=z.n("Private notes");e=(0,z.y)(""+e);b={dIa:g,title:(0,z.O)(""+z.A(e)),yf:!0,Ff:(0,z.O)(b),l:"heading--privateNotes"};b=(0,z.y)(z.Jp(z.D({vj:(0,z.O)(""+z.Kp(b,c)),YEa:!0},b)));b=d+=z.A(b);d=""+('\x3cdiv class\x3d"privateNotes-list js-notesList'+(a.oU?" is-showingNoteEditor":"")+(0==a.notes.length?" is-empty":"")+'"\x3e');g=a.notes;e=g.length;for(k=0;k<e;k++)d+=M$({note:g[k],post:a.post,iK:a.iK},0,c);a.oU?(g=a.post.creator,a="",g=c.currentUser.userId==g.userId?z.n("Leave yourself a note"):
z.n("Send {$name} a private note…",{name:z.A(g.name)}),a+=g,a=(0,z.y)(a),a='\x3cdiv class\x3d"privateNotes-actions js-noteActions"\x3e'+z.A(z.Bn({action:"show-note-editor",text:(0,z.O)(""+z.A(a)),l:"privateNotes-prompt"},0,c)),g=z.y,e='\x3cdiv class\x3d"privateNotes-editor"\x3e'+z.A(z.yp({user:c.currentUser,Qe:!0},c))+'\x3cdiv class\x3d"js-noteEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',k=z.n("Send"),k=(0,z.y)(""+k),c=g(e+z.A(z.Bn({action:"save-note",isPrimary:!0,l:"js-saveNoteButton",
text:(0,z.O)(""+z.A(k))},0,c))+z.A(z.Bn({action:"hide-note-editor",text:(0,z.O)(""+z.A(g6a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e"),c=a+c+"\x3c/div\x3e"):c="";c=(0,z.y)(d+("\x3c/div\x3e"+c));d=b+('\x3cdiv class\x3d"quoteResponses-inner privateNotes"\x3e'+c+"\x3c/div\x3e\x3c/div\x3e")}}else 0<a.bD&&(a=z.n("Show next tip"),b=z.n("Show previous tip"),d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed quoteResponses-section--tips u-textAlignCenter u-paddingLeft0 u-paddingRight0"\x3e\x3cdiv class\x3d"quoteResponses-section--tipsInner u-alignMiddle"\x3e'+
z.A(z.En({yb:!0,Bc:!0,wa:!0,action:"previous-highlight-tip",icon:(0,z.O)(""+z.A(z.Ao())),title:(0,z.O)(""+b)},c))+"\x3cdiv class\x3d'u-alignBlock quoteResponses-section--tipsContent u-paddingLeft20 u-paddingRight20 js-highlightTip'\x3e\x3c/div\x3e"+z.A(z.En({yb:!0,Bc:!0,wa:!0,action:"next-highlight-tip",icon:(0,z.O)(""+z.A(z.Do())),title:(0,z.O)(""+a)},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(d+"\x3c/div\x3e")},h6a=function(a,b,c){return(0,z.y)(z.A(z.FR({posts:a.responses,source:"quoteResponses",
gS:!0},0,c)))},M$=function(a,b,c){var d,e=null==a.note.replies?null:a.note.replies.length,g=null==a.note.replyId,k=a.post.creator.userId==c.currentUser.userId,l=a.post.creator.userId==a.note.author.userId;d=a.note.author.userId==c.currentUser.userId;b=k||(null==a.post.homeCollection?null:a.post.homeCollection.virtuals.permissions.canEditPosts);var p=""+(g?"js-note-item"+(a.note.noteId?" js-note-"+a.note.noteId:""):"js-reply-item"+(a.note.replyId?" js-reply-"+a.note.replyId:"")),p=z.E(p),p='\x3cdiv class\x3d"privateNotes-item '+
z.F(p)+' js-note" data-note-id\x3d"'+z.F(a.note.noteId)+'"\x3e'+(g?z.A(z.xp({user:a.note.author},c)):z.A(z.vp({user:a.note.author},c)))+'\x3cdiv class\x3d"privateNotes-authorLockup"\x3e\x3cdiv class\x3d"privateNotes-author"\x3e'+z.A(z.Pn({user:a.note.author},c));g||!(k||d||(null==a.post.homeCollection?0:a.post.homeCollection.virtuals.permissions.canEditPosts))||l||a.gha?k="":(k=z.n("(Editor)"),k=(0,z.y)(""+k),k='\x3cspan class\x3d"privateNotes-author--supplemental"\x3e '+z.A(k)+"\x3c/span\x3e");p=
p+k+'\x3c/div\x3e\x3cdiv class\x3d"privateNotes-supplemental"\x3e'+z.A(z.jj(Number(a.note.createdAt),c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"privateNotes-content js-privateNotesContent"\x3e';k=z.A(z.Ix(String(a.note.content),c));l=String(k).replace(/(\r\n|\r|\n)/g,"\x3cbr\x3e");k=z.di(k,z.gi)?(0,z.y)(l,z.ei(k)):l;d=""+(p+k+"\x3c/div\x3e"+(d?j6a({note:a.note,isPrimary:g},c):""));if(g){d+='\x3cdiv class\x3d"privateNotes-replies'+(e?"":" is-empty")+' js-repliesList"\x3e';if(e)for(e=a.note.replies,
g=e.length,p=0;p<g;p++)k=e[p],d+=M$({note:k,post:a.post,gha:a.note.author.userId==k.author.userId},0,c);e=d;a.iK?(g=z.y,d='\x3cdiv class\x3d"privateNotes-editor privateNotes-editor--reply"\x3e'+z.A(z.wp({user:c.currentUser,Qe:!0},c))+'\x3cdiv class\x3d"js-replyEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',p=z.n("Send"),p=(0,z.y)(""+p),g=g(d+z.A(z.Bn({action:"save-reply",isPrimary:!0,text:(0,z.O)(""+z.A(p))},0,c))+z.A(z.Bn({action:"hide-reply-editor",text:(0,z.O)(""+z.A(g6a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e")):
g="";g="\x3c/div\x3e"+g+'\x3cdiv class\x3d"privateNotes-actions'+(b?" privateNotes-actions--withDismiss":"")+' u-clearfix"\x3e';a.iK?(d=z.y,p=z.n("Reply"),p=(0,z.y)(""+p),d='\x3cdiv class\x3d"u-floatLeft"\x3e'+d(z.A(z.Bn({isPrimary:!0,action:"show-reply-editor",l:"privateNotes-prompt",text:(0,z.O)(""+z.A(p))},0,c)))+"\x3c/div\x3e"):d="";d=e+(g+d+(b?'\x3cdiv class\x3d"u-floatRight"\x3e'+j6a({note:a.note,isPrimary:!0,Oga:!0},c)+"\x3c/div\x3e":"")+"\x3c/div\x3e")}return(0,z.y)(d+"\x3c/div\x3e")},j6a=
function(a,b){var c=z.y,d=a.isPrimary?a.note.noteId:a.note.replyId,e=a.Oga?"dismiss-note":a.isPrimary?"delete-note":"delete-reply";a=a.Oga?z.n("Dismiss note"):z.n("Delete");a=(0,z.y)(""+a);a=z.A(a);return c(z.A(z.Bn({actionValue:d,action:e,l:"privateNotes-delete js-deleteNote",text:(0,z.O)(""+a)},0,b)))},k6a=function(a,b,c){b="";if(0==a.W6)a=1==a.bD?z.n("People highlighted this passage. You can click on an existing highlight to add to it, like below:"):z.n("{$topQuoteCount} people highlighted this passage. You can click on an existing highlight to add to it, like below:",
{topQuoteCount:z.A(a.bD)}),b+=a,b+='\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Wi(z.hm({imageId:"1*SyXCciYXeNpx4-GUAuh0XQ.gif"},0,c)))+'"\x3e';else if(1==a.W6)a=z.n("Or, select any passage to create your own highlight and tell the author and others what resonated with you:"),b+=a+'\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Wi(z.hm({imageId:"1*dEp02HXMKtAeKxsV5MWqGg.gif"},0,c)))+'"\x3e';else if(2==a.W6){a=z.n("so that you can save your highlights and share them with others.");
var d=z.n("Sign in to create a profile");b+=z.A(z.Q({rb:!0,cc:!0,source:"highlight_tip",s:(0,z.O)(""+d),href:(0,z.M)(""+z.H(z.fl(c)))},c))+" "+a}return(0,z.y)(b)},N$=function(a,b,c,d,e,g,k,l){z.R.call(this);this.ra=a;this.xa=a.get("butter-bar");this.cb=b;this.Ne=c;this.Oj=e;this.ve=a.get("quotes-data");this.vf=a.get("notes-data");this.oj=a.get("responses-data");this.mf=g;this.f_=d;this.$_=(this.FG=k)?k.Ti():null;this.Pf=this.Lc=null;this.Rj={};this.Gaa=!!z.mu();this.Iaa=!!z.ou();this.Tz=this.Gaa&&
this.Iaa&&z.SH(b);this.Dq=null;this.qN=0;this.Jda=o5a(this.ve,this.Ne);this.Xv=l;this.Ua(this.Dv());this.Gba=z.mu()?2:3},l6a=function(a){a.pb(".js-block").forEach(function(a){this.Pa(a,"mouseenter",this.Gra,this);this.Pa(a,"mouseleave",this.r1,this)},a)},m6a=function(a){a.pb(".js-note").forEach(function(a){this.Pa(a,"mouseenter",this.Era,this);this.Pa(a,"mouseleave",this.r1,this)},a)},n6a=function(a,b){var c=a.query(".js-note-"+b);a.Rj[b]||(a.Rj[b]=new L$(a.ra,c.querySelector(".js-replyEditor"),a.cb.La(),
b,a.Ne),z.tA(a,a.Rj[b],"saving",a.Zua,a),z.tA(a,a.Rj[b],"save",a.Tua,a),z.tA(a,a.Rj[b],"fail",a.Uta,a));z.kd(c,"is-noteEditorVisible");a.Rj[b].focus()},o6a=function(a,b){var c=a.Rj[b];c&&(c.kb()&&c.qd(""),a=a.query(".js-note-"+b),z.td(a,"is-noteEditorVisible"))},p6a=function(a,b,c){var d=I$(a.mf,a.Ne);if(d){var e=[];a.Xv&&(e=a.Xv.quotes.map(function(a){return a.Ti()}));(0,z.zb)(d.querySelectorAll(".markup--quote"),function(a){var d=a.getAttribute("data-creator-ids").split(" "),d=z.Ua(d,b);if(this.Xv)var l=
a.getAttribute("name").split(" "),d=d&&(0,z.Xc)(l,z.Ua.bind(null,e));z.vd(a,"is-selected",c&&d)},a)}},O$=function(a){return(a=z.Sv(a,function(a){return z.jd(a,"js-note-item")}))&&a.getAttribute("data-note-id")},q6a=function(a,b,c,d){b=new z.NG(b,300);b.Ua(c);b.subscribe("dismiss",d,a);b.qa();return b},P$=function(a){var b=a.jc(),c=a.Bd();a=a.ze();1<b.length&&(a=b[0].Ga().length);var d=new z.wx;d.Vp(b[0].getName());d.Ig(c);z.K(d,"endIndex",a);d.qd(b[0].Ga().substring(c,a));return d},Q$=function(a,
b){b%=a.Gba;0>b&&(b=a.Gba-1);a.qN=b;(b=a.query(".js-highlightTip"))&&z.lz(b,k6a,{W6:a.qN,bD:a.Jda})},R$=function(a,b,c,d){z.R.call(this);this.Ua(this.Dv(d));this.Db=a.get("dom-monitor");this.cb=b;this.Naa=!b.Ya().nr()||b.Lb();this.jb=b.La();this.mf=c;this.ve=a.get("quotes-data");this.oj=a.get("responses-data");this.vf=a.get("notes-data");this.Gv=null;this.Kh={}},r6a=function(a,b){b.forEach(function(a){a&&S$(this,a)},a)},S$=function(a,b){if(!a.Gv)if(I$(a.mf,b)){var c=s6a(a,b),c=t6a(a,c),c=u6a(a,c),
c=v6a(a,c);a.Kh[b]=c;w6a(a,b)}else delete a.Kh[b]},x6a=function(a,b){if(!a.Gv){var c=a.Kh[b];if(c){var d=c.length,c=u6a(a,c),c=v6a(a,c);a.Kh[b]=c;d!=c.length?w6a(a,b):c.forEach(function(a){a.Xa&&a.offsetTop&&(a.Xa.style.top=a.offsetTop+"px")})}}},y6a=function(a,b,c){return z.Sa(a.Kh[b]||[],function(a){return a.Xa==c})},s6a=function(a,b){var c=[];E$(a.vf,b).Ug(function(a){var e=a.CB(),g;e?(g=this.vf.rR(e),e=g.hb(),g=z.J(g,"endIndex")):(e=0,g=a.kb().length);c.push({anchor:b,startIndex:e,endIndex:g,
notes:[a],quotes:[],responses:[]})},a);if(a.Naa)return c;(a.ve.wt[b]||[]).forEach(function(a){var e=z6a(a);c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[a],responses:[]})},a);r$(a.oj,b).forEach(function(a){var e=p$(a);e&&(e=q$(e)&&q$(e).Ln())&&(e=z6a(e),c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[],responses:[a]}))},a);return c},t6a=function(a,b){var c=[];b.sort(function(a,b){return a.startIndex-b.startIndex});b.forEach(function(a){var b=
z.Ra(c,function(b){return b.endIndex>=a.startIndex-1&&b.startIndex<=a.endIndex+1});0<=b?this.bG(c[b],a):c.push(a)},a);return c},v6a=function(a,b){var c=[];b.forEach(function(a){if(a.offsetTop){var b=z.Ra(c,function(b){return 30>=Math.abs(b.offsetTop-a.offsetTop)});0<=b?this.bG(c[b],a):c.push(a)}},a);return c},w6a=function(a,b){a.pb(".js-paragraphControl-"+b).forEach(z.Ch);a.Kh[b]=a.Kh[b].map(function(a){var b=A6a(this,a),b=z.nz(B6a,b);b.style.top=a.offsetTop+"px";a.Xa=b;this.na().appendChild(a.Xa);
z.kd(b,"is-visible");return a},a)},A6a=function(a,b){var c=b.notes,d=b.responses,e=l$(a.ve,b.quotes),g=d?d.length:0,k=c?c.length:0,l=0,p=0,r=0,t=!1,v=!1,C={},G={},N=z.lu().userId,P=a.cb.Ya().Hf().lb();c.forEach(function(a){var b=a.kI();b&&((a=z.J(a,"replies"))&&a.forEach(function(a){k++;a.author&&(a.author.userId==N&&l++,a.author.social&&a.author.social.isFollowing&&(C[a.author.userId]=a.author),G[a.author.userId]=!0)}),G[b.userId]=!0,b.userId==N&&l++,b.userId==P?p++:r++,b.social&&b.social.isFollowing&&
(C[b.userId]=b))});e.forEach(function(a){a=a.user;G[a.userId]=!0;a.userId==N&&(t=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});d.forEach(function(a){a=a.Hf();G[a.userId]=!0;a.userId==N&&(v=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});c=b.quotes.filter(function(a){return"anon"==a.lb()});return{postId:a.jb,aB:b.anchor,iGa:k,YGa:g,ey:v,Wx:l,$ha:p,jGa:r,QYa:e.length,cy:t,Hga:Object.keys(G).length,bEa:z.nb(C),bD:c.length}},z6a=function(a){var b=a.Bd(),c=a.ze();1<a.paragraphs.length&&(c=
a.paragraphs[0].text.length);return{startIndex:b,endIndex:c}},u6a=function(a,b){var c=z.Qz();return b.map(function(a){var b=this.mf.get(a.anchor),g=this.cb.Si(b);if(!g)return a;var k;4==g.type&&(g.Ga()&&(k=b.querySelector("figcaption")),k||(k=b));if(!k){g=a.startIndex+1;b=[b];k=0;for(var l=null;0<b.length&&k<g;)if(l=b.pop(),!(l.nodeName in z.PGa))if(3==l.nodeType){var p=l.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");k+=p.length}else if(l.nodeName in z.xS)k+=z.xS[l.nodeName].length;else for(p=
l.childNodes.length-1;0<=p;p--)b.push(l.childNodes[p]);k=l}g=z.Tz(k,!0);a.offsetTop=Math.round(g.top+c.top);return a},a)},B6a=function(a,b,c){b=z.y;var d='\x3cdiv class\x3d"paragraphControls js-paragraphControl js-paragraphControl-'+z.F(a.aB)+' u-noUserSelect"\x3e',e=z.y,g;if(a.iGa||a.YGa){g='\x3cdiv class\x3d"notesMarker u-noUserSelect" data-action\x3d"select-anchor" data-action-value\x3d"'+z.F(a.aB)+'"\x3e';var k;k={};k=(0,z.y)(z.uo(z.D({name:"asteriskFilled",size:"19px",content:(0,z.O)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14.78 8.07a8.681 8.681 0 0 0-.427-1.383.478.478 0 0 0-.584-.27l-3.12.77V4.034c0-.247-.19-.48-.43-.5a7.23 7.23 0 0 0-1.38 0c-.24.02-.43.253-.43.5V7.19L5.3 6.415a.48.48 0 0 0-.583.27c-.18.448-.324.91-.426 1.383-.05.24.1.5.32.58l3.06.754-1.98 2.956c-.14.196-.13.502.04.67.34.332.7.632 1.09.896.2.136.49.077.63-.117l2.09-3.114 2.09 3.112c.15.193.43.252.63.116.39-.26.75-.56 1.09-.89.17-.17.19-.47.04-.67L11.4 9.41l3.06-.76a.517.517 0 0 0 .32-.58" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
k)));g=g+z.A(k)+"\x3c/div\x3e"}else g="";var l=k="",p="",r=1==a.Wx?z.n("a note"):z.n("notes"),p=p+(""+r),p=z.E(p);1==a.Hga&&(0<a.Wx||a.cy||a.ey)&&(0<a.Wx&&a.cy&&a.ey?(p=z.n("highlighted, responded, and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Wx&&a.ey?(p=z.n("responded and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Wx&&a.cy?(p=z.n("highlighted and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.cy&&a.ey?(p=z.n("highlighted and responded"),l+=" "+p):a.cy?
(p=z.n("highlighted"),l+=" "+p):0<a.Wx?(p=z.n("left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.ey&&(p=z.n("responded"),l+=" "+p));l=z.E(l);k+='\x3cspan class\x3d"paragraphControls-itemText"\x3e';p="";if(0<a.$ha&&0==a.jGa&&!a.cy&&!a.ey)c=1==a.$ha?z.n("Note to self"):z.n("Notes to self"),p+=c;else{r="";if(0<a.bD)var t=z.n("Top highlight"),r=r+t;p+=z.A(z.uR(z.D({social:a.bEa,isActive:0<a.Wx||a.cy||a.ey,zi:a.Hga,B4:!0,uGa:!0,ifa:(0,z.O)(r)},a),c));p+=z.A(l)}p=(0,z.O)(p);k+=z.A(z.ZEa(z.D({text:p},
a)))+"\x3c/span\x3e";a=(0,z.y)(k);a=e(g+a);return b(d+a+"\x3c/div\x3e")},T$=function(a,b,c){z.R.call(this);this.ra=a;this.Ja=a.get("app");this.jqa=a.get("floating-components");this.Na=a.get("screen");this.ub=a.get("screen-service");this.Db=a.get("dom-monitor");this.cb=b;this.Qd=b.Qd;this.Wl=this.Qd.querySelector(".js-postField");this.Yba=this.Na.na().querySelector(".js-notesPositionContainer");this.ve=a.get("quotes-data");this.vf=a.get("notes-data");this.vf.subscribe("new_note_list",this.pua,this);
this.oj=a.get("responses-data");this.Vl=null;this.mf=new W5a(this.Qd.querySelector(".js-notesSource"));this.$F=this.Kh=this.mP=null;this.Kh=new R$(a,b,this.mf,this.Yba);this.track(this.Kh);this.$F=this.Kh.na();this.Mg=this.FZ=null;this.Oe=c},V$=function(a,b){if(a.isActive()){var c=(b=b||a.FZ)&&b.bS,d=b&&b.noteId;c&&(a.uw(c),d&&a.vf.Bp(d,c)&&a.Mg&&z.u(a.Mg,function(){return U$(a,c,null,d)}));z.nma(a.Ja,"")}else a.FZ=b||null},U$=function(a,b,c,d,e,g){var k={Fj:!0,v4:z.rz()};a.i0();c=new N$(a.ra,a.cb,
b,d||"",c||null,a.mf,e||null,g||null);c.subscribe("set-active-highlight",a.Rca,a);c.subscribe("reset-highlight",a.zxa,a);c.subscribe("close",a.i0,a);b=g&&g.Xa?g.Xa:a.mf.get(b);g=z.Tua(a.jqa);g.wn=b;b=g.eD(c);b.tH=k;k=b.XU(a.nn.bind(a));k.fP=!0;a.Vl=k.qa()},C6a=function(a,b,c){var d=a.cb.Si(I$(a.mf,b));if(d&&4!=d.type){z.zw(d,4);if(c){if(!S5a(c,d))return;z.xw(d,z.hw(c.startIndex,c.endIndex,c.id))}c=a.cb.Lb();var e=a.cb.Ya();c={mode:c?"edit":"view",Dj:z.Mw(e),media:null,Kl:null,sections:!0,tk:!1,nk:!1,
ml:!1,Rf:!1,postId:e.id};a.mf.get(b).innerHTML=z.jx(d,z.Tq,c)}},D6a=function(a,b){var c=z.bs();if(!c||c.isCollapsed())if(b&&(c=b),!c||c.isCollapsed())return null;b=c.Uf();var d=Y5a(a.mf,b);if(!d)return null;a=(b=z.Sv(b,z.sD,d))&&a.cb.Si(b);if(!b)return null;var d=z.Vz(c,b,!0),e=z.Vz(c,b,!1);return-1==d||-1==e?null:new T5a(c,b,new z.wx({anchor:b.getAttribute("name"),startIndex:d,endIndex:e,content:a.Ga().substring(d,e)}))},E6a=function(){},W$=function(a,b){z.R.call(this);this.Nh=b||x5a;this.fb=a.get("screen-request");
this.ua=null;this.B1=a.get("screen-view-state");this.ra=a;this.eda=this.I0=!1;this.x_=this.Lc=null},X$=function(a){z.rA.call(this);this.Ey=a},F6a=function(a,b,c){a=z.qa(a)?new z.Yd(a):a;(a=P5a(a,b,c||{}))&&(new X$(a)).focus()},G6a=function(a){this.oa=a.get("request");this.la=a.get("route-builder")},H6a=function(a,b){b=new z.Wk(b.authBaseUrl);return new z.Yd(b.qm(a))},I6a=function(a,b,c){b.content=b.content.replace(/“/g,"‘").replace(/”/g,"’").replace(/„/g,"‚").replace(/'/g,"’");var d=String(a(b,null,
c)),e=Y$(d)-140;0<e&&(b.content=z.xj(b.content,b.content.length-e),d=String(a(b,null,c)));return d},Y$=function(a){var b=a.length;a=a.match(J6a);if(!a)return b;for(var c=0;c<a.length;c++)b+=23-a[c].length;return b},Z$=function(a){z.Uq.call(this);this.ra=a;this.CE=a.get("dialog");this.oa=a.get("request");this.la=a.get("route-builder");this.xa=a.get("butter-bar");this.DH=this.Fa=this.Lw=this.ua=null;this.vN=!1},L6a=function(a){var b=a.Fa.query(".js-tweetEditor-image"),c=a.Fa.query(".js-tweetEditor-imageContainer"),
d=a.Fa.query(".js-tweetEditor-imageStatus");z.kd(c,"u-hide");var e=K6a(a);e.base64=!0;z.w(z.u(a.oa.post(z.mz(B5a),e,{bB:!1,withCredentials:!1}),function(a){b.src="data:image/png;base64,"+a;z.td(c,"u-hide");z.kd(d,"u-hide");this.vN=!0},a),function(a){z.nA(a);z.lz(d,D5a)},a)},M6a=function(a,b){return 140>=Y$(b)?!0:(b=a.Fa.query(".js-tweetEditor-text"),(new z.GA(b,{name:"shimmy-shake",duration:400})).start(),a=a.Fa.query(".js-tweetEditor-error"),z.lz(a,H5a),!1)},K6a=function(a){var b=a.ua,c=a.Lw.bIa;
a=a.Lw.aIa;var d=b.creator,e=b.approvedHomeCollection,g=z.Tq,k=null;e&&(k=e.image);var l=null;e&&e.logo&&e.logo.imageId&&(l=e.logo.imageId);var p=null;e&&e.tintColor&&2==e.colorBehavior&&e.logo&&e.logo.imageId&&(p=e.tintColor);var r=null;e&&e.tintColor&&(r=z.CGa(e.tintColor),r=z.Iv(r,.6).color);return new u$({content:c,altText:a,title:b.title,author:d&&d.name,date:z.ij(b.createdAt,g),authorAvatarId:d&&d.imageId,collection:e&&e.name,collectionAvatarId:k?k.imageId:null,collectionLogoId:l,collectionBackgroundColor:p,
collectionHighlightColor:r,version:2})},N6a=function(a){this.oa=a.get("request");this.la=a.get("route-builder");this.ra=a},$$=function(a,b){z.RZ.call(this);this.Ja=a.get("app");this.la=a.get("route-builder");this.Ha=a.get("model-request");this.ya=a.get("model-store");this.jb=b},O6a=function(a){var b=a.la.ka(z.uwa,null,{sourcePostId:a.jb});z.w(z.u(z.uP(a.Ha,B$,b),function(b){if(b=a.ya.kc(b))z.lz(a.na(),y5a,{cards:b.welcomeCards}),a.toggle()}),z.nA)},P6a=function(a){var b=a.la.ka(z.twa,null,{sourcePostId:a.jb});
z.w(z.u(z.uP(a.Ha,C$,b),function(b){b=a.ya.kc(b);if(b=b.streamItem)z.lz(a.na(),z5a,{placements:b.welcomeContentFirst.placements}),a.toggle()}),z.nA)};z.q(j$,z.L);z.f=j$.prototype;z.f.aa=function(){return""};z.f.ba=function(){return"Placement"};z.f.Bg=function(){return z.J(this,"items")};z.f.Xc=z.h(410);z.f.IC=function(a){return z.K(this,"location",a)};z.f.Td=z.h(460);z.f.Sb=function(a){return z.K(this,"index",a)};z.f.ea=function(){return j$.prototype};
z.f.ca={name:"Placement",fa:!1,fields:{items:{name:"items",g:function(){return z.SN},pa:z.T,h:1},location:{name:"location",g:function(){return z.cya},h:2},index:{name:"index",g:z.V,h:3}},ha:{}};z.f.Td=z.Y(460,function(){return z.J(this,"index")});z.f.Xc=z.Y(410,function(a){return z.K(this,"items",a)});z.m(m$,z.bf);m$.prototype.fk=function(a){var b={};z.sG(this,b,a.Jb(),"");return b};
m$.prototype.Hb=function(a,b){if(!a||!b)return null;var c=new a;Object.keys(b).forEach(function(a){for(var e=a.split(/[[\]]+/).filter(function(a){return!!a}),g=c,k=e.shift();k;){var l=z.Sj(g,k);if(!l)break;var p=l.g();if(l.pa()){var r=z.Nj(g,k)||[],t=e.shift(),v=Number(t);if(void 0===t||!Number.isInteger(v)||0>v)break;if(p.prototype instanceof z.Hj)l=r[v],l||(l=new p,r[v]=l),z.K(g,k,r),g=l;else{if(void 0!==e.shift())break;p=h5a(b[a],l);r[v]=p;z.K(g,k,r)}}else if(p.prototype instanceof z.Hj)r=z.Nj(g,
k),r||(r=new p,z.K(g,k,r)),g=r;else{if(void 0!==e.shift())break;p=h5a(b[a],l);z.K(g,k,p)}k=e.shift()}});return c};z.q(n$,z.dk);z.f=n$.prototype;z.f.aa=function(){return""};z.f.ba=function(){return""};z.f.HB=z.h(457);z.f.ea=function(){return n$.prototype};z.f.ca={name:"PlacementsResponse",fa:!1,fields:{placements:{name:"placements",g:function(){return j$},pa:z.T,h:1}},ha:{}};z.q(o$,z.L);o$.prototype.aa=function(){return""};o$.prototype.ba=function(){return""};o$.prototype.ea=function(){return o$.prototype};
o$.prototype.ca={name:"PlacementsRequestQuery",fa:!1,fields:{requestContext:{name:"requestContext",g:function(){return z.Au},h:1},slots:{name:"slots",g:function(){return z.Cu},pa:z.T,h:2}},ha:{}};z.XX.prototype.hU=z.Y(612,function(a){a!=this.LN&&this.xb&&(this.xb.ci.contentEditable=a);this.LN=a});z.zI.prototype.x3=z.Y(604,function(a){a=p$(a);if(!a)return null;a=q$(a)&&q$(a).Ln();return a?(a=a.jc())&&a.length?a[0].getName():null:null});z.SG.prototype.XU=z.Y(603,function(a){this.nn=a;return this});
z.MI.prototype.XU=z.Y(602,function(a){this.nn=a;return this});z.RA.prototype.Bp=z.Y(513,function(){return z.J(this,"note")});z.mG.prototype.Bp=z.Y(512,function(a){return this.qc("Note",a)});z.vx.prototype.sx=z.Y(492,function(){return z.J(this,"replyId")});z.RA.prototype.sx=z.Y(491,function(){return z.J(this,"replyId")});z.tx.prototype.ly=z.Y(490,function(a){return z.K(this,"highlight",a)});z.tx.prototype.rR=z.Y(489,function(){return z.J(this,"highlight")});
z.tx.prototype.Uu=z.Y(488,function(a){return z.K(this,"author",a)});z.vx.prototype.Uu=z.Y(487,function(a){return z.K(this,"author",a)});z.tx.prototype.kI=z.Y(486,function(){return z.J(this,"author")});z.vx.prototype.kI=z.Y(485,function(){return z.J(this,"author")});z.tx.prototype.CB=z.Y(484,function(){return z.J(this,"highlightId")});z.tx.prototype.bv=z.Y(483,function(a){return z.K(this,"state",a)});z.vx.prototype.bv=z.Y(482,function(a){return z.K(this,"state",a)});
z.LA.prototype.bv=z.Y(481,function(a){return z.K(this,"state",a)});z.tx.prototype.Cg=z.Y(480,function(){return z.J(this,"noteId")});z.vx.prototype.Cg=z.Y(479,function(){return z.J(this,"noteId")});z.RA.prototype.Cg=z.Y(478,function(){return z.J(this,"noteId")});z.dv.prototype.Vu=z.Y(473,function(a){return z.K(this,"authorId",a)});z.tx.prototype.Vu=z.Y(472,function(a){return z.K(this,"authorId",a)});z.vx.prototype.Vu=z.Y(471,function(a){return z.K(this,"authorId",a)});
z.NM.prototype.HB=z.Y(458,function(){return z.J(this,"placements")});n$.prototype.HB=z.Y(457,function(){return z.J(this,"placements")});z.tG.prototype.HB=z.Y(456,function(a,b){var c=this;a=j5a(k5a(new o$,a),b);a=(new m$).fk(a);var d=this.la.ka(z.gwa,{},a);return z.uG(this,d,function(){return z.u(c.oa.get(d,{background:!0}),function(a){a=c.Ha.bc(n$,a);c.ya.kc(a);return a})})});z.au.prototype.Je=z.Y(371,function(){return z.J(this,"catalogId")});z.$L.prototype.Je=z.Y(370,function(){return z.J(this,"catalogId")});
z.SL.prototype.Je=z.Y(369,function(){return z.J(this,"catalogId")});z.QL.prototype.Je=z.Y(368,function(){return z.J(this,"catalogId")});z.SN.prototype.Je=z.Y(367,function(){return z.J(this,"catalogId")});z.rL.prototype.Je=z.Y(366,function(){return z.J(this,"catalogId")});z.wN.prototype.Je=z.Y(365,function(){return z.J(this,"catalogId")});z.oM.prototype.Je=z.Y(364,function(){return z.J(this,"catalogId")});z.oN.prototype.Je=z.Y(363,function(){return z.J(this,"catalogId")});
z.nN.prototype.Je=z.Y(362,function(){return z.J(this,"catalogId")});z.mN.prototype.Je=z.Y(361,function(){return z.J(this,"catalogId")});z.dv.prototype.Je=z.Y(360,function(){return z.J(this,"catalogId")});z.RA.prototype.Je=z.Y(359,function(){return z.J(this,"catalogId")});z.mJ.prototype.Je=z.Y(358,function(){return z.J(this,"catalogId")});z.Os.prototype.JR=z.Y(82,function(){return z.J(this,"point")});
s$.prototype.JR=function(){var a=window.document.body;return z.Jh(a,this.ji.node)?this.ji:this.Hk&&z.Jh(a,this.Hk)?z.DO(this.qO,this.Hk):this.Ne&&(a=z.Vv(this.fqa,this.Ne))?z.DO(this.qO,a):null};z.q(t$,z.gr);t$.prototype.MJ=function(){if(!this.Uj)return null;var a=this.Uj.JR();if(!a)return null;var b=this.Zl.JR();return b?z.Pr(a.node,a.offset,b.node,b.offset):null};z.q(u$,z.L);z.f=u$.prototype;z.f.aa=function(){return""};z.f.ba=function(){return""};z.f.kb=function(){return z.J(this,"content")};
z.f.qd=function(a){return z.K(this,"content",a)};z.f.Fb=function(){return z.J(this,"title")};z.f.Oc=function(a){return z.K(this,"title",a)};z.f.kI=function(){return z.J(this,"author")};z.f.Uu=function(a){return z.K(this,"author",a)};z.f.getDate=function(){return z.J(this,"date")};z.f.setDate=function(a){return z.K(this,"date",a)};z.f.Eb=function(){return z.J(this,"collection")};z.f.setVersion=function(a){return z.K(this,"version",a)};z.f.fK=function(a){return z.K(this,"template",a)};
z.f.Ud=function(){return z.J(this,"subtitle")};z.f.zf=function(a){return z.K(this,"subtitle",a)};z.f.ea=function(){return u$.prototype};
z.f.ca={name:"TextshotInfo",fa:!1,fields:{content:{name:"content",g:z.U,h:1},altText:{name:"altText",g:z.U,h:2},title:{name:"title",g:z.U,h:3},author:{name:"author",g:z.U,h:4},date:{name:"date",g:z.U,h:5},authorAvatarId:{name:"authorAvatarId",g:z.U,h:6},collection:{name:"collection",g:z.U,h:7},collectionAvatarId:{name:"collectionAvatarId",g:z.U,h:8},collectionLogoId:{name:"collectionLogoId",g:z.U,h:9},collectionBackgroundColor:{name:"collectionBackgroundColor",g:z.U,h:10},collectionHighlightColor:{name:"collectionHighlightColor",
g:z.U,h:11},version:{name:"version",g:z.V,h:12},base64:{name:"base64",g:z.uJ,h:13},template:{name:"template",g:z.U,h:14},mainStat:{name:"mainStat",g:z.U,h:15},mainStatTitle:{name:"mainStatTitle",g:z.U,h:16},subtitle:{name:"subtitle",g:z.U,h:17},icon:{name:"icon",g:z.U,h:18},imgKey:{name:"imgKey",g:z.U,h:19}},ha:{}};z.q(w$,z.R);z.f=w$.prototype;z.f.gk=function(){return this.em.gk()};
z.f.ma=function(){w$.va.ma.call(this);z.tA(this,this.rY,"data-redirect-type-quote",this.Cta,this);this.Pa(this.Qd,"click",this.Qv,this);z.TH(this.cb)&&z.pz()&&this.Pa(this.Qd,"mouseover",this.Yqa,this);this.cb.Ya().nr()&&!this.cb.Lb()&&z.w(this.ve.load(this.cb.La()),z.nA);var a=this.gk();a&&(z.tA(this,a,"quote",this.Tqa,this),z.tA(this,a,"quote-respond",this.Uqa,this),z.tA(this,a,"show",this.t1,this),z.tA(this,a,"hide",this.Vta,this))};
z.f.Cta=function(a){var b=z.EH(this.em,this.gk().Iw);b&&(a.url=new z.Yd(this.la.ka(z.tza,{postId:this.cb.La()},{paragraphs:JSON.stringify([b.zx.Hb().Jb()]),startOffset:b.start,endOffset:b.end})))};z.f.Qv=function(a){z.Sv(a.target,function(a){if(a===this.Qd)return!0;var c=z.BD(a);if(3==c)return!0;if(7==c){if(c=L5a(this,a))if(x$(this,c),z.pz())z$(this,c);else{var d=new z.ME;J5a(this,c,a,d)}return!0}return!1}.bind(this))};
z.f.Yqa=function(a){z.Sv(a.target,function(a){if(a===this.Qd)return!0;var c=z.BD(a);if(3==c)return!0;if(7==c){c=z.bs();if(!(c&&!c.isCollapsed()||this.gk()&&this.gk().Dm())&&(c=L5a(this,a))){var d=this.Qd.querySelector('.markup--quote[name~\x3d"'+c.Ti()+'"]');a=new z.NG(a,100);J5a(this,c,d,a);x$(this,c)}return!0}return!1}.bind(this))};
z.f.t1=function(){var a=z.bs();a&&!a.isCollapsed()&&x$(this,null);z.TH(this.cb)&&(a=z.EH(this.em,this.gk().Iw))&&(a=z.Ksa(this.ve,a.zx,a.start,a.end),z.vd(this.gk().Sa().querySelector(".js-highlightMenuQuoteButton"),"is-active",!!a))};z.f.Vta=function(){this.gp&&x$(this,null)};
z.f.Tqa=function(){if(z.TH(this.cb)){var a=z.zH(this.gk());if(a){var b=a.range,c=a.sFa,d=z.jd(this.gk().Sa().querySelector(".js-highlightMenuQuoteButton"),"is-active"),a=z.EH(this.em,b);z.w(z.u(this.ve.toggle(a.zx,a.start,a.end,!c),function(a){z.GGa();d?z.BH(this.gk()):z$(this,a);var b=c?"selection_menu":"quote_click_menu";A$(this,a.Ti(),!d,b)},this),z.nA)}}};
z.f.Uqa=function(){if(z.TH(this.cb)&&z.Tq.supportsEdit){var a=z.zH(this.gk());if(a){var b=z.EH(this.em,a.range);z.w(z.u(this.ve.create(b.zx,b.start,b.end,1,!0),function(a){A$(this,a.Ti(),!0,"selection_menu_quote_respond");this.za("quote-respond",a,b.zx.name)},this),z.nA)}}};
z.f.fra=function(a){var b=this.gp,c=y$(this,b),d=b.Bd(),e=b.ze(),b=a.query(".js-quoteAttributions-pileOn"),g=z.jd(b,"is-active");z.w(z.u(this.ve.toggle(c,d,e,!0),function(b){var l=a.query(".js-quoteAttributions-pileOn");z.yd(l,"is-active");if(l=z.vH(this.ve,c,d,e)){var p=I5a(this,l),r=a.query(".js-quoteAttributions-info");z.lz(r,t5a,p)}else a.Tc();!g&&z.pz()&&(a.Tc(),z$(this,l));l=z.pz()?"quote_hover":"quote_click_mobile";A$(this,b.Ti(),!g,l)},this),z.nA)};
z.f.gra=function(){if(z.TH(this.cb)&&z.Tq.supportsEdit){var a=y$(this,this.gp),b=this.gp.Bd(),c=this.gp.ze();z.w(z.u(this.ve.create(a,b,c,1,!0),function(b){A$(this,b.Ti(),!0,"quote_respond");this.za("quote-respond",b,a.name)},this),z.nA)}};z.f.hra=function(){var a=N5a(this,this.gp);a&&z.Usa(this.em,a)};
z.f.Gca=function(){var a=new t$(this.Qd),b=this.ve.wt,c=Object.keys(b).concat(this.g$);z.db(c);c.forEach(function(a){var c=b[a]||[],g=this.cb;if(g=(a=g.Qd&&z.Vv(g.Qd,a))&&this.cb.Si(a))s5a(g,c),a.innerHTML=z.jx(g,z.Tq,z.eta(this.cb)),z.bva(this.Ewa,a)},this);this.g$=Object.keys(b);(a=a.restore())&&a.select()};z.q(B$,z.dk);B$.prototype.aa=function(){return""};B$.prototype.ba=function(){return""};B$.prototype.ea=function(){return B$.prototype};
B$.prototype.ca={name:"OnboardingWelcomeHomepagePromoResponse",fa:!1,fields:{welcomeCards:{name:"welcomeCards",g:function(){return z.xM},pa:z.T,h:1}},ha:{}};z.q(C$,z.dk);C$.prototype.aa=function(){return""};C$.prototype.ba=function(){return""};C$.prototype.ea=function(){return C$.prototype};C$.prototype.ca={name:"OnboardingWelcomeResponse",fa:!1,fields:{streamItem:{name:"streamItem",g:function(){return z.SN},h:1}},ha:{}};z.q(D$,z.rA);z.f=D$.prototype;
z.f.load=function(a){if(!z.mu())return z.dd([]);this.jb=a;this.Hh||(this.Hh=z.w(z.u(this.al.get(this.la.ka(z.lza,{postId:a}),{background:!0}),this.Cwa,this),z.nA));return this.Hh.Zc()};z.f.Kp=function(){return this.d$};z.f.hk=function(){return this.eca};z.f.rR=function(a){return this.uaa[a]||null};z.f.Bp=function(a,b){return z.PP(E$(this,b),a)};z.f.ly=function(a,b){this.uaa[a]=b};z.f.La=function(){return this.jb};
z.f.Cwa=function(a){var b=a.references.User;this.eca=a.post.visibility;var c=a.value;if(c)for(var d=0;d<c.length;d++){var e=c[d];if("HIDDEN"!=e.state){var g=e.replies,k=b;if(g)for(var l=0;l<g.length;l++){var p=g[l],r=p.authorId||null;p.author=r&&k[r]||null}g=e.anchor;k=e.authorId||null;e.author=k&&b[k]||null;g=E$(this,g);e=z.ux(e);g.add(z.mE(this.ya,e))}}if(a=a.highlights)for(b=0;b<a.length;b++)this.ly(a[b].id,z.Hs.Hb(z.wx,a[b]));this.d$=!0};z.m(H$,z.R);H$.prototype.ma=function(){var a=this;z.R.prototype.ma.call(this);z.u(this.fb.HB(this.hP,this.owa),function(b){b.placements&&b.placements.forEach(a.Tra,a)})};
H$.prototype.Tra=function(a){if(this.isActive()){var b=null;switch(a.location){case 1:b=this.Na.query(".js-postFooterPlacements");if(!b)break;z.lz(b,z.LR,{items:a.items,context:9});z.S(b).ia("show-more-recommendations",this.aza,this);break;case 2:b=this.Na.query(".js-readNextMetabarRight");if(!b)break;z.lz(b,z.LR,{items:a.items,context:2});break;case 6:(b=this.Na.query(".js-postPromotionWrapper"))&&z.lz(b,z.LR,{items:a.items,context:2})}b&&U5a(this,b)}};
H$.prototype.aza=function(a){z.WA(z.ZCa,{});var b=this.Na.query(".js-moreRecommendations");b&&(z.Yv(b),z.Xv(a.target))};V5a.prototype.OQ=function(a,b,c){return new w$(a,b,c)};W5a.prototype.get=function(a){return I$(this,a)};z.q(J$,z.XX);z.f=J$.prototype;z.f.bH=!1;z.f.Qz="";z.f.cH=0;z.f.Mp=z.T;z.f.Cg=function(){return this.f_};z.f.save=function(){this.kb().length<=this.dm&&this.dl()};z.f.Ib=function(){(0,window.clearTimeout)(this.cH);J$.va.Ib.call(this)};
z.f.ma=function(){function a(a){a.stopPropagation()}J$.va.ma.call(this);this.Qz=this.kb();this.qd(this.Qz);this.Tw(13,this.k_,this);this.Tw(27,this.l_,this);this.xb.Pa("blur",this.j_,!1,this);var b=this.xb.Sa();z.Iz(b,"keydown",a);z.Iz(b,"keyup",a);z.Iz(b,"keypress",a)};z.f.B5=function(a){return a};
z.f.dl=function(){if(this.isEnabled()){var a=this.kb().trim();if(a){this.hU(!1);var b=this.bga(),a=this.aga(a);this.za("saving",a);z.Uc(z.w(z.u(this.al.post(b,a.Jb()),this.tua,this),this.rua.bind(this,a)),this.hU.bind(this,!0))}}};z.f.tua=function(a){this.za("save",this.B5(a.value))};z.f.rua=function(a,b){this.za("fail",a);this.Fa.error(Z5a());z.nA(b)};z.f.k_=function(a){if(this.It&&z.LY(this.It))return!1;a.shiftKey||(a.preventDefault(),this.save());return!0};
z.f.l_=function(a){if(this.It&&z.LY(this.It))return!1;a.preventDefault();this.qd(this.Qz);this.za("cancel");return!1};z.f.j_=function(){this.bH&&(this.kb().length>=this.dm?(0,window.confirm)(this.dga())?(this.qd(this.Qz),this.za("cancel")):this.focus():this.cH=(0,window.setTimeout)(this.dl.bind(this),100))};z.q(K$,J$);z.f=K$.prototype;z.f.uW=null;z.f.v9=null;z.f.vW=null;z.f.Oj=null;z.f.TY=null;z.f.RY=null;z.f.taa=null;z.f.ly=function(a){this.Oj=a;this.TY=a.startIndex;this.RY=a.endIndex;this.taa=a.content;return this};z.f.dga=function(){var a=z.n("Your note is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};z.f.B5=function(a){var b=z.jz();a=z.ux(a).Uu(b).Vu(b.lb());this.Oj&&a.CB()&&this.vf.ly(a.CB(),this.Oj);var b=this.vf,c;c=z.mE(b.ya,a);E$(b,c.pe()).add(c);return a};
z.f.bga=function(){return this.Cg()?this.la.ka(z.mza,{postId:this.jb,noteId:this.Cg()}):this.la.ka(z.kza,{postId:this.jb})};z.f.aga=function(a){var b=z.jz();a=(new z.tx({content:a,anchor:this.uW,anchorContent:this.v9,anchorImage:this.vW?this.vW.Jb():null,replies:[],createdAt:Date.now()})).Uu(b);null!=this.TY&&null!=this.RY&&(b=new z.wx({anchor:this.uW,startIndex:this.TY,endIndex:this.RY,content:this.taa}),a.ly(b));return a};z.q(L$,J$);L$.prototype.dga=function(){var a=z.n("Your reply is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};L$.prototype.B5=function(a){var b=z.jz();a=z.Yia(a).Uu(b).Vu(b.lb());z.J(this.vf.Bp(a.Cg(),this.Ne),"replies").push(a);return a};L$.prototype.bga=function(){return this.Cca?this.la.ka(z.pza,{postId:this.jb,noteId:this.Cg(),replyId:this.Cca}):this.la.ka(z.oza,{postId:this.jb,noteId:this.Cg()})};
L$.prototype.aga=function(a){var b=z.jz();return(new z.vx({replyId:"",postId:this.jb,noteId:this.Cg(),content:a,createdAt:Date.now()})).Uu(b)};z.q(N$,z.R);z.f=N$.prototype;
z.f.ma=function(){N$.va.ma.call(this);z.S(this.na()).ia("show-note-editor",this.N0,this).ia("hide-note-editor",this.NY.bind(this,!0)).ia("show-reply-editor",this.oza,this).ia("hide-reply-editor",this.Cra,this).ia("save-note",this.Qxa,this).ia("save-reply",this.Sxa,this).ia("highlight-quote",this.Fra,this).ia("dismiss-note",this.k$.bind(this,!0),this).ia("delete-note",this.k$.bind(this,!1),this).ia("delete-reply",this.opa,this).ia("previous-highlight-tip",this.Awa,this).ia("next-highlight-tip",this.gta,
this);m6a(this);this.oj&&k$(this.oj)&&(l6a(this),z.tA(this,k$(this.oj),"add",this.qua,this));if(this.$_&&this.Gaa&&this.Iaa){var a=this.query(".js-inlineNewPostControl"),b=this.$_,c=this.cb.La(),d=new z.$T(this.ra);d.XJ("web-inline-quote-responses");d.Ua(a);d.HE=!0;d.DX=!0;d.zX=!0;d.fK(u5a);d.Pz=b;d.aK(c);z.aU(d,!0);this.Lc=d;this.Lc.qa();a=P$(this.FG);this.za("set-active-highlight",this.Ne,a)}this.Oj&&(this.N0(),this.Pf&&this.Pf.focus());Q$(this,0)};
z.f.Aa=function(){this.Dq&&this.Dq.J2();(this.Oj||this.FG)&&this.za("reset-highlight",this.Ne,null);N$.va.Aa.call(this)};z.f.Ib=function(){z.cB(this.na());z.Ch(this.na());z.Wq(this.Lc);z.Wq(this.Pf);z.Wq(this.Dq);z.Xq(z.nb(this.Rj));this.Dq=this.Rj=this.Pf=this.Lc=null;N$.va.Ib.call(this)};z.f.Rn=function(){if(this.Pf&&this.Pf.kb())return!0;for(var a=z.nb(this.Rj),b=0;b<a.length;b++)if(a[b]&&a[b].kb())return!0;return this.Lc&&!this.Lc.isDismissable()?!0:!1};
z.f.Dv=function(){var a=[],b=[],c=[],d=this.Tz&&(this.Oj||this.FG);d||(this.Xv?(a=this.ve?l$(this.ve,this.Xv.quotes):[],b=this.Xv.notes,c=this.Xv.responses):(b=this.vf?z.wE(E$(this.vf,this.Ne)):[],this.f_||(this.ve?(a=this.ve,a=l$(a,a.wt[this.Ne]||[])):a=[],c=this.oj?r$(this.oj,this.Ne):[])));return z.nz(i6a,{post:this.cb.Ya(),quotes:a,notes:b,responses:c,k7:!!this.$_,oU:d,iK:this.Tz,bD:this.Jda,kGa:z.SH(this.cb)})};
z.f.qua=function(){var a=this.query(".js-postList"),b=z.nz(h6a,{responses:r$(this.oj,this.Ne)});z.Dh(b,a);l6a(this)};
z.f.N0=function(){if(this.Tz){if(!this.Pf){var a=this.query(".js-noteEditor"),b=z.mz(f6a),a=this.Pf=new K$(this.ra,a,this.cb.La(),null,b),b=this.Ne,c=this.cb.Si(this.mf.get(this.Ne)),d=c.Ga(),c=4==c.type?c.Ae():null;a.uW=b;a.v9=d;a.vW=c;(a=this.Oj)&&this.Pf.ly(a);z.tA(this,this.Pf,"saving",this.Yua,this);z.tA(this,this.Pf,"fail",this.Tta,this);z.tA(this,this.Pf,"save",this.Sua,this)}z.kd(this.query(".js-noteActions"),"is-noteEditorVisible");this.Pf&&this.Pf.focus()}};z.f.Qxa=function(){this.Pf&&this.Pf.save()};
z.f.Yua=function(a){this.Pf.qd("");var b=this.query(".js-notesList");a={note:a,post:this.cb.Ya(),oU:this.Tz,iK:this.Tz};a=z.nz(M$,a);b.appendChild(a);z.td(b,"is-empty");m6a(this);this.NY()};z.f.Sua=function(a){var b=this.query(".js-notesList").lastChild;a=a.Cg();z.kd(b,"js-note-"+a);b.setAttribute("data-note-id",a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};z.f.Tta=function(){var a=this.query(".js-notesList");a.removeChild(a.lastChild);z.kd(a,"is-empty");this.N0()};
z.f.NY=function(a){a?this.za("close"):this.Pf&&(this.Pf.kb()&&this.Pf.qd(""),z.td(this.query(".js-noteActions"),"is-noteEditorVisible"))};z.f.oza=function(a){(a=O$(a.target))&&this.Tz&&n6a(this,a)};z.f.Sxa=function(a){a=O$(a.target);(a=this.Rj[a])&&a.save()};
z.f.Zua=function(a){var b=a.Cg();this.Rj[b]&&this.Rj[b].qd("");var c=this.vf.Bp(b,this.Ne).author.userId==a.author.userId,d=this.query(".js-note-"+a.Cg()+" .js-repliesList");a={note:a,post:this.cb.Ya(),gha:c};a=z.nz(M$,a);d.appendChild(a);z.td(d,"is-empty");o6a(this,b)};z.f.Tua=function(a){var b=this.query(".js-note-"+a.Cg()).querySelector(".js-repliesList").lastChild;a=a.sx();z.kd(b,"js-reply-"+a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.Uta=function(a){var b=this.query(".js-note-"+a.Cg()+" .js-repliesList");b.removeChild(b.lastChild);z.kd(b,"is-empty");n6a(this,a.Cg())};z.f.Cra=function(a){(a=O$(a.target))&&o6a(this,a)};z.f.Fra=function(a){a=a.target;var b=a.getAttribute("data-quote-creator-id"),c=I$(this.mf,this.Ne);c&&(this.Dq&&this.Dq.J2(),this.Dq=q6a(this,c,a,function(){p6a(this,b,!1);z.Wq(this.Dq);this.Dq=null}),p6a(this,b,!0))};
z.f.Era=function(a){var b=I$(this.mf,this.Ne);(a=this.vf.Bp(a.target.getAttribute("data-note-id"),this.Ne))&&b&&(b=(b=a.CB())?this.vf.rR(b):null,this.za("set-active-highlight",this.Ne,b))};z.f.Gra=function(a){var b=I$(this.mf,this.Ne),c;c=this.oj;a=a.target.getAttribute("data-post-id");c=k$(c)?z.PP(k$(c),a):null;b&&c&&(b=p$(c))&&(b=q$(b)&&q$(b).Ln())&&(c=b.jc())&&c.length&&(b=P$(b),this.za("set-active-highlight",this.Ne,b))};
z.f.r1=function(){var a=null;this.FG&&(a=P$(this.FG));this.Oj&&(a=this.Oj);this.za("reset-highlight",this.Ne,a)};
z.f.k$=function(a,b){b=b.value;var c=this.vf.Bp(b,this.Ne),d=this.query(".js-note-"+b);if(c&&d){z.Xv(d);this.r1();this.pb(".js-note-item").every(function(a){return z.jd(a,"u-hide")})&&this.NY(!0);var e=F$(this.vf,c,"HIDDEN");z.w(e.ql,function(b){this.xa.qa(a?$5a():a6a(),"error");e.NJ();z.Yv(d);(400>b.status||499<b.status)&&F$(this.vf,c,"NEW")},this);z.u(this.xa.qa(a?c6a():d6a(),{type:"success",cD:!0}),function(){this.xa.Tc();e.NJ();F$(this.vf,c,"NEW");z.Yv(d)},this)}};
z.f.opa=function(a){var b=a.value,c=this.query(".js-reply-"+b),d=O$(a.target);if(d&&c){z.Xv(c);var e=G$(this.vf,b,d,this.cb.La(),this.Ne,"HIDDEN");z.w(e.ql,function(){this.xa.qa(b6a(),"error");e.NJ();z.Yv(c);G$(this.vf,b,d,this.cb.La(),this.Ne,"")},this);z.u(this.xa.qa(e6a(),{type:"success",cD:!0}),function(){this.xa.Tc();e.NJ();G$(this.vf,b,d,this.cb.La(),this.Ne,"");z.Yv(c)},this)}};z.f.Awa=function(){Q$(this,this.qN-1)};z.f.gta=function(){Q$(this,this.qN+1)};z.q(R$,z.R);z.f=R$.prototype;z.f.ma=function(){R$.va.ma.call(this);var a=[];z.SH(this.cb)&&a.push(this.vf.load(this.jb));this.Naa||(a.push(this.ve.load(this.jb)),a.push(this.oj.load(this.jb)));this.Gv=z.u(z.u(z.u(z.VS(a),function(){this.Gv=null},this),this.Tr,this),this.goa,this);z.tA(this,this.Db,"resize-end",this.mg,this)};z.f.Aa=function(){this.Gv&&this.Gv.cancel();R$.va.Aa.call(this)};z.f.Ib=function(){this.Gv=null;R$.va.Ib.call(this)};z.f.Tr=function(){X5a(this.mf,function(a,b){S$(this,b)},this)};
z.f.mg=function(){X5a(this.mf,function(a,b){x6a(this,b)},this)};z.f.goa=function(){var a=this.ve.Vo;z.tA(this,a,"add",this.Nba,this);z.tA(this,a,"remove",this.Nba,this);(a=k$(this.oj))&&z.tA(this,a,"add",this.Pua,this)};z.f.Nba=function(a){r6a(this,Object.keys(z.Osa(this.ve,a instanceof Array?a:[a])))};z.f.Pua=function(a){r6a(this,(a instanceof Array?a:[a]).map(this.oj.x3,this.oj))};z.f.Dv=function(a){var b=window.document.createElement("div");b.className="notesMarkers";a.appendChild(b);return b};
z.f.bG=function(a,b){z.wb(a,{startIndex:Math.min(a.startIndex,b.startIndex),endIndex:Math.max(a.endIndex,b.endIndex),notes:a.notes.concat(b.notes),quotes:a.quotes.concat(b.quotes),responses:a.responses.concat(b.responses)})};z.q(T$,z.R);z.f=T$.prototype;
z.f.ma=function(){T$.va.ma.call(this);this.Pa(this.Na.na(),"click",this.Isa,this,!0);z.S(this.$F).ia("select-anchor",this.bva,this);var a=this.cb.Ya();if(a.nr()&&!this.cb.Lb()){var b=z.Nt(a),b=2==a.visibility&&b&&!z.J(b.Cl(),"memberOfMembershipPlanId");a.allowResponses&&!b&&z.w(this.oj.load(this.cb.La(),"best"),z.nA);z.w(this.ve.load(this.cb.La()),z.nA)}a.Cl().jI()&&(this.oO=z.u(this.vf.load(this.cb.La()),this.uua,this));this.FZ&&V$(this,null);z.tA(this,this.ub,"historyUpdate",function(){V$(this,
z.HH())},this);this.Oe&&z.tA(this,this.Oe,"highlight",this.sua,this)};z.f.Ib=function(){z.Wq(this.Kh);this.Kh=null;z.Wq(this.Vl);this.Vl=null;this.$F&&z.S(this.$F).clear("select-anchor");this.oO&&this.oO.cancel();this.oO=null;T$.va.Ib.call(this)};z.f.qGa=function(a,b){U$(this,b,null,null,a)};z.f.qIa=function(){this.Kh&&this.Kh.mg()};z.f.Rn=function(){if(!this.Vl)return!1;var a=this.Vl.kb();return a?a.Rn():!1};z.f.pua=function(a){a.subscribe("add",this.Rda,this);a.subscribe("remove",this.Rda,this)};
z.f.Rda=function(a){(z.oa(a)?a:[a]).forEach(function(a){S$(this.Kh,a.pe())},this)};z.f.uua=function(){var a=(0,z.Ia)();this.oO=null;V$(this,z.HH());this.Pa(this.Wl,z.XJ,this.u_,this);z.OB("notes.renderMarkers",(0,z.Ia)()-a)};z.f.u_=function(a){(a=a.target.getAttribute("name"))&&I$(this.mf,a)&&x6a(this.Kh,a)};z.f.sua=function(){if(this.Oe){var a=D6a(this,this.Oe.Iw);z.BH(this.Oe);a&&(a=a.highlight,this.Rca(a.anchor,a),U$(this,a.anchor,a))}};
z.f.Isa=function(a){if(this.Vl){var b=a.target;if(!z.Jh(this.Vl.na(),b)){var c=this.Vl.kb(),d;if(!(d=!c)){a:if(c.Pf&&c.Pf.kb())c=!0;else{d=z.nb(c.Rj);for(var e=0;e<d.length;e++)if(d[e]&&d[e].kb()){c=!0;break a}c=c.Lc&&!c.Lc.Xi()?!0:!1}d=!c}d&&(c=this.Vl&&this.Vl.wn,d="select-anchor"==b.getAttribute("data-action"),this.i0(),c&&d&&z.Jh(c,b)&&a.stopPropagation())}}};
z.f.nn=function(a){if(!z.rz()){var b=a.wn,c=z.Tz(b);a.wl();a=a.na();var d=z.Tz(a),e=window.innerHeight,g=window.innerWidth,k=this.Na.query(".js-metabar"),l=0;k&&(l=z.Tz(k).height);d.height>=e-l?Q5a(a):(z.Pz(b),b=c.top+d.height>=e?z.Qz().top+e-d.height-10:z.Pz(b),c=z.Tz(this.$F).left+10,c+d.width>=g&&(c=g-d.width-10),a.style.top=b+"px",a.style.left=c+"px")}};z.f.i0=function(){z.Wq(this.Vl);this.Vl=null};
z.f.bva=function(a){var b=z.Sv(a.target,function(a){return z.jd(a,"js-paragraphControl")},this.Yba),b=y6a(this.Kh,a.value,b);U$(this,a.value,null,null,null,b)};z.f.Rca=function(a,b){if(this.cb.Lb()){var c=z.bs();this.mP=(c=c&&Y5a(this.mf,c.Uf()))&&new t$(c)}C6a(this,a,b)};z.f.zxa=function(a,b){C6a(this,a,b);this.cb.Lb()&&this.mP&&(a=this.mP.restore())&&a.select();this.mP=null};
z.f.uw=function(a){if(this.mf&&(a=I$(this.mf,a))){a=Math.max(z.Pz(a),0);var b=window.document.body;this.Mg&&this.Mg.cancel();this.Mg=new z.sz(b,"scrollTop",600,a)}};E6a.prototype.OQ=function(a,b,c){return new T$(a,b,c)};z.m(W$,z.R);z.f=W$.prototype;z.f.tc=function(a){this.ua=a};z.f.fK=function(a){this.Nh=a};z.f.tHa=function(a){this.I0=a};z.f.uHa=function(a){this.eda=a};
z.f.ma=function(){this.na()?(z.R.prototype.ma.call(this),z.S(this.na()).ia("show-responses-stream-editor",this.mva,this).ia("show-other-responses",this.kda,this),z.lz(this.na(),this.Nh,{post:this.ua}),this.ua.nr()&&z.w(z.u(z.u(z.u(r5a(this.fb,this.ua.Cb(),"best"),this.Aca.bind(this,"best")),this.gxa,this),function(){this.B1.G6&&this.kda()},this),z.nA)):z.nA("Attempted to initialize ResponsesStreamControl without root element.")};z.f.Aa=function(){z.S(this.na()).clear("show-other-responses");z.R.prototype.Aa.call(this)};
z.f.Aca=function(a,b){this.isActive()&&(b=b.ke,"best"==a?(a=this.query(".js-responsesStream"),z.tA(this,b,"add",this.qba.bind(this,b)),this.qba(b)):a=this.query(".js-responsesStreamOther"),b&&(z.ou()||0<b.Re())&&a&&(z.lz(a,z.LR,{items:z.wE(b),context:2}),b=new z.BU(this.ra,b),b.Ua(a),b.rd(2),this.track(b),z.Yv(this.query(".js-responsesStreamWrapper"))),this.eda&&(a=z.Pz(a),z.Mz(window.document.body,0,a)))};
z.f.gxa=function(){var a=this.query(".js-inlineNewPostControl"),b=this.query(".js-responsesLoggedOutPrompt");z.ou()?a?(this.Lc=z.aU(l5a((new z.$T(this.ra)).XJ("web-inline-post-response").aK(this.ua.Cb()),z.kz(z.Yk,{post:this.ua,$T:!0})),this.I0).Ua(a),this.track(this.Lc)):b&&this.I0&&(a=z.Oz(b),b=z.Pz(b),z.Mz(a,0,b)):b&&z.kd(b,"u-hide")};
z.f.kda=function(){this.x_||(this.x_=z.Uc(z.u(z.u(r5a(this.fb,this.ua.Cb(),"other"),this.Aca.bind(this,"other")),function(){z.Xv(this.query(".js-showOtherResponses"));this.B1.G6=!0},this),function(){this.x_=null},this))};z.f.qba=function(a){(a=a.Wk)&&a.next&&"other"==a.next.filter&&!this.B1.G6&&(z.Yv(this.query(".js-responsesStreamWrapper")),z.Yv(this.query(".js-showOtherResponses")))};z.f.ex=function(){this.Lc&&(z.IS(this.Lc.na(),new z.hs(60,0,200,0)),this.Lc.ex())};
z.f.mva=function(){var a=this.query(".js-responsesStreamEditor"),b=this.query(".js-showResponsesStreamEditorButton");z.lS(a)&&(z.Yv(a),z.Xv(b),this.ex())};z.q(X$,z.rA);X$.prototype.focus=function(){this.isActive&&this.Ey.focus()};X$.prototype.close=function(){this.Ey&&!this.Ey.closed&&this.Ey.close();this.za("close");this.eg()};X$.prototype.isActive=function(){return this.Ey?!this.Ey.closed:!1};X$.prototype.Ta=function(){this.Ey=null;X$.va.Ta.call(this)};z.f=G6a.prototype;z.f.QC=function(a,b,c){var d;d=z.Tq;var e=new z.Wk(z.Oq(d)),e=new z.Yd(e.qm(a));d=v$(e,d);this.dw(d);z.WA(z.HK,{postId:a.id,type:b,source:c,dest:"facebook",dialogType:"native"})};z.f.z6=function(a){var b;b=z.Tq;var c=new z.Wk(z.Oq(b));a=new z.Yd(c.ka(z.Ey,{catalogSlug:a.Je(),username:a.Hf().jk()}));b=v$(a,b);this.dw(b)};z.f.A6=function(a){var b;b=z.Tq;var c=new z.Wk(z.Oq(b));a=new z.Yd(c.ka(z.vy,{sequenceSlug:a.pd()}));b=v$(a,b);this.dw(b)};
z.f.t3=function(){var a=this.la.ka(z.Sya);return this.oa.get(a)};z.f.dw=function(a){F6a(a,"facebook-share",{width:550,height:320})};var J6a=/(?:https?:\/\/|www\.)\w[\w~#-@![\]]*/g;z.q(Z$,z.Uq);
Z$.prototype.open=function(a,b){this.ua=a;this.Lw=b;this.Fa=this.CE.open({bodyHtml:z.kz(E5a,this.Lw),type:"tweet"},!0);a=this.Fa.query(".js-tweetEditor-text");b=this.ra;var c=String,d;d=z.n("Enter tweet text.");d=(0,z.y)(""+d);this.DH=new z.QZ(b,a,c(d),!0);a=new z.JZ(140,!0);a.W9=Y$;this.DH.bb(a);a=I6a(A5a,this.Lw,z.Tq);this.DH.qd(a);this.DH.focus();L6a(this);z.S(this.Fa.lc).ia("remove-textshot",this.Wca.bind(this,!1),this).ia("add-textshot",this.Wca.bind(this,!0),this).ia("toggle-expand-image",this.iAa,
this);this.Fa.subscribe("submit",this.WAa.bind(this))};Z$.prototype.WAa=function(){var a=this.DH.kb();if(M6a(this,a)){var b=this.vN?K6a(this):null;z.w(z.u(this.oa.post(this.la.ka(z.Qya),{tweet:a,textshotInfo:b}),function(a){a=z.mz(C5a,{id:a.value});a=z.kz(G5a,{lIa:a});this.xa.qa(a,{type:"success",cq:1E4})},this),function(a){z.nA(a);this.xa.qa(F5a(),"error")},this);z.IB(z.vBa,{postId:this.ua.id,type:this.Lw.shareType,source:this.Lw.zHa,dest:"twitter",style:this.vN?"textshot":null});this.Fa.close()}};
Z$.prototype.Wca=function(a){this.vN=a;z.vd(this.Fa.query(".js-tweetEditor-imageContainer"),"u-hide",!a);z.vd(this.Fa.query(".js-tweetEditor-addTextshot"),"u-hide",a)};Z$.prototype.iAa=function(){var a=this.Fa.query(".js-tweetEditor-image");z.yd(a,"tweetEditor-image--expanded")};z.f=N6a.prototype;z.f.yHa=function(a,b){var c=z.lu(),d=a.creator||{},e=q5a(b),g=p5a(b),k=H6a(a,z.Tq);(b=R5a(b.v3()))&&z.ie(k,b||"");var l={name:d.name||"",username:d.username||"",twitterScreenName:d.twitterScreenName||"",url:k.toString(),content:a.title,user:c,bIa:e,aIa:g,shareType:"highlight",zHa:"highlight_menu"};z.w(z.u(this.ra.load("tweet-dialog"),function(b){b.open(a,l)}),z.nA);z.IB(z.HK,{postId:a.id,type:"highlight",source:"highlight_menu",dest:"twitter",dialogType:"inapp"});return!0};
z.f.QC=function(a,b,c,d,e){var g=z.lu().userId,k="highlight"==c?A5a:z.hta,l=z.Tq,p=a.creator||{};b={content:b,name:p.name||"",username:p.username||"",twitterScreenName:p.twitterScreenName||"",Bea:p.userId==g,url:H6a(a,l).toString(),collaborators:d||[]};d=d&&d.length?String(k(b,null,l)):I6a(k,b,l);k=new z.Yd("https://twitter.com/intent/tweet");z.se(k,"text",d);this.dw(k);z.WA(z.HK,{postId:a.id,type:c,source:e,dest:"twitter",dialogType:"native"})};
z.f.z6=function(a){var b=z.Tq,c=new z.Wk(z.Oq(b)),c=(new z.Yd(c.ka(z.Ey,{catalogSlug:a.Je(),username:a.Hf().jk()}))).toString();a=z.B(""+z.Wn(String(a.name))+((null==a.creator?null:a.creator.userId)!=b.currentUser.userId?" — "+z.VH({twitterScreenName:null==a.creator?null:a.creator.twitterScreenName,name:null==a.creator?null:a.creator.name}):"")+" "+(""+c));b=new z.Yd("https://twitter.com/intent/tweet");z.se(b,"text",a);this.dw(b)};
z.f.A6=function(a){var b=new z.Wk(z.Oq(z.Tq)),b=(new z.Yd(b.ka(z.vy,{sequenceSlug:a.pd()}))).toString();a=z.B(""+z.Wn(String(a.title))+" "+(""+b));b=new z.Yd("https://twitter.com/intent/tweet");z.se(b,"text",a);this.dw(b)};z.f.dw=function(a){F6a(a,"twitter-share",{width:670,height:420})};z.m($$,z.RZ);$$.prototype.ma=function(){z.RZ.prototype.ma.call(this);z.Bk(z.Tq).enable_post_welcome_modal?O6a(this):z.Bk(z.Tq).enable_post_welcome_content_first&&P6a(this);z.S(this.na()).ia("homepage-link-clicked",this.Hra,this)};$$.prototype.toggle=function(){this.cm&&z.WA(z.hDa,{postId:this.jb});z.RZ.prototype.toggle.call(this)};$$.prototype.Hra=function(){z.WA(z.gDa,{postId:this.jb});this.Ja.navigate(this.la.ka(z.Qx))};var Q6a=z.qB,R6a=Q6a.Ca();z.tB(R6a.scope("screen").add("quotes",V5a).add("quote-responses",E6a).add("responses-stream-control",W$).add("notes-data",D$),"WelcomeDrawer",$$);z.tB(R6a.scope("app"),"PlacementsControl",H$).add("twitter",N6a).add("facebook",G6a).add("tweet-dialog",Z$);z.QP(Q6a,"notes");}).call(this, _mdm);
