version: '2'
services:
    testmanager-app:
        image: testmanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testmanager-mysql:3306/testmanager?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=testmanager-elasticsearch:9300
        ports:
            - 8080:8080
    testmanager-mysql:
        extends:
            file: mysql.yml
            service: testmanager-mysql
    testmanager-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: testmanager-elasticsearch
