//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class suite
    {
        public suite()
        {
            this.tests = new HashSet<test>();
        }

        //public string Id { get; set; }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int SuiteId { get; set; }
        public string SuiteName { get; set; }
        public string xmlFileLocation { get; set; }
        public string jenkinsURL { get; set; }
        
        public virtual ICollection<test> tests { get; set; }
    }
}
