//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AutomationModel", "FK_BRAND_LANGUAGE_BRAND", "BRAND", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication1.BRAND), "BRAND_LANGUAGE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication1.BRAND_LANGUAGE), true)]
[assembly: EdmRelationshipAttribute("AutomationModel", "FK_BrandsResult_BRAND1", "BRAND", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication1.BRAND), "BrandsResult", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication1.BrandsResult), true)]
[assembly: EdmRelationshipAttribute("AutomationModel", "FK_Tool_BRAND_LANGUAGE", "BRAND_LANGUAGE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication1.BRAND_LANGUAGE), "Tool", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication1.Tool), true)]
[assembly: EdmRelationshipAttribute("AutomationModel", "FK_TOOL_RESULT_Tool", "Tool", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WpfApplication1.Tool), "TOOL_RESULT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfApplication1.TOOL_RESULT), true)]

#endregion

namespace WpfApplication1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AutomationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AutomationEntities object using the connection string found in the 'AutomationEntities' section of the application configuration file.
        /// </summary>
        public AutomationEntities() : base("name=AutomationEntities", "AutomationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AutomationEntities object.
        /// </summary>
        public AutomationEntities(string connectionString) : base(connectionString, "AutomationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AutomationEntities object.
        /// </summary>
        public AutomationEntities(EntityConnection connection) : base(connection, "AutomationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BRAND> BRAND
        {
            get
            {
                if ((_BRAND == null))
                {
                    _BRAND = base.CreateObjectSet<BRAND>("BRAND");
                }
                return _BRAND;
            }
        }
        private ObjectSet<BRAND> _BRAND;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BRAND_LANGUAGE> BRAND_LANGUAGE
        {
            get
            {
                if ((_BRAND_LANGUAGE == null))
                {
                    _BRAND_LANGUAGE = base.CreateObjectSet<BRAND_LANGUAGE>("BRAND_LANGUAGE");
                }
                return _BRAND_LANGUAGE;
            }
        }
        private ObjectSet<BRAND_LANGUAGE> _BRAND_LANGUAGE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BrandsResult> BrandsResult
        {
            get
            {
                if ((_BrandsResult == null))
                {
                    _BrandsResult = base.CreateObjectSet<BrandsResult>("BrandsResult");
                }
                return _BrandsResult;
            }
        }
        private ObjectSet<BrandsResult> _BrandsResult;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tool> Tool
        {
            get
            {
                if ((_Tool == null))
                {
                    _Tool = base.CreateObjectSet<Tool>("Tool");
                }
                return _Tool;
            }
        }
        private ObjectSet<Tool> _Tool;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TOOL_RESULT> TOOL_RESULT
        {
            get
            {
                if ((_TOOL_RESULT == null))
                {
                    _TOOL_RESULT = base.CreateObjectSet<TOOL_RESULT>("TOOL_RESULT");
                }
                return _TOOL_RESULT;
            }
        }
        private ObjectSet<TOOL_RESULT> _TOOL_RESULT;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BRAND EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBRAND(BRAND bRAND)
        {
            base.AddObject("BRAND", bRAND);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BRAND_LANGUAGE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBRAND_LANGUAGE(BRAND_LANGUAGE bRAND_LANGUAGE)
        {
            base.AddObject("BRAND_LANGUAGE", bRAND_LANGUAGE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BrandsResult EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBrandsResult(BrandsResult brandsResult)
        {
            base.AddObject("BrandsResult", brandsResult);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tool EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTool(Tool tool)
        {
            base.AddObject("Tool", tool);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TOOL_RESULT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTOOL_RESULT(TOOL_RESULT tOOL_RESULT)
        {
            base.AddObject("TOOL_RESULT", tOOL_RESULT);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AutomationModel", Name="BRAND")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BRAND : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BRAND object.
        /// </summary>
        /// <param name="brand_ID">Initial value of the Brand_ID property.</param>
        public static BRAND CreateBRAND(global::System.Decimal brand_ID)
        {
            BRAND bRAND = new BRAND();
            bRAND.Brand_ID = brand_ID;
            return bRAND;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Brand_ID
        {
            get
            {
                return _Brand_ID;
            }
            set
            {
                if (_Brand_ID != value)
                {
                    OnBrand_IDChanging(value);
                    ReportPropertyChanging("Brand_ID");
                    _Brand_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Brand_ID");
                    OnBrand_IDChanged();
                }
            }
        }
        private global::System.Decimal _Brand_ID;
        partial void OnBrand_IDChanging(global::System.Decimal value);
        partial void OnBrand_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Brand_Name
        {
            get
            {
                return _Brand_Name;
            }
            set
            {
                OnBrand_NameChanging(value);
                ReportPropertyChanging("Brand_Name");
                _Brand_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Brand_Name");
                OnBrand_NameChanged();
            }
        }
        private global::System.String _Brand_Name;
        partial void OnBrand_NameChanging(global::System.String value);
        partial void OnBrand_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Brand_Symbol
        {
            get
            {
                return _Brand_Symbol;
            }
            set
            {
                OnBrand_SymbolChanging(value);
                ReportPropertyChanging("Brand_Symbol");
                _Brand_Symbol = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Brand_Symbol");
                OnBrand_SymbolChanged();
            }
        }
        private global::System.String _Brand_Symbol;
        partial void OnBrand_SymbolChanging(global::System.String value);
        partial void OnBrand_SymbolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Brand_Main_URL
        {
            get
            {
                return _Brand_Main_URL;
            }
            set
            {
                OnBrand_Main_URLChanging(value);
                ReportPropertyChanging("Brand_Main_URL");
                _Brand_Main_URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Brand_Main_URL");
                OnBrand_Main_URLChanged();
            }
        }
        private global::System.String _Brand_Main_URL;
        partial void OnBrand_Main_URLChanging(global::System.String value);
        partial void OnBrand_Main_URLChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AutomationModel", "FK_BRAND_LANGUAGE_BRAND", "BRAND_LANGUAGE")]
        public EntityCollection<BRAND_LANGUAGE> BRAND_LANGUAGE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BRAND_LANGUAGE>("AutomationModel.FK_BRAND_LANGUAGE_BRAND", "BRAND_LANGUAGE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BRAND_LANGUAGE>("AutomationModel.FK_BRAND_LANGUAGE_BRAND", "BRAND_LANGUAGE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AutomationModel", "FK_BrandsResult_BRAND1", "BrandsResult")]
        public EntityCollection<BrandsResult> BrandsResult
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BrandsResult>("AutomationModel.FK_BrandsResult_BRAND1", "BrandsResult");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BrandsResult>("AutomationModel.FK_BrandsResult_BRAND1", "BrandsResult", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AutomationModel", Name="BRAND_LANGUAGE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BRAND_LANGUAGE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BRAND_LANGUAGE object.
        /// </summary>
        /// <param name="brand_Language_ID">Initial value of the Brand_Language_ID property.</param>
        /// <param name="brand_ID">Initial value of the Brand_ID property.</param>
        /// <param name="currency_ID">Initial value of the Currency_ID property.</param>
        /// <param name="language_ID">Initial value of the Language_ID property.</param>
        public static BRAND_LANGUAGE CreateBRAND_LANGUAGE(global::System.Decimal brand_Language_ID, global::System.Decimal brand_ID, global::System.Decimal currency_ID, global::System.Decimal language_ID)
        {
            BRAND_LANGUAGE bRAND_LANGUAGE = new BRAND_LANGUAGE();
            bRAND_LANGUAGE.Brand_Language_ID = brand_Language_ID;
            bRAND_LANGUAGE.Brand_ID = brand_ID;
            bRAND_LANGUAGE.Currency_ID = currency_ID;
            bRAND_LANGUAGE.Language_ID = language_ID;
            return bRAND_LANGUAGE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Brand_Language_ID
        {
            get
            {
                return _Brand_Language_ID;
            }
            set
            {
                if (_Brand_Language_ID != value)
                {
                    OnBrand_Language_IDChanging(value);
                    ReportPropertyChanging("Brand_Language_ID");
                    _Brand_Language_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Brand_Language_ID");
                    OnBrand_Language_IDChanged();
                }
            }
        }
        private global::System.Decimal _Brand_Language_ID;
        partial void OnBrand_Language_IDChanging(global::System.Decimal value);
        partial void OnBrand_Language_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Brand_ID
        {
            get
            {
                return _Brand_ID;
            }
            set
            {
                OnBrand_IDChanging(value);
                ReportPropertyChanging("Brand_ID");
                _Brand_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Brand_ID");
                OnBrand_IDChanged();
            }
        }
        private global::System.Decimal _Brand_ID;
        partial void OnBrand_IDChanging(global::System.Decimal value);
        partial void OnBrand_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Currency_ID
        {
            get
            {
                return _Currency_ID;
            }
            set
            {
                OnCurrency_IDChanging(value);
                ReportPropertyChanging("Currency_ID");
                _Currency_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Currency_ID");
                OnCurrency_IDChanged();
            }
        }
        private global::System.Decimal _Currency_ID;
        partial void OnCurrency_IDChanging(global::System.Decimal value);
        partial void OnCurrency_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Language_ID
        {
            get
            {
                return _Language_ID;
            }
            set
            {
                OnLanguage_IDChanging(value);
                ReportPropertyChanging("Language_ID");
                _Language_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Language_ID");
                OnLanguage_IDChanged();
            }
        }
        private global::System.Decimal _Language_ID;
        partial void OnLanguage_IDChanging(global::System.Decimal value);
        partial void OnLanguage_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Notification_ID
        {
            get
            {
                return _Notification_ID;
            }
            set
            {
                OnNotification_IDChanging(value);
                ReportPropertyChanging("Notification_ID");
                _Notification_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Notification_ID");
                OnNotification_IDChanged();
            }
        }
        private Nullable<global::System.Decimal> _Notification_ID;
        partial void OnNotification_IDChanging(Nullable<global::System.Decimal> value);
        partial void OnNotification_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Brand_Language_URL_Template
        {
            get
            {
                return _Brand_Language_URL_Template;
            }
            set
            {
                OnBrand_Language_URL_TemplateChanging(value);
                ReportPropertyChanging("Brand_Language_URL_Template");
                _Brand_Language_URL_Template = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Brand_Language_URL_Template");
                OnBrand_Language_URL_TemplateChanged();
            }
        }
        private global::System.String _Brand_Language_URL_Template;
        partial void OnBrand_Language_URL_TemplateChanging(global::System.String value);
        partial void OnBrand_Language_URL_TemplateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Brand_Language_Priority
        {
            get
            {
                return _Brand_Language_Priority;
            }
            set
            {
                OnBrand_Language_PriorityChanging(value);
                ReportPropertyChanging("Brand_Language_Priority");
                _Brand_Language_Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Brand_Language_Priority");
                OnBrand_Language_PriorityChanged();
            }
        }
        private Nullable<global::System.Int32> _Brand_Language_Priority;
        partial void OnBrand_Language_PriorityChanging(Nullable<global::System.Int32> value);
        partial void OnBrand_Language_PriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Group_Number
        {
            get
            {
                return _Group_Number;
            }
            set
            {
                OnGroup_NumberChanging(value);
                ReportPropertyChanging("Group_Number");
                _Group_Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Group_Number");
                OnGroup_NumberChanged();
            }
        }
        private Nullable<global::System.Decimal> _Group_Number;
        partial void OnGroup_NumberChanging(Nullable<global::System.Decimal> value);
        partial void OnGroup_NumberChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AutomationModel", "FK_BRAND_LANGUAGE_BRAND", "BRAND")]
        public BRAND BRAND
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRAND>("AutomationModel.FK_BRAND_LANGUAGE_BRAND", "BRAND").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRAND>("AutomationModel.FK_BRAND_LANGUAGE_BRAND", "BRAND").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BRAND> BRANDReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRAND>("AutomationModel.FK_BRAND_LANGUAGE_BRAND", "BRAND");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BRAND>("AutomationModel.FK_BRAND_LANGUAGE_BRAND", "BRAND", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AutomationModel", "FK_Tool_BRAND_LANGUAGE", "Tool")]
        public EntityCollection<Tool> Tool
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tool>("AutomationModel.FK_Tool_BRAND_LANGUAGE", "Tool");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tool>("AutomationModel.FK_Tool_BRAND_LANGUAGE", "Tool", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AutomationModel", Name="BrandsResult")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BrandsResult : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BrandsResult object.
        /// </summary>
        /// <param name="brand_Result_ID">Initial value of the Brand_Result_ID property.</param>
        /// <param name="brand_ID">Initial value of the Brand_ID property.</param>
        /// <param name="tool_Name">Initial value of the Tool_Name property.</param>
        public static BrandsResult CreateBrandsResult(global::System.Decimal brand_Result_ID, global::System.Decimal brand_ID, global::System.String tool_Name)
        {
            BrandsResult brandsResult = new BrandsResult();
            brandsResult.Brand_Result_ID = brand_Result_ID;
            brandsResult.Brand_ID = brand_ID;
            brandsResult.Tool_Name = tool_Name;
            return brandsResult;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Brand_Result_ID
        {
            get
            {
                return _Brand_Result_ID;
            }
            set
            {
                if (_Brand_Result_ID != value)
                {
                    OnBrand_Result_IDChanging(value);
                    ReportPropertyChanging("Brand_Result_ID");
                    _Brand_Result_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Brand_Result_ID");
                    OnBrand_Result_IDChanged();
                }
            }
        }
        private global::System.Decimal _Brand_Result_ID;
        partial void OnBrand_Result_IDChanging(global::System.Decimal value);
        partial void OnBrand_Result_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Brand_ID
        {
            get
            {
                return _Brand_ID;
            }
            set
            {
                OnBrand_IDChanging(value);
                ReportPropertyChanging("Brand_ID");
                _Brand_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Brand_ID");
                OnBrand_IDChanged();
            }
        }
        private global::System.Decimal _Brand_ID;
        partial void OnBrand_IDChanging(global::System.Decimal value);
        partial void OnBrand_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tool_Name
        {
            get
            {
                return _Tool_Name;
            }
            set
            {
                OnTool_NameChanging(value);
                ReportPropertyChanging("Tool_Name");
                _Tool_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tool_Name");
                OnTool_NameChanged();
            }
        }
        private global::System.String _Tool_Name;
        partial void OnTool_NameChanging(global::System.String value);
        partial void OnTool_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Tool_Result
        {
            get
            {
                return _Tool_Result;
            }
            set
            {
                OnTool_ResultChanging(value);
                ReportPropertyChanging("Tool_Result");
                _Tool_Result = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tool_Result");
                OnTool_ResultChanged();
            }
        }
        private Nullable<global::System.Boolean> _Tool_Result;
        partial void OnTool_ResultChanging(Nullable<global::System.Boolean> value);
        partial void OnTool_ResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Tool_last_Run_Date
        {
            get
            {
                return _Tool_last_Run_Date;
            }
            set
            {
                OnTool_last_Run_DateChanging(value);
                ReportPropertyChanging("Tool_last_Run_Date");
                _Tool_last_Run_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tool_last_Run_Date");
                OnTool_last_Run_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Tool_last_Run_Date;
        partial void OnTool_last_Run_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnTool_last_Run_DateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AutomationModel", "FK_BrandsResult_BRAND1", "BRAND")]
        public BRAND BRAND
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRAND>("AutomationModel.FK_BrandsResult_BRAND1", "BRAND").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRAND>("AutomationModel.FK_BrandsResult_BRAND1", "BRAND").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BRAND> BRANDReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRAND>("AutomationModel.FK_BrandsResult_BRAND1", "BRAND");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BRAND>("AutomationModel.FK_BrandsResult_BRAND1", "BRAND", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AutomationModel", Name="Tool")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tool : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tool object.
        /// </summary>
        /// <param name="tool_ID">Initial value of the Tool_ID property.</param>
        /// <param name="brand_Language_ID">Initial value of the Brand_Language_ID property.</param>
        public static Tool CreateTool(global::System.Decimal tool_ID, global::System.Decimal brand_Language_ID)
        {
            Tool tool = new Tool();
            tool.Tool_ID = tool_ID;
            tool.Brand_Language_ID = brand_Language_ID;
            return tool;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Tool_ID
        {
            get
            {
                return _Tool_ID;
            }
            set
            {
                if (_Tool_ID != value)
                {
                    OnTool_IDChanging(value);
                    ReportPropertyChanging("Tool_ID");
                    _Tool_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Tool_ID");
                    OnTool_IDChanged();
                }
            }
        }
        private global::System.Decimal _Tool_ID;
        partial void OnTool_IDChanging(global::System.Decimal value);
        partial void OnTool_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Brand_Language_ID
        {
            get
            {
                return _Brand_Language_ID;
            }
            set
            {
                OnBrand_Language_IDChanging(value);
                ReportPropertyChanging("Brand_Language_ID");
                _Brand_Language_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Brand_Language_ID");
                OnBrand_Language_IDChanged();
            }
        }
        private global::System.Decimal _Brand_Language_ID;
        partial void OnBrand_Language_IDChanging(global::System.Decimal value);
        partial void OnBrand_Language_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tool_Name
        {
            get
            {
                return _Tool_Name;
            }
            set
            {
                OnTool_NameChanging(value);
                ReportPropertyChanging("Tool_Name");
                _Tool_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tool_Name");
                OnTool_NameChanged();
            }
        }
        private global::System.String _Tool_Name;
        partial void OnTool_NameChanging(global::System.String value);
        partial void OnTool_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tool_Type
        {
            get
            {
                return _Tool_Type;
            }
            set
            {
                OnTool_TypeChanging(value);
                ReportPropertyChanging("Tool_Type");
                _Tool_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tool_Type");
                OnTool_TypeChanged();
            }
        }
        private global::System.String _Tool_Type;
        partial void OnTool_TypeChanging(global::System.String value);
        partial void OnTool_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tool_Description
        {
            get
            {
                return _Tool_Description;
            }
            set
            {
                OnTool_DescriptionChanging(value);
                ReportPropertyChanging("Tool_Description");
                _Tool_Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tool_Description");
                OnTool_DescriptionChanged();
            }
        }
        private global::System.String _Tool_Description;
        partial void OnTool_DescriptionChanging(global::System.String value);
        partial void OnTool_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tool_SMS_Message_Format
        {
            get
            {
                return _Tool_SMS_Message_Format;
            }
            set
            {
                OnTool_SMS_Message_FormatChanging(value);
                ReportPropertyChanging("Tool_SMS_Message_Format");
                _Tool_SMS_Message_Format = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tool_SMS_Message_Format");
                OnTool_SMS_Message_FormatChanged();
            }
        }
        private global::System.String _Tool_SMS_Message_Format;
        partial void OnTool_SMS_Message_FormatChanging(global::System.String value);
        partial void OnTool_SMS_Message_FormatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tool_Email_Message_Format
        {
            get
            {
                return _Tool_Email_Message_Format;
            }
            set
            {
                OnTool_Email_Message_FormatChanging(value);
                ReportPropertyChanging("Tool_Email_Message_Format");
                _Tool_Email_Message_Format = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tool_Email_Message_Format");
                OnTool_Email_Message_FormatChanged();
            }
        }
        private global::System.String _Tool_Email_Message_Format;
        partial void OnTool_Email_Message_FormatChanging(global::System.String value);
        partial void OnTool_Email_Message_FormatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tool_Argument
        {
            get
            {
                return _Tool_Argument;
            }
            set
            {
                OnTool_ArgumentChanging(value);
                ReportPropertyChanging("Tool_Argument");
                _Tool_Argument = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tool_Argument");
                OnTool_ArgumentChanged();
            }
        }
        private global::System.String _Tool_Argument;
        partial void OnTool_ArgumentChanging(global::System.String value);
        partial void OnTool_ArgumentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tool_FilePath
        {
            get
            {
                return _Tool_FilePath;
            }
            set
            {
                OnTool_FilePathChanging(value);
                ReportPropertyChanging("Tool_FilePath");
                _Tool_FilePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tool_FilePath");
                OnTool_FilePathChanged();
            }
        }
        private global::System.String _Tool_FilePath;
        partial void OnTool_FilePathChanging(global::System.String value);
        partial void OnTool_FilePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tool_IPAddress
        {
            get
            {
                return _Tool_IPAddress;
            }
            set
            {
                OnTool_IPAddressChanging(value);
                ReportPropertyChanging("Tool_IPAddress");
                _Tool_IPAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tool_IPAddress");
                OnTool_IPAddressChanged();
            }
        }
        private global::System.String _Tool_IPAddress;
        partial void OnTool_IPAddressChanging(global::System.String value);
        partial void OnTool_IPAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Group_Number
        {
            get
            {
                return _Group_Number;
            }
            set
            {
                OnGroup_NumberChanging(value);
                ReportPropertyChanging("Group_Number");
                _Group_Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Group_Number");
                OnGroup_NumberChanged();
            }
        }
        private Nullable<global::System.Decimal> _Group_Number;
        partial void OnGroup_NumberChanging(Nullable<global::System.Decimal> value);
        partial void OnGroup_NumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Tool_TimeOut
        {
            get
            {
                return _Tool_TimeOut;
            }
            set
            {
                OnTool_TimeOutChanging(value);
                ReportPropertyChanging("Tool_TimeOut");
                _Tool_TimeOut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tool_TimeOut");
                OnTool_TimeOutChanged();
            }
        }
        private Nullable<global::System.Decimal> _Tool_TimeOut;
        partial void OnTool_TimeOutChanging(Nullable<global::System.Decimal> value);
        partial void OnTool_TimeOutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Tool_Run_Order
        {
            get
            {
                return _Tool_Run_Order;
            }
            set
            {
                OnTool_Run_OrderChanging(value);
                ReportPropertyChanging("Tool_Run_Order");
                _Tool_Run_Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tool_Run_Order");
                OnTool_Run_OrderChanged();
            }
        }
        private Nullable<global::System.Decimal> _Tool_Run_Order;
        partial void OnTool_Run_OrderChanging(Nullable<global::System.Decimal> value);
        partial void OnTool_Run_OrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Tool_Start_Time
        {
            get
            {
                return _Tool_Start_Time;
            }
            set
            {
                OnTool_Start_TimeChanging(value);
                ReportPropertyChanging("Tool_Start_Time");
                _Tool_Start_Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tool_Start_Time");
                OnTool_Start_TimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Tool_Start_Time;
        partial void OnTool_Start_TimeChanging(Nullable<global::System.DateTime> value);
        partial void OnTool_Start_TimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> EstimateRunTimeMin
        {
            get
            {
                return _EstimateRunTimeMin;
            }
            set
            {
                OnEstimateRunTimeMinChanging(value);
                ReportPropertyChanging("EstimateRunTimeMin");
                _EstimateRunTimeMin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EstimateRunTimeMin");
                OnEstimateRunTimeMinChanged();
            }
        }
        private Nullable<global::System.Decimal> _EstimateRunTimeMin;
        partial void OnEstimateRunTimeMinChanging(Nullable<global::System.Decimal> value);
        partial void OnEstimateRunTimeMinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RunFreqMinutes
        {
            get
            {
                return _RunFreqMinutes;
            }
            set
            {
                OnRunFreqMinutesChanging(value);
                ReportPropertyChanging("RunFreqMinutes");
                _RunFreqMinutes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RunFreqMinutes");
                OnRunFreqMinutesChanged();
            }
        }
        private Nullable<global::System.Decimal> _RunFreqMinutes;
        partial void OnRunFreqMinutesChanging(Nullable<global::System.Decimal> value);
        partial void OnRunFreqMinutesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ParallelEnable
        {
            get
            {
                return _ParallelEnable;
            }
            set
            {
                OnParallelEnableChanging(value);
                ReportPropertyChanging("ParallelEnable");
                _ParallelEnable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParallelEnable");
                OnParallelEnableChanged();
            }
        }
        private Nullable<global::System.Boolean> _ParallelEnable;
        partial void OnParallelEnableChanging(Nullable<global::System.Boolean> value);
        partial void OnParallelEnableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSkip
        {
            get
            {
                return _IsSkip;
            }
            set
            {
                OnIsSkipChanging(value);
                ReportPropertyChanging("IsSkip");
                _IsSkip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSkip");
                OnIsSkipChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSkip;
        partial void OnIsSkipChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSkipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsRunning
        {
            get
            {
                return _IsRunning;
            }
            set
            {
                OnIsRunningChanging(value);
                ReportPropertyChanging("IsRunning");
                _IsRunning = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRunning");
                OnIsRunningChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsRunning;
        partial void OnIsRunningChanging(Nullable<global::System.Boolean> value);
        partial void OnIsRunningChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Running
        {
            get
            {
                return _Running;
            }
            set
            {
                OnRunningChanging(value);
                ReportPropertyChanging("Running");
                _Running = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Running");
                OnRunningChanged();
            }
        }
        private Nullable<global::System.Boolean> _Running;
        partial void OnRunningChanging(Nullable<global::System.Boolean> value);
        partial void OnRunningChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AutomationModel", "FK_Tool_BRAND_LANGUAGE", "BRAND_LANGUAGE")]
        public BRAND_LANGUAGE BRAND_LANGUAGE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRAND_LANGUAGE>("AutomationModel.FK_Tool_BRAND_LANGUAGE", "BRAND_LANGUAGE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRAND_LANGUAGE>("AutomationModel.FK_Tool_BRAND_LANGUAGE", "BRAND_LANGUAGE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BRAND_LANGUAGE> BRAND_LANGUAGEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRAND_LANGUAGE>("AutomationModel.FK_Tool_BRAND_LANGUAGE", "BRAND_LANGUAGE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BRAND_LANGUAGE>("AutomationModel.FK_Tool_BRAND_LANGUAGE", "BRAND_LANGUAGE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AutomationModel", "FK_TOOL_RESULT_Tool", "TOOL_RESULT")]
        public EntityCollection<TOOL_RESULT> TOOL_RESULT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TOOL_RESULT>("AutomationModel.FK_TOOL_RESULT_Tool", "TOOL_RESULT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TOOL_RESULT>("AutomationModel.FK_TOOL_RESULT_Tool", "TOOL_RESULT", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AutomationModel", Name="TOOL_RESULT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TOOL_RESULT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TOOL_RESULT object.
        /// </summary>
        /// <param name="tool_Result_ID">Initial value of the Tool_Result_ID property.</param>
        /// <param name="tool_ID">Initial value of the Tool_ID property.</param>
        /// <param name="id_temp">Initial value of the id_temp property.</param>
        public static TOOL_RESULT CreateTOOL_RESULT(global::System.Decimal tool_Result_ID, global::System.Decimal tool_ID, global::System.Int32 id_temp)
        {
            TOOL_RESULT tOOL_RESULT = new TOOL_RESULT();
            tOOL_RESULT.Tool_Result_ID = tool_Result_ID;
            tOOL_RESULT.Tool_ID = tool_ID;
            tOOL_RESULT.id_temp = id_temp;
            return tOOL_RESULT;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Tool_Result_ID
        {
            get
            {
                return _Tool_Result_ID;
            }
            set
            {
                if (_Tool_Result_ID != value)
                {
                    OnTool_Result_IDChanging(value);
                    ReportPropertyChanging("Tool_Result_ID");
                    _Tool_Result_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Tool_Result_ID");
                    OnTool_Result_IDChanged();
                }
            }
        }
        private global::System.Decimal _Tool_Result_ID;
        partial void OnTool_Result_IDChanging(global::System.Decimal value);
        partial void OnTool_Result_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Tool_ID
        {
            get
            {
                return _Tool_ID;
            }
            set
            {
                OnTool_IDChanging(value);
                ReportPropertyChanging("Tool_ID");
                _Tool_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tool_ID");
                OnTool_IDChanged();
            }
        }
        private global::System.Decimal _Tool_ID;
        partial void OnTool_IDChanging(global::System.Decimal value);
        partial void OnTool_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Tool_Result_Result
        {
            get
            {
                return _Tool_Result_Result;
            }
            set
            {
                OnTool_Result_ResultChanging(value);
                ReportPropertyChanging("Tool_Result_Result");
                _Tool_Result_Result = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tool_Result_Result");
                OnTool_Result_ResultChanged();
            }
        }
        private Nullable<global::System.Boolean> _Tool_Result_Result;
        partial void OnTool_Result_ResultChanging(Nullable<global::System.Boolean> value);
        partial void OnTool_Result_ResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tool_Result_Description
        {
            get
            {
                return _Tool_Result_Description;
            }
            set
            {
                OnTool_Result_DescriptionChanging(value);
                ReportPropertyChanging("Tool_Result_Description");
                _Tool_Result_Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tool_Result_Description");
                OnTool_Result_DescriptionChanged();
            }
        }
        private global::System.String _Tool_Result_Description;
        partial void OnTool_Result_DescriptionChanging(global::System.String value);
        partial void OnTool_Result_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Tool_Result_Last_Pass_Date
        {
            get
            {
                return _Tool_Result_Last_Pass_Date;
            }
            set
            {
                OnTool_Result_Last_Pass_DateChanging(value);
                ReportPropertyChanging("Tool_Result_Last_Pass_Date");
                _Tool_Result_Last_Pass_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tool_Result_Last_Pass_Date");
                OnTool_Result_Last_Pass_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Tool_Result_Last_Pass_Date;
        partial void OnTool_Result_Last_Pass_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnTool_Result_Last_Pass_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_temp
        {
            get
            {
                return _id_temp;
            }
            set
            {
                Onid_tempChanging(value);
                ReportPropertyChanging("id_temp");
                _id_temp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_temp");
                Onid_tempChanged();
            }
        }
        private global::System.Int32 _id_temp;
        partial void Onid_tempChanging(global::System.Int32 value);
        partial void Onid_tempChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Tool_Result_Last_Run_Date
        {
            get
            {
                return _Tool_Result_Last_Run_Date;
            }
            set
            {
                OnTool_Result_Last_Run_DateChanging(value);
                ReportPropertyChanging("Tool_Result_Last_Run_Date");
                _Tool_Result_Last_Run_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tool_Result_Last_Run_Date");
                OnTool_Result_Last_Run_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Tool_Result_Last_Run_Date;
        partial void OnTool_Result_Last_Run_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnTool_Result_Last_Run_DateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AutomationModel", "FK_TOOL_RESULT_Tool", "Tool")]
        public Tool Tool
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tool>("AutomationModel.FK_TOOL_RESULT_Tool", "Tool").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tool>("AutomationModel.FK_TOOL_RESULT_Tool", "Tool").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tool> ToolReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tool>("AutomationModel.FK_TOOL_RESULT_Tool", "Tool");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tool>("AutomationModel.FK_TOOL_RESULT_Tool", "Tool", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
