//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suite
    {
        public suite()
        {
            this.tests = new HashSet<test>();
        }
    
        public int SuitesId { get; set; }
        public string SuiteName { get; set; }
        public string xmlFileLocation { get; set; }
        public string jenkinsURL { get; set; }
    
        public virtual ICollection<test> tests { get; set; }
    }
}
