//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int TestsId { get; set; }
        public Nullable<int> SuitesId { get; set; }
        public string TestName { get; set; }
        public string classesName { get; set; }
        public string parametersName { get; set; }
        public string parametersValue { get; set; }
    
        public virtual suite suite { get; set; }
    }
}
