// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace BrowserTargeting
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Threading;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class UIMap
    {
        /// <summary>
        /// BT_Test - Use 'BT_TestParams' to pass parameters into this method.
        /// </summary>
        public string Res;

        public void BT_Test()
        {
            #region Variable Declarations

            WinButton uIToolsButton = this.UIBlankPageWindowsInteWindow.UICommandBarToolBar.UIToolsButton;
            WinMenuItem uIInternetOptionsMenuItem = this.UIItemWindow.UIContextMenu.UIInternetOptionsMenuItem;
            WinButton uIDeleteButton = this.UIInternetOptionsWindow.UIDeleteWindow.UIDeleteButton;
            WinButton uIDeleteButton1 = this.UIDeleteBrowsingHistorWindow.UIDeleteWindow.UIDeleteButton;
            WinButton uIOKButton = this.UIInternetOptionsWindow.UIOKWindow.UIOKButton;
            BrowserWindow uIBlankPageWindowsInteWindow = this.UIBlankPageWindowsInteWindow;
            WinEdit uIAddressEdit = this.UIBlankPageWindowsInteWindow.UIItemWindow.UIAddressEdit;
            WinMenuItem uICopyMenuItem = this.UIItemWindow.UIContextMenu.UICopyMenuItem;
            WinButton uICloseButton = this.UIBlankPageWindowsInteWindow.UIDasköniglichsteonlinTitleBar.UICloseButton;

            #endregion Variable Declarations

            // Go to web page 'about:blank' using new browser instance
            this.UIBlankPageWindowsInteWindow.LaunchUrl(new System.Uri(this.BT_TestParams.UIBlankPageWindowsInteWindowUrl));

            // Click 'Tools' button
            Mouse.Click(uIToolsButton, new Point(45, 19));

            // Click 'Internet Options' menu item
            Mouse.Click(uIInternetOptionsMenuItem, new Point(99, 12));

            // Click '&Delete...' button
            Mouse.Click(uIDeleteButton, new Point(42, 25));

            // Click '&Delete' button
            Mouse.Click(uIDeleteButton1, new Point(54, 14));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(50, 20));

            // Go to web page 'http://www.skykingscasino.com/'
            uIBlankPageWindowsInteWindow.NavigateToUrl(new System.Uri(this.BT_TestParams.UIBlankPageWindowsInteWindowUrl1));

            // Right-Click 'Address' text box
            Mouse.Click(uIAddressEdit, MouseButtons.Right, ModifierKeys.None, new Point(329, 9));

            // Click 'Copy' menu item
            Mouse.Click(uICopyMenuItem, new Point(65, 15));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(22, 16));
        }

        /// <summary>
        /// CopyAddress - Use 'CopyAddressParams' to pass parameters into this method.
        /// </summary>
        public void CopyAddress()
        {
            #region Variable Declarations

            WinEdit uIAddressEdit = this.UIПолучитеБесплатныйБоWindow.UIItemWindow.UIAddressEdit;

            #endregion Variable Declarations

            // Click 'Address' text box
            Mouse.Click(uIAddressEdit, new Point(178, 15));

            // Type 'Control + C' in 'Address' text box
            Keyboard.SendKeys(uIAddressEdit, this.CopyAddressParams.UIAddressEditSendKeys, ModifierKeys.Control);
        }

        /// <summary>
        /// ViewSorce - Use 'ViewSorceParams' to pass parameters into this method.
        /// </summary>
        public void ViewSorce()
        {
            #region Variable Declarations

            WinButton uIPageButton = this.UIFreeonlinecasinogameWindow.UICommandBarToolBar.UIPageButton;
            WinMenuItem uIViewSourceMenuItem = this.UIItemWindow.UIContextMenu.UIViewSourceMenuItem;
            HtmlSpan uITextjavascriptPane = this.UIHttpwwwjoylandcasinoWindow.UIItemClient.UIAboutblankDocument.UISyn_row7Pane.UITextjavascriptPane;
            HtmlDocument uIAboutblankDocument = this.UIHttpwwwjoylandcasinoWindow.UIItemClient.UIAboutblankDocument;
            WinButton uICloseButton = this.UIHttpwwwjoylandcasinoWindow.UIHttpwwwjoylandcasinoTitleBar.UICloseButton;

            #endregion Variable Declarations

            // Click 'Page' button
            Mouse.Click(uIPageButton, new Point(43, 21));

            // Click 'View Source' menu item
            Mouse.Click(uIViewSourceMenuItem, new Point(62, 11));

            // Click '"text/javascript"' pane
            Mouse.Click(uITextjavascriptPane, new Point(73, 13));

            // Type 'Control + A' in 'about:blank' document
            Keyboard.SendKeys(uIAboutblankDocument, this.ViewSorceParams.UIAboutblankDocumentSendKeys, ModifierKeys.Control);

            // Type 'Control + C' in 'about:blank' document
            Keyboard.SendKeys(uIAboutblankDocument, this.ViewSorceParams.UIAboutblankDocumentSendKeys1, ModifierKeys.Control);

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(37, 17));
        }

        /// <summary>
        /// BT_Test2 - Use 'BT_Test2Params' to pass parameters into this method.
        /// </summary>
        public void BT_Test2()
        {
            #region Variable Declarations

            WinButton uIToolsButton = this.UIBlankPageWindowsInteWindow.UICommandBarToolBar.UIToolsButton;
            WinMenuItem uIInternetOptionsMenuItem = this.UIItemWindow.UIContextMenu.UIInternetOptionsMenuItem;
            WinButton uIDeleteButton = this.UIInternetOptionsWindow.UIDeleteWindow.UIDeleteButton;
            WinButton uIDeleteButton1 = this.UIDeleteBrowsingHistorWindow.UIDeleteWindow.UIDeleteButton;
            WinButton uILanguagesButton = this.UIInternetOptionsWindow.UILanguagesWindow.UILanguagesButton;
            WinButton uIOKButton = this.UILanguagePreferenceWindow.UIOKWindow.UIOKButton;
            WinButton uIOKButton1 = this.UIInternetOptionsWindow.UIOKWindow.UIOKButton;
            BrowserWindow uIBlankPageWindowsInteWindow = this.UIBlankPageWindowsInteWindow;
            WinButton uIPageButton = this.UIBlankPageWindowsInteWindow.UICommandBarToolBar.UIPageButton;
            WinMenuItem uIViewSourceMenuItem = this.UIItemWindow.UIContextMenu.UIViewSourceMenuItem;
            HtmlSpan uILeggicomescaricareilPane = this.UIHttpwwwskykingscasinWindow.UIItemClient.UIAboutblankDocument.UISyn_row7Pane.UILeggicomescaricareilPane;
            HtmlDocument uIAboutblankDocument = this.UIHttpwwwskykingscasinWindow.UIItemClient.UIAboutblankDocument;
            WinButton uICloseButton = this.UIHttpwwwskykingscasinWindow.UIHttpwwwskykingscasinTitleBar.UICloseButton;
            WinButton uICloseButton1 = this.UIBlankPageWindowsInteWindow.UIDasköniglichsteonlinTitleBar.UICloseButton;

            #endregion Variable Declarations

            // Go to web page 'about:blank' using new browser instance
            this.UIBlankPageWindowsInteWindow.LaunchUrl(new System.Uri(this.BT_Test2Params.UIBlankPageWindowsInteWindowUrl));

            // Click 'Tools' button
            Mouse.Click(uIToolsButton, new Point(33, 18));

            // Click 'Internet Options' menu item
            Mouse.Click(uIInternetOptionsMenuItem, new Point(122, 11));

            // Click '&Delete...' button
            Mouse.Click(uIDeleteButton, new Point(44, 16));

            // Click '&Delete' button
            Mouse.Click(uIDeleteButton1, new Point(41, 17));

            // Click '&Languages' button
            Mouse.Click(uILanguagesButton, new Point(46, 16));

            // Click '&Languages' button
            Mouse.Click(uILanguagesButton, new Point(49, 12));

            // Click '&Languages' button
            Mouse.Click(uILanguagesButton, new Point(48, 14));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(46, 21));

            // Click 'OK' button
            Mouse.Click(uIOKButton1, new Point(49, 19));

            // Go to web page 'http://www.skykingscasino.com/'
            uIBlankPageWindowsInteWindow.NavigateToUrl(new System.Uri(this.BT_Test2Params.UIBlankPageWindowsInteWindowUrl1));

            // Click 'Page' button
            Mouse.Click(uIPageButton, new Point(32, 15));

            // Click 'View Source' menu item
            Mouse.Click(uIViewSourceMenuItem, new Point(73, 15));

            // Click '"Leggi come scaricare il programma di Sk' pane
            Mouse.Click(uILeggicomescaricareilPane, new Point(194, 39));

            // Type 'Control + A' in 'about:blank' document
            Keyboard.SendKeys(uIAboutblankDocument, this.BT_Test2Params.UIAboutblankDocumentSendKeys, ModifierKeys.Control);

            // Type 'Control + V' in 'about:blank' document
            Keyboard.SendKeys(uIAboutblankDocument, this.BT_Test2Params.UIAboutblankDocumentSendKeys1, ModifierKeys.Control);

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(22, 12));

            // Click 'Close' button
            Mouse.Click(uICloseButton1, new Point(30, 6));
        }

        /// <summary>
        /// BT_Test3 - Use 'BT_Test3Params' to pass parameters into this method.
        /// </summary>
        public void BT_Test3()
        {
            #region Variable Declarations

            WinButton uIToolsButton = this.UIBlankPageWindowsInteWindow.UICommandBarToolBar.UIToolsButton;
            WinMenuItem uIInternetOptionsMenuItem = this.UIItemWindow.UIContextMenu.UIInternetOptionsMenuItem;
            WinButton uILanguagesButton = this.UIInternetOptionsWindow.UILanguagesWindow.UILanguagesButton;
            WinButton uIOKButton = this.UILanguagePreferenceWindow.UIOKWindow.UIOKButton;
            WinButton uIDeleteButton = this.UIInternetOptionsWindow.UIDeleteWindow.UIDeleteButton;
            WinButton uIDeleteButton1 = this.UIDeleteBrowsingHistorWindow.UIDeleteWindow.UIDeleteButton;
            WinButton uIOKButton1 = this.UIInternetOptionsWindow.UIOKWindow.UIOKButton;
            BrowserWindow uIBlankPageWindowsInteWindow = this.UIBlankPageWindowsInteWindow;
            WinButton uIPageButton = this.UIBlankPageWindowsInteWindow.UICommandBarToolBar.UIPageButton;
            WinMenuItem uIViewSourceMenuItem = this.UIItemWindow.UIContextMenu.UIViewSourceMenuItem;
            WinMenuItem uISelectAllCtrlAMenuItem = this.UIHttpwwwskykingscasinWindow1.UIApplicationMenuBar.UIEditMenuItem.UISelectAllCtrlAMenuItem;
            WinMenuItem uICopyCtrlCMenuItem = this.UIHttpwwwskykingscasinWindow1.UIApplicationMenuBar.UIEditMenuItem.UICopyCtrlCMenuItem;
            WinButton uICloseButton = this.UIHttpwwwskykingscasinWindow1.UIHttpwwwskykingscasinTitleBar.UICloseButton;
            WinButton uICloseButton1 = this.UIBlankPageWindowsInteWindow.UIDasköniglichsteonlinTitleBar.UICloseButton;

            #endregion Variable Declarations

            // Go to web page 'about:blank' using new browser instance
            this.UIBlankPageWindowsInteWindow.LaunchUrl(new System.Uri(this.BT_Test3Params.UIBlankPageWindowsInteWindowUrl));

            // Click 'Tools' button
            Mouse.Click(uIToolsButton, new Point(31, 21));

            // Click 'Internet Options' menu item
            Mouse.Click(uIInternetOptionsMenuItem, new Point(96, 15));

            // Click '&Languages' button
            Mouse.Click(uILanguagesButton, new Point(59, 17));
            Thread.Sleep(3000);
            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(46, 20));

            // Click '&Delete...' button
            Mouse.Click(uIDeleteButton, new Point(46, 20));

            // Click '&Delete' button
            Mouse.Click(uIDeleteButton1, new Point(41, 19));

            // Click 'OK' button
            Mouse.Click(uIOKButton1, new Point(42, 10));

            Thread.Sleep(15000);
            bool done = false;
            int i = 0;
            do
            {
                try
                {
                    // Go to web page 'http://www.skykingscasino.com/'
                    uIBlankPageWindowsInteWindow.NavigateToUrl(new System.Uri(this.BT_Test3Params.UIBlankPageWindowsInteWindowUrl1));
                    done = true;
                }
                catch (Exception)
                {
                    if (i > 15)
                    {
                        done = true;
                    }
                    Thread.Sleep(1000);
                }
                i++;
            } while (!done);

            try
            {
                GetStartedClick2();
            }
            catch (Exception)
            {
                Res = "";
            }
            //// Click 'Page' button
            //Mouse.Click(uIPageButton, new Point(41, 20));

            //// Click 'View Source' menu item
            //Mouse.Click(uIViewSourceMenuItem, new Point(91, 18));

            //// Click 'Edit' -> 'Select All	Ctrl+A' menu item
            //Mouse.Click(uISelectAllCtrlAMenuItem, new Point(69, 14));

            //// Click 'Edit' -> 'Copy	Ctrl+C' menu item
            //Mouse.Click(uICopyCtrlCMenuItem, new Point(32, 9));

            //// Click 'Close' button
            //Mouse.Click(uICloseButton, new Point(29, 13));

            // Click 'Close' button
            Mouse.Click(uICloseButton1, new Point(31, 15));
        }

        /// <summary>
        /// GetStartedClivk
        /// </summary>
        public void GetStartedClivk()
        {
            #region Variable Declarations

            HtmlHyperlink uIGettingstartedHyperlink = this.UIGetFreeOnlineCasinoBWindow.UIMainFrameFrame.UIFreeonlinecasinogameDocument.UIGettingstartedHyperlink;

            #endregion Variable Declarations

            // Click 'Getting started' link
            Mouse.Click(uIGettingstartedHyperlink, new Point(45, 10));
        }

        /// <summary>
        /// startedClick
        /// </summary>
        public void startedClick()
        {
            #region Variable Declarations

            HtmlHyperlink uIGettingstartedHyperlink = this.UIFreeonlinecasinogameWindow.UIMainFrameFrame.UIFreeonlinecasinogameDocument.UIGettingstartedHyperlink;

            #endregion Variable Declarations

            // Click 'Getting started' link
            Mouse.Click(uIGettingstartedHyperlink, new Point(60, 9));
        }

        /// <summary>
        /// GetStartedClick2
        /// </summary>
        public void GetStartedClick2()
        {
            #region Variable Declarations

            //HtmlHyperlink uIGettingstartedHyperlink = this.UIFreeonlinecasinogameWindow.UIFreeonlinecasinogameDocument.UIGettingstartedHyperlink;

            #endregion Variable Declarations

            // Click 'Getting started' link
            //Mouse.Click(uIGettingstartedHyperlink, new Point(36, 5));
            Res = this.UIFreeonlinecasinogameWindow.UIFreeonlinecasinogameDocument.PageUrl;
        }

        #region Properties

        public virtual BT_TestParams BT_TestParams
        {
            get
            {
                if ((this.mBT_TestParams == null))
                {
                    this.mBT_TestParams = new BT_TestParams();
                }
                return this.mBT_TestParams;
            }
        }

        public virtual CopyAddressParams CopyAddressParams
        {
            get
            {
                if ((this.mCopyAddressParams == null))
                {
                    this.mCopyAddressParams = new CopyAddressParams();
                }
                return this.mCopyAddressParams;
            }
        }

        public virtual ViewSorceParams ViewSorceParams
        {
            get
            {
                if ((this.mViewSorceParams == null))
                {
                    this.mViewSorceParams = new ViewSorceParams();
                }
                return this.mViewSorceParams;
            }
        }

        public virtual BT_Test2Params BT_Test2Params
        {
            get
            {
                if ((this.mBT_Test2Params == null))
                {
                    this.mBT_Test2Params = new BT_Test2Params();
                }
                return this.mBT_Test2Params;
            }
        }

        public virtual BT_Test3Params BT_Test3Params
        {
            get
            {
                if ((this.mBT_Test3Params == null))
                {
                    this.mBT_Test3Params = new BT_Test3Params();
                }
                return this.mBT_Test3Params;
            }
        }

        public UIBlankPageWindowsInteWindow UIBlankPageWindowsInteWindow
        {
            get
            {
                if ((this.mUIBlankPageWindowsInteWindow == null))
                {
                    this.mUIBlankPageWindowsInteWindow = new UIBlankPageWindowsInteWindow();
                }
                return this.mUIBlankPageWindowsInteWindow;
            }
        }

        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1();
                }
                return this.mUIItemWindow;
            }
        }

        public UIInternetOptionsWindow UIInternetOptionsWindow
        {
            get
            {
                if ((this.mUIInternetOptionsWindow == null))
                {
                    this.mUIInternetOptionsWindow = new UIInternetOptionsWindow();
                }
                return this.mUIInternetOptionsWindow;
            }
        }

        public UIDeleteBrowsingHistorWindow UIDeleteBrowsingHistorWindow
        {
            get
            {
                if ((this.mUIDeleteBrowsingHistorWindow == null))
                {
                    this.mUIDeleteBrowsingHistorWindow = new UIDeleteBrowsingHistorWindow();
                }
                return this.mUIDeleteBrowsingHistorWindow;
            }
        }

        public UIПолучитеБесплатныйБоWindow UIПолучитеБесплатныйБоWindow
        {
            get
            {
                if ((this.mUIПолучитеБесплатныйБоWindow == null))
                {
                    this.mUIПолучитеБесплатныйБоWindow = new UIПолучитеБесплатныйБоWindow();
                }
                return this.mUIПолучитеБесплатныйБоWindow;
            }
        }

        public UIFreeonlinecasinogameWindow UIFreeonlinecasinogameWindow
        {
            get
            {
                if ((this.mUIFreeonlinecasinogameWindow == null))
                {
                    this.mUIFreeonlinecasinogameWindow = new UIFreeonlinecasinogameWindow();
                }
                return this.mUIFreeonlinecasinogameWindow;
            }
        }

        public UIHttpwwwjoylandcasinoWindow UIHttpwwwjoylandcasinoWindow
        {
            get
            {
                if ((this.mUIHttpwwwjoylandcasinoWindow == null))
                {
                    this.mUIHttpwwwjoylandcasinoWindow = new UIHttpwwwjoylandcasinoWindow();
                }
                return this.mUIHttpwwwjoylandcasinoWindow;
            }
        }

        public UILanguagePreferenceWindow UILanguagePreferenceWindow
        {
            get
            {
                if ((this.mUILanguagePreferenceWindow == null))
                {
                    this.mUILanguagePreferenceWindow = new UILanguagePreferenceWindow();
                }
                return this.mUILanguagePreferenceWindow;
            }
        }

        public UIHttpwwwskykingscasinWindow UIHttpwwwskykingscasinWindow
        {
            get
            {
                if ((this.mUIHttpwwwskykingscasinWindow == null))
                {
                    this.mUIHttpwwwskykingscasinWindow = new UIHttpwwwskykingscasinWindow();
                }
                return this.mUIHttpwwwskykingscasinWindow;
            }
        }

        public UIHttpwwwskykingscasinWindow1 UIHttpwwwskykingscasinWindow1
        {
            get
            {
                if ((this.mUIHttpwwwskykingscasinWindow1 == null))
                {
                    this.mUIHttpwwwskykingscasinWindow1 = new UIHttpwwwskykingscasinWindow1();
                }
                return this.mUIHttpwwwskykingscasinWindow1;
            }
        }

        public UIGetFreeOnlineCasinoBWindow UIGetFreeOnlineCasinoBWindow
        {
            get
            {
                if ((this.mUIGetFreeOnlineCasinoBWindow == null))
                {
                    this.mUIGetFreeOnlineCasinoBWindow = new UIGetFreeOnlineCasinoBWindow();
                }
                return this.mUIGetFreeOnlineCasinoBWindow;
            }
        }

        #endregion Properties

        #region Fields

        private BT_TestParams mBT_TestParams;

        private CopyAddressParams mCopyAddressParams;

        private ViewSorceParams mViewSorceParams;

        private BT_Test2Params mBT_Test2Params;

        private BT_Test3Params mBT_Test3Params;

        private UIBlankPageWindowsInteWindow mUIBlankPageWindowsInteWindow;

        private UIItemWindow1 mUIItemWindow;

        private UIInternetOptionsWindow mUIInternetOptionsWindow;

        private UIDeleteBrowsingHistorWindow mUIDeleteBrowsingHistorWindow;

        private UIПолучитеБесплатныйБоWindow mUIПолучитеБесплатныйБоWindow;

        private UIFreeonlinecasinogameWindow mUIFreeonlinecasinogameWindow;

        private UIHttpwwwjoylandcasinoWindow mUIHttpwwwjoylandcasinoWindow;

        private UILanguagePreferenceWindow mUILanguagePreferenceWindow;

        private UIHttpwwwskykingscasinWindow mUIHttpwwwskykingscasinWindow;

        private UIHttpwwwskykingscasinWindow1 mUIHttpwwwskykingscasinWindow1;

        private UIGetFreeOnlineCasinoBWindow mUIGetFreeOnlineCasinoBWindow;

        #endregion Fields
    }

    /// <summary>
    /// Parameters to be passed into 'BT_Test'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class BT_TestParams
    {
        #region Fields

        /// <summary>
        /// Go to web page 'about:blank' using new browser instance
        /// </summary>
        public string UIBlankPageWindowsInteWindowUrl = "about:blank";

        /// <summary>
        /// Go to web page 'http://www.skykingscasino.com/'
        /// </summary>
        public string UIBlankPageWindowsInteWindowUrl1 = "http://www.skykingscasino.com/";

        #endregion Fields
    }

    /// <summary>
    /// Parameters to be passed into 'CopyAddress'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class CopyAddressParams
    {
        #region Fields

        /// <summary>
        /// Type 'Control + C' in 'Address' text box
        /// </summary>
        public string UIAddressEditSendKeys = "C";

        #endregion Fields
    }

    /// <summary>
    /// Parameters to be passed into 'ViewSorce'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class ViewSorceParams
    {
        #region Fields

        /// <summary>
        /// Type 'Control + A' in 'about:blank' document
        /// </summary>
        public string UIAboutblankDocumentSendKeys = "A";

        /// <summary>
        /// Type 'Control + C' in 'about:blank' document
        /// </summary>
        public string UIAboutblankDocumentSendKeys1 = "C";

        #endregion Fields
    }

    /// <summary>
    /// Parameters to be passed into 'BT_Test2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class BT_Test2Params
    {
        #region Fields

        /// <summary>
        /// Go to web page 'about:blank' using new browser instance
        /// </summary>
        public string UIBlankPageWindowsInteWindowUrl = "about:blank";

        /// <summary>
        /// Go to web page 'http://www.skykingscasino.com/'
        /// </summary>
        public string UIBlankPageWindowsInteWindowUrl1 = "http://www.skykingscasino.com/";

        /// <summary>
        /// Type 'Control + A' in 'about:blank' document
        /// </summary>
        public string UIAboutblankDocumentSendKeys = "A";

        /// <summary>
        /// Type 'Control + V' in 'about:blank' document
        /// </summary>
        public string UIAboutblankDocumentSendKeys1 = "V";

        #endregion Fields
    }

    /// <summary>
    /// Parameters to be passed into 'BT_Test3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class BT_Test3Params
    {
        #region Fields

        /// <summary>
        /// Go to web page 'about:blank' using new browser instance
        /// </summary>
        public string UIBlankPageWindowsInteWindowUrl = "about:blank";

        /// <summary>
        /// Go to web page 'http://www.skykingscasino.com/'
        /// </summary>
        public string UIBlankPageWindowsInteWindowUrl1 = "http://www.skykingscasino.com/";

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIBlankPageWindowsInteWindow : BrowserWindow
    {
        public UIBlankPageWindowsInteWindow()
        {
            #region Search Criteria

            this.SearchProperties[UITestControl.PropertyNames.Name] = "Blank Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Blank Page");
            this.WindowTitles.Add("Benvenuto al casinò Skykings, il miglior casinò online dove giocare!");

            #endregion Search Criteria
        }

        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }

        #region Properties

        public UICommandBarToolBar UICommandBarToolBar
        {
            get
            {
                if ((this.mUICommandBarToolBar == null))
                {
                    this.mUICommandBarToolBar = new UICommandBarToolBar(this);
                }
                return this.mUICommandBarToolBar;
            }
        }

        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }

        public UIDasköniglichsteonlinTitleBar UIDasköniglichsteonlinTitleBar
        {
            get
            {
                if ((this.mUIDasköniglichsteonlinTitleBar == null))
                {
                    this.mUIDasköniglichsteonlinTitleBar = new UIDasköniglichsteonlinTitleBar(this);
                }
                return this.mUIDasköniglichsteonlinTitleBar;
            }
        }

        #endregion Properties

        #region Fields

        private UICommandBarToolBar mUICommandBarToolBar;

        private UIItemWindow mUIItemWindow;

        private UIDasköniglichsteonlinTitleBar mUIDasköniglichsteonlinTitleBar;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UICommandBarToolBar : WinToolBar
    {
        public UICommandBarToolBar(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Command Bar";
            this.WindowTitles.Add("Blank Page");
            this.WindowTitles.Add("Benvenuto al casinò Skykings, il miglior casinò online dove giocare!");

            #endregion Search Criteria
        }

        #region Properties

        public WinButton UIToolsButton
        {
            get
            {
                if ((this.mUIToolsButton == null))
                {
                    this.mUIToolsButton = new WinButton(this);

                    #region Search Criteria

                    this.mUIToolsButton.SearchProperties[WinButton.PropertyNames.Name] = "Tools";
                    this.mUIToolsButton.WindowTitles.Add("Blank Page");

                    #endregion Search Criteria
                }
                return this.mUIToolsButton;
            }
        }

        public WinButton UIPageButton
        {
            get
            {
                if ((this.mUIPageButton == null))
                {
                    this.mUIPageButton = new WinButton(this);

                    #region Search Criteria

                    this.mUIPageButton.SearchProperties[WinButton.PropertyNames.Name] = "Page";
                    this.mUIPageButton.WindowTitles.Add("Benvenuto al casinò Skykings, il miglior casinò online dove giocare!");

                    #endregion Search Criteria
                }
                return this.mUIPageButton;
            }
        }

        #endregion Properties

        #region Fields

        private WinButton mUIToolsButton;

        private WinButton mUIPageButton;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow : WinWindow
    {
        public UIItemWindow(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "41477";
            this.WindowTitles.Add("Blank Page");
            this.WindowTitles.Add("Das königlichste online Casino!");

            #endregion Search Criteria
        }

        #region Properties

        public WinEdit UIAddressEdit
        {
            get
            {
                if ((this.mUIAddressEdit == null))
                {
                    this.mUIAddressEdit = new WinEdit(this);

                    #region Search Criteria

                    this.mUIAddressEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address";
                    this.mUIAddressEdit.WindowTitles.Add("Blank Page");
                    this.mUIAddressEdit.WindowTitles.Add("Das königlichste online Casino!");

                    #endregion Search Criteria
                }
                return this.mUIAddressEdit;
            }
        }

        #endregion Properties

        #region Fields

        private WinEdit mUIAddressEdit;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDasköniglichsteonlinTitleBar : WinTitleBar
    {
        public UIDasköniglichsteonlinTitleBar(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.WindowTitles.Add("Das königlichste online Casino!");

            #endregion Search Criteria
        }

        #region Properties

        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);

                    #region Search Criteria

                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Das königlichste online Casino!");

                    #endregion Search Criteria
                }
                return this.mUICloseButton;
            }
        }

        #endregion Properties

        #region Fields

        private WinButton mUICloseButton;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow1 : WinWindow
    {
        public UIItemWindow1()
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Context";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32768";

            #endregion Search Criteria
        }

        #region Properties

        public UIContextMenu UIContextMenu
        {
            get
            {
                if ((this.mUIContextMenu == null))
                {
                    this.mUIContextMenu = new UIContextMenu(this);
                }
                return this.mUIContextMenu;
            }
        }

        #endregion Properties

        #region Fields

        private UIContextMenu mUIContextMenu;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIContextMenu : WinMenu
    {
        public UIContextMenu(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinMenu.PropertyNames.Name] = "Context";

            #endregion Search Criteria
        }

        #region Properties

        public WinMenuItem UIInternetOptionsMenuItem
        {
            get
            {
                if ((this.mUIInternetOptionsMenuItem == null))
                {
                    this.mUIInternetOptionsMenuItem = new WinMenuItem(this);

                    #region Search Criteria

                    this.mUIInternetOptionsMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Internet Options";

                    #endregion Search Criteria
                }
                return this.mUIInternetOptionsMenuItem;
            }
        }

        public WinMenuItem UICopyMenuItem
        {
            get
            {
                if ((this.mUICopyMenuItem == null))
                {
                    this.mUICopyMenuItem = new WinMenuItem(this);

                    #region Search Criteria

                    this.mUICopyMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Copy";

                    #endregion Search Criteria
                }
                return this.mUICopyMenuItem;
            }
        }

        public WinMenuItem UIViewSourceMenuItem
        {
            get
            {
                if ((this.mUIViewSourceMenuItem == null))
                {
                    this.mUIViewSourceMenuItem = new WinMenuItem(this);

                    #region Search Criteria

                    this.mUIViewSourceMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "View Source";

                    #endregion Search Criteria
                }
                return this.mUIViewSourceMenuItem;
            }
        }

        #endregion Properties

        #region Fields

        private WinMenuItem mUIInternetOptionsMenuItem;

        private WinMenuItem mUICopyMenuItem;

        private WinMenuItem mUIViewSourceMenuItem;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIInternetOptionsWindow : WinWindow
    {
        public UIInternetOptionsWindow()
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.Name] = "Internet Options";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Internet Options");

            #endregion Search Criteria
        }

        #region Properties

        public UIDeleteWindow UIDeleteWindow
        {
            get
            {
                if ((this.mUIDeleteWindow == null))
                {
                    this.mUIDeleteWindow = new UIDeleteWindow(this);
                }
                return this.mUIDeleteWindow;
            }
        }

        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow(this);
                }
                return this.mUIOKWindow;
            }
        }

        public UILanguagesWindow UILanguagesWindow
        {
            get
            {
                if ((this.mUILanguagesWindow == null))
                {
                    this.mUILanguagesWindow = new UILanguagesWindow(this);
                }
                return this.mUILanguagesWindow;
            }
        }

        #endregion Properties

        #region Fields

        private UIDeleteWindow mUIDeleteWindow;

        private UIOKWindow mUIOKWindow;

        private UILanguagesWindow mUILanguagesWindow;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDeleteWindow : WinWindow
    {
        public UIDeleteWindow(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "5501";
            this.WindowTitles.Add("Internet Options");

            #endregion Search Criteria
        }

        #region Properties

        public WinButton UIDeleteButton
        {
            get
            {
                if ((this.mUIDeleteButton == null))
                {
                    this.mUIDeleteButton = new WinButton(this);

                    #region Search Criteria

                    this.mUIDeleteButton.SearchProperties[WinButton.PropertyNames.Name] = "Delete...";
                    this.mUIDeleteButton.WindowTitles.Add("Internet Options");

                    #endregion Search Criteria
                }
                return this.mUIDeleteButton;
            }
        }

        #endregion Properties

        #region Fields

        private WinButton mUIDeleteButton;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIOKWindow : WinWindow
    {
        public UIOKWindow(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Internet Options");

            #endregion Search Criteria
        }

        #region Properties

        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);

                    #region Search Criteria

                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Internet Options");

                    #endregion Search Criteria
                }
                return this.mUIOKButton;
            }
        }

        #endregion Properties

        #region Fields

        private WinButton mUIOKButton;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UILanguagesWindow : WinWindow
    {
        public UILanguagesWindow(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1495";
            this.WindowTitles.Add("Internet Options");

            #endregion Search Criteria
        }

        #region Properties

        public WinButton UILanguagesButton
        {
            get
            {
                if ((this.mUILanguagesButton == null))
                {
                    this.mUILanguagesButton = new WinButton(this);

                    #region Search Criteria

                    this.mUILanguagesButton.SearchProperties[WinButton.PropertyNames.Name] = "Languages";
                    this.mUILanguagesButton.WindowTitles.Add("Internet Options");

                    #endregion Search Criteria
                }
                return this.mUILanguagesButton;
            }
        }

        #endregion Properties

        #region Fields

        private WinButton mUILanguagesButton;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDeleteBrowsingHistorWindow : WinWindow
    {
        public UIDeleteBrowsingHistorWindow()
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.Name] = "Delete Browsing History";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Delete Browsing History");

            #endregion Search Criteria
        }

        #region Properties

        public UIDeleteWindow1 UIDeleteWindow
        {
            get
            {
                if ((this.mUIDeleteWindow == null))
                {
                    this.mUIDeleteWindow = new UIDeleteWindow1(this);
                }
                return this.mUIDeleteWindow;
            }
        }

        #endregion Properties

        #region Fields

        private UIDeleteWindow1 mUIDeleteWindow;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIDeleteWindow1 : WinWindow
    {
        public UIDeleteWindow1(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "5543";
            this.WindowTitles.Add("Delete Browsing History");

            #endregion Search Criteria
        }

        #region Properties

        public WinButton UIDeleteButton
        {
            get
            {
                if ((this.mUIDeleteButton == null))
                {
                    this.mUIDeleteButton = new WinButton(this);

                    #region Search Criteria

                    this.mUIDeleteButton.SearchProperties[WinButton.PropertyNames.Name] = "Delete";
                    this.mUIDeleteButton.WindowTitles.Add("Delete Browsing History");

                    #endregion Search Criteria
                }
                return this.mUIDeleteButton;
            }
        }

        #endregion Properties

        #region Fields

        private WinButton mUIDeleteButton;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIПолучитеБесплатныйБоWindow : BrowserWindow
    {
        public UIПолучитеБесплатныйБоWindow()
        {
            #region Search Criteria

            this.SearchProperties[UITestControl.PropertyNames.Name] = "Получите Бесплатный Бонус от Онлайн Казино - Только Сегодня!";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Получите Бесплатный Бонус от Онлайн Казино - Только Сегодня!");

            #endregion Search Criteria
        }

        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }

        #region Properties

        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2(this);
                }
                return this.mUIItemWindow;
            }
        }

        #endregion Properties

        #region Fields

        private UIItemWindow2 mUIItemWindow;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow2 : WinWindow
    {
        public UIItemWindow2(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "41477";
            this.WindowTitles.Add("Получите Бесплатный Бонус от Онлайн Казино - Только Сегодня!");

            #endregion Search Criteria
        }

        #region Properties

        public WinEdit UIAddressEdit
        {
            get
            {
                if ((this.mUIAddressEdit == null))
                {
                    this.mUIAddressEdit = new WinEdit(this);

                    #region Search Criteria

                    this.mUIAddressEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address";
                    this.mUIAddressEdit.WindowTitles.Add("Получите Бесплатный Бонус от Онлайн Казино - Только Сегодня!");

                    #endregion Search Criteria
                }
                return this.mUIAddressEdit;
            }
        }

        #endregion Properties

        #region Fields

        private WinEdit mUIAddressEdit;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIFreeonlinecasinogameWindow : BrowserWindow
    {
        public UIFreeonlinecasinogameWindow()
        {
            #region Search Criteria

            //this.SearchProperties[UITestControl.PropertyNames.Name] = "Free online casino games";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            //this.WindowTitles.Add("Free online casino games");

            #endregion Search Criteria
        }

        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }

        #region Properties

        public UICommandBarToolBar1 UICommandBarToolBar
        {
            get
            {
                if ((this.mUICommandBarToolBar == null))
                {
                    this.mUICommandBarToolBar = new UICommandBarToolBar1(this);
                }
                return this.mUICommandBarToolBar;
            }
        }

        public UIMainFrameFrame UIMainFrameFrame
        {
            get
            {
                if ((this.mUIMainFrameFrame == null))
                {
                    this.mUIMainFrameFrame = new UIMainFrameFrame(this);
                }
                return this.mUIMainFrameFrame;
            }
        }

        public UIFreeonlinecasinogameDocument1 UIFreeonlinecasinogameDocument
        {
            get
            {
                if ((this.mUIFreeonlinecasinogameDocument == null))
                {
                    this.mUIFreeonlinecasinogameDocument = new UIFreeonlinecasinogameDocument1(this);
                }
                return this.mUIFreeonlinecasinogameDocument;
            }
        }

        #endregion Properties

        #region Fields

        private UICommandBarToolBar1 mUICommandBarToolBar;

        private UIMainFrameFrame mUIMainFrameFrame;

        private UIFreeonlinecasinogameDocument1 mUIFreeonlinecasinogameDocument;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UICommandBarToolBar1 : WinToolBar
    {
        public UICommandBarToolBar1(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Command Bar";
            this.WindowTitles.Add("Free online casino games");

            #endregion Search Criteria
        }

        #region Properties

        public WinButton UIPageButton
        {
            get
            {
                if ((this.mUIPageButton == null))
                {
                    this.mUIPageButton = new WinButton(this);

                    #region Search Criteria

                    this.mUIPageButton.SearchProperties[WinButton.PropertyNames.Name] = "Page";
                    this.mUIPageButton.WindowTitles.Add("Free online casino games");

                    #endregion Search Criteria
                }
                return this.mUIPageButton;
            }
        }

        #endregion Properties

        #region Fields

        private WinButton mUIPageButton;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIMainFrameFrame : HtmlFrame
    {
        public UIMainFrameFrame(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "mainFrame";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = "mainFrame";
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/pl/index.php";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "http://www.joylandcasino.com/pl/index.php";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "id=mainFrame noResize marginHeight=0 src";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Free online casino games");

            #endregion Search Criteria
        }

        #region Properties

        public UIFreeonlinecasinogameDocument UIFreeonlinecasinogameDocument
        {
            get
            {
                if ((this.mUIFreeonlinecasinogameDocument == null))
                {
                    this.mUIFreeonlinecasinogameDocument = new UIFreeonlinecasinogameDocument(this);
                }
                return this.mUIFreeonlinecasinogameDocument;
            }
        }

        #endregion Properties

        #region Fields

        private UIFreeonlinecasinogameDocument mUIFreeonlinecasinogameDocument;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIFreeonlinecasinogameDocument : HtmlDocument
    {
        public UIFreeonlinecasinogameDocument(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Free online casino games";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/uk/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.joylandcasino.com/uk/";
            this.WindowTitles.Add("Free online casino games");

            #endregion Search Criteria
        }

        #region Properties

        public HtmlHyperlink UIGettingstartedHyperlink
        {
            get
            {
                if ((this.mUIGettingstartedHyperlink == null))
                {
                    this.mUIGettingstartedHyperlink = new HtmlHyperlink(this);

                    #region Search Criteria

                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Getting started";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/uk/getting_started.php";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Instructions how to download and play at Joyland Online Casino";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.joylandcasino.com/uk/getting_started.php";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "top_menu";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=top_menu title=\"Instructions how t";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "23";
                    this.mUIGettingstartedHyperlink.WindowTitles.Add("Free online casino games");

                    #endregion Search Criteria
                }
                return this.mUIGettingstartedHyperlink;
            }
        }

        #endregion Properties

        #region Fields

        private HtmlHyperlink mUIGettingstartedHyperlink;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIFreeonlinecasinogameDocument1 : HtmlDocument
    {
        public UIFreeonlinecasinogameDocument1(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            //this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            //this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            //this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            //this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Free online casino games";
            //this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/uk/";
            //this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.joylandcasino.com/uk/";
            //this.WindowTitles.Add("Free online casino games");

            #endregion Search Criteria
        }

        #region Properties

        public HtmlHyperlink UIGettingstartedHyperlink
        {
            get
            {
                if ((this.mUIGettingstartedHyperlink == null))
                {
                    this.mUIGettingstartedHyperlink = new HtmlHyperlink(this);

                    #region Search Criteria

                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Getting started";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/uk/getting_started.php";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Instructions how to download and play at Joyland Online Casino";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.joylandcasino.com/uk/getting_started.php";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "top_menu";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=top_menu title=\"Instructions how t";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "23";
                    this.mUIGettingstartedHyperlink.WindowTitles.Add("Free online casino games");

                    #endregion Search Criteria
                }
                return this.mUIGettingstartedHyperlink;
            }
        }

        #endregion Properties

        #region Fields

        private HtmlHyperlink mUIGettingstartedHyperlink;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIHttpwwwjoylandcasinoWindow : WinWindow
    {
        public UIHttpwwwjoylandcasinoWindow()
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.Name] = "http://www.joylandcasino.com/ - Original Source";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "HTMLSOURCEVIEW";
            this.WindowTitles.Add("http://www.joylandcasino.com/ - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient(this);
                }
                return this.mUIItemClient;
            }
        }

        public UIHttpwwwjoylandcasinoTitleBar UIHttpwwwjoylandcasinoTitleBar
        {
            get
            {
                if ((this.mUIHttpwwwjoylandcasinoTitleBar == null))
                {
                    this.mUIHttpwwwjoylandcasinoTitleBar = new UIHttpwwwjoylandcasinoTitleBar(this);
                }
                return this.mUIHttpwwwjoylandcasinoTitleBar;
            }
        }

        #endregion Properties

        #region Fields

        private UIItemClient mUIItemClient;

        private UIHttpwwwjoylandcasinoTitleBar mUIHttpwwwjoylandcasinoTitleBar;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemClient : WinClient
    {
        public UIItemClient(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinControl.PropertyNames.ClassName] = "Internet Explorer_Server";
            this.WindowTitles.Add("http://www.joylandcasino.com/ - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public UIAboutblankDocument UIAboutblankDocument
        {
            get
            {
                if ((this.mUIAboutblankDocument == null))
                {
                    this.mUIAboutblankDocument = new UIAboutblankDocument(this);
                }
                return this.mUIAboutblankDocument;
            }
        }

        #endregion Properties

        #region Fields

        private UIAboutblankDocument mUIAboutblankDocument;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIAboutblankDocument : HtmlDocument
    {
        public UIAboutblankDocument(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "blank";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "about:blank";
            this.WindowTitles.Add("http://www.joylandcasino.com/ - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public UISyn_row7Pane UISyn_row7Pane
        {
            get
            {
                if ((this.mUISyn_row7Pane == null))
                {
                    this.mUISyn_row7Pane = new UISyn_row7Pane(this);
                }
                return this.mUISyn_row7Pane;
            }
        }

        #endregion Properties

        #region Fields

        private UISyn_row7Pane mUISyn_row7Pane;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISyn_row7Pane : HtmlDiv
    {
        public UISyn_row7Pane(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "syn_row7";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "<script type=\"text/javascript\"  src=\"/js";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "SYN_TXT";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"TEXT-INDENT: -0.5em; PADDING-LEFT";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "21";
            this.WindowTitles.Add("http://www.joylandcasino.com/ - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public HtmlSpan UITextjavascriptPane
        {
            get
            {
                if ((this.mUITextjavascriptPane == null))
                {
                    this.mUITextjavascriptPane = new HtmlSpan(this);

                    #region Search Criteria

                    this.mUITextjavascriptPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUITextjavascriptPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUITextjavascriptPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "\"text/javascript\"";
                    this.mUITextjavascriptPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUITextjavascriptPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "HTML_VAL";
                    this.mUITextjavascriptPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=HTML_VAL";
                    this.mUITextjavascriptPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
                    this.mUITextjavascriptPane.WindowTitles.Add("http://www.joylandcasino.com/ - Original Source");

                    #endregion Search Criteria
                }
                return this.mUITextjavascriptPane;
            }
        }

        #endregion Properties

        #region Fields

        private HtmlSpan mUITextjavascriptPane;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIHttpwwwjoylandcasinoTitleBar : WinTitleBar
    {
        public UIHttpwwwjoylandcasinoTitleBar(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.WindowTitles.Add("http://www.joylandcasino.com/ - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);

                    #region Search Criteria

                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("http://www.joylandcasino.com/ - Original Source");

                    #endregion Search Criteria
                }
                return this.mUICloseButton;
            }
        }

        #endregion Properties

        #region Fields

        private WinButton mUICloseButton;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UILanguagePreferenceWindow : WinWindow
    {
        public UILanguagePreferenceWindow()
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.Name] = "Language Preference";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Language Preference");

            #endregion Search Criteria
        }

        #region Properties

        public UIOKWindow1 UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow1(this);
                }
                return this.mUIOKWindow;
            }
        }

        #endregion Properties

        #region Fields

        private UIOKWindow1 mUIOKWindow;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIOKWindow1 : WinWindow
    {
        public UIOKWindow1(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Language Preference");

            #endregion Search Criteria
        }

        #region Properties

        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);

                    #region Search Criteria

                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Language Preference");

                    #endregion Search Criteria
                }
                return this.mUIOKButton;
            }
        }

        #endregion Properties

        #region Fields

        private WinButton mUIOKButton;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIHttpwwwskykingscasinWindow : WinWindow
    {
        public UIHttpwwwskykingscasinWindow()
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.Name] = "http://www.skykingscasino.com/language/it/ - Original Source";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "HTMLSOURCEVIEW";
            this.WindowTitles.Add("http://www.skykingscasino.com/language/it/ - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public UIItemClient1 UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient1(this);
                }
                return this.mUIItemClient;
            }
        }

        public UIHttpwwwskykingscasinTitleBar UIHttpwwwskykingscasinTitleBar
        {
            get
            {
                if ((this.mUIHttpwwwskykingscasinTitleBar == null))
                {
                    this.mUIHttpwwwskykingscasinTitleBar = new UIHttpwwwskykingscasinTitleBar(this);
                }
                return this.mUIHttpwwwskykingscasinTitleBar;
            }
        }

        #endregion Properties

        #region Fields

        private UIItemClient1 mUIItemClient;

        private UIHttpwwwskykingscasinTitleBar mUIHttpwwwskykingscasinTitleBar;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemClient1 : WinClient
    {
        public UIItemClient1(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinControl.PropertyNames.ClassName] = "Internet Explorer_Server";
            this.WindowTitles.Add("http://www.skykingscasino.com/language/it/ - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public UIAboutblankDocument1 UIAboutblankDocument
        {
            get
            {
                if ((this.mUIAboutblankDocument == null))
                {
                    this.mUIAboutblankDocument = new UIAboutblankDocument1(this);
                }
                return this.mUIAboutblankDocument;
            }
        }

        #endregion Properties

        #region Fields

        private UIAboutblankDocument1 mUIAboutblankDocument;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIAboutblankDocument1 : HtmlDocument
    {
        public UIAboutblankDocument1(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "blank";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "about:blank";
            this.WindowTitles.Add("http://www.skykingscasino.com/language/it/ - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public UISyn_row7Pane1 UISyn_row7Pane
        {
            get
            {
                if ((this.mUISyn_row7Pane == null))
                {
                    this.mUISyn_row7Pane = new UISyn_row7Pane1(this);
                }
                return this.mUISyn_row7Pane;
            }
        }

        #endregion Properties

        #region Fields

        private UISyn_row7Pane1 mUISyn_row7Pane;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UISyn_row7Pane1 : HtmlDiv
    {
        public UISyn_row7Pane1(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "syn_row7";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = " var domainName = \'skykingscasino.com\';<";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "SYN_TXT";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"TEXT-INDENT: -0.5em; PADDING-LEFT";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "21";
            this.WindowTitles.Add("http://www.skykingscasino.com/language/it/ - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public HtmlSpan UILeggicomescaricareilPane
        {
            get
            {
                if ((this.mUILeggicomescaricareilPane == null))
                {
                    this.mUILeggicomescaricareilPane = new HtmlSpan(this);

                    #region Search Criteria

                    this.mUILeggicomescaricareilPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUILeggicomescaricareilPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUILeggicomescaricareilPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "\"Leggi come scaricare il programma di Sk";
                    this.mUILeggicomescaricareilPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUILeggicomescaricareilPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "HTML_VAL";
                    this.mUILeggicomescaricareilPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=HTML_VAL";
                    this.mUILeggicomescaricareilPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "12";
                    this.mUILeggicomescaricareilPane.WindowTitles.Add("http://www.skykingscasino.com/language/it/ - Original Source");

                    #endregion Search Criteria
                }
                return this.mUILeggicomescaricareilPane;
            }
        }

        #endregion Properties

        #region Fields

        private HtmlSpan mUILeggicomescaricareilPane;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIHttpwwwskykingscasinTitleBar : WinTitleBar
    {
        public UIHttpwwwskykingscasinTitleBar(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.WindowTitles.Add("http://www.skykingscasino.com/language/it/ - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);

                    #region Search Criteria

                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("http://www.skykingscasino.com/language/it/ - Original Source");

                    #endregion Search Criteria
                }
                return this.mUICloseButton;
            }
        }

        #endregion Properties

        #region Fields

        private WinButton mUICloseButton;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIHttpwwwskykingscasinWindow1 : WinWindow
    {
        public UIHttpwwwskykingscasinWindow1()
        {
            #region Search Criteria

            this.SearchProperties[WinWindow.PropertyNames.Name] = "http://www.skykingscasino.com/front/pl/?lnd_index=temp - Original Source";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "HTMLSOURCEVIEW";
            this.WindowTitles.Add("http://www.skykingscasino.com/front/pl/?lnd_index=temp - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public UIApplicationMenuBar UIApplicationMenuBar
        {
            get
            {
                if ((this.mUIApplicationMenuBar == null))
                {
                    this.mUIApplicationMenuBar = new UIApplicationMenuBar(this);
                }
                return this.mUIApplicationMenuBar;
            }
        }

        public UIHttpwwwskykingscasinTitleBar1 UIHttpwwwskykingscasinTitleBar
        {
            get
            {
                if ((this.mUIHttpwwwskykingscasinTitleBar == null))
                {
                    this.mUIHttpwwwskykingscasinTitleBar = new UIHttpwwwskykingscasinTitleBar1(this);
                }
                return this.mUIHttpwwwskykingscasinTitleBar;
            }
        }

        #endregion Properties

        #region Fields

        private UIApplicationMenuBar mUIApplicationMenuBar;

        private UIHttpwwwskykingscasinTitleBar1 mUIHttpwwwskykingscasinTitleBar;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIApplicationMenuBar : WinMenuBar
    {
        public UIApplicationMenuBar(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinMenu.PropertyNames.Name] = "Application";
            this.WindowTitles.Add("http://www.skykingscasino.com/front/pl/?lnd_index=temp - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public UIEditMenuItem UIEditMenuItem
        {
            get
            {
                if ((this.mUIEditMenuItem == null))
                {
                    this.mUIEditMenuItem = new UIEditMenuItem(this);
                }
                return this.mUIEditMenuItem;
            }
        }

        #endregion Properties

        #region Fields

        private UIEditMenuItem mUIEditMenuItem;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIEditMenuItem : WinMenuItem
    {
        public UIEditMenuItem(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "Edit";
            this.WindowTitles.Add("http://www.skykingscasino.com/front/pl/?lnd_index=temp - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public WinMenuItem UISelectAllCtrlAMenuItem
        {
            get
            {
                if ((this.mUISelectAllCtrlAMenuItem == null))
                {
                    this.mUISelectAllCtrlAMenuItem = new WinMenuItem(this);

                    #region Search Criteria

                    this.mUISelectAllCtrlAMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Select All\tCtrl+A";
                    this.mUISelectAllCtrlAMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUISelectAllCtrlAMenuItem.WindowTitles.Add("http://www.skykingscasino.com/front/pl/?lnd_index=temp - Original Source");

                    #endregion Search Criteria
                }
                return this.mUISelectAllCtrlAMenuItem;
            }
        }

        public WinMenuItem UICopyCtrlCMenuItem
        {
            get
            {
                if ((this.mUICopyCtrlCMenuItem == null))
                {
                    this.mUICopyCtrlCMenuItem = new WinMenuItem(this);

                    #region Search Criteria

                    this.mUICopyCtrlCMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Copy\tCtrl+C";
                    this.mUICopyCtrlCMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUICopyCtrlCMenuItem.WindowTitles.Add("http://www.skykingscasino.com/front/pl/?lnd_index=temp - Original Source");

                    #endregion Search Criteria
                }
                return this.mUICopyCtrlCMenuItem;
            }
        }

        #endregion Properties

        #region Fields

        private WinMenuItem mUISelectAllCtrlAMenuItem;

        private WinMenuItem mUICopyCtrlCMenuItem;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIHttpwwwskykingscasinTitleBar1 : WinTitleBar
    {
        public UIHttpwwwskykingscasinTitleBar1(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.WindowTitles.Add("http://www.skykingscasino.com/front/pl/?lnd_index=temp - Original Source");

            #endregion Search Criteria
        }

        #region Properties

        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);

                    #region Search Criteria

                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("http://www.skykingscasino.com/front/pl/?lnd_index=temp - Original Source");

                    #endregion Search Criteria
                }
                return this.mUICloseButton;
            }
        }

        #endregion Properties

        #region Fields

        private WinButton mUICloseButton;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIGetFreeOnlineCasinoBWindow : BrowserWindow
    {
        public UIGetFreeOnlineCasinoBWindow()
        {
            #region Search Criteria

            this.SearchProperties[UITestControl.PropertyNames.Name] = "Get Free Online Casino Bonus - Today Only!";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Get Free Online Casino Bonus - Today Only!");

            #endregion Search Criteria
        }

        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }

        #region Properties

        public UIMainFrameFrame1 UIMainFrameFrame
        {
            get
            {
                if ((this.mUIMainFrameFrame == null))
                {
                    this.mUIMainFrameFrame = new UIMainFrameFrame1(this);
                }
                return this.mUIMainFrameFrame;
            }
        }

        #endregion Properties

        #region Fields

        private UIMainFrameFrame1 mUIMainFrameFrame;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIMainFrameFrame1 : HtmlFrame
    {
        public UIMainFrameFrame1(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[HtmlFrame.PropertyNames.Id] = "mainFrame";
            this.SearchProperties[HtmlFrame.PropertyNames.Name] = "mainFrame";
            this.FilterProperties[HtmlFrame.PropertyNames.AbsolutePath] = "/en/index.php";
            this.FilterProperties[HtmlFrame.PropertyNames.PageUrl] = "http://www.joylandcasino.com/en/index.php";
            this.FilterProperties[HtmlFrame.PropertyNames.Title] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.Class] = null;
            this.FilterProperties[HtmlFrame.PropertyNames.ControlDefinition] = "id=mainFrame noResize marginHeight=0 src";
            this.FilterProperties[HtmlFrame.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Get Free Online Casino Bonus - Today Only!");

            #endregion Search Criteria
        }

        #region Properties

        public UIFreeonlinecasinogameDocument2 UIFreeonlinecasinogameDocument
        {
            get
            {
                if ((this.mUIFreeonlinecasinogameDocument == null))
                {
                    this.mUIFreeonlinecasinogameDocument = new UIFreeonlinecasinogameDocument2(this);
                }
                return this.mUIFreeonlinecasinogameDocument;
            }
        }

        #endregion Properties

        #region Fields

        private UIFreeonlinecasinogameDocument2 mUIFreeonlinecasinogameDocument;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIFreeonlinecasinogameDocument2 : HtmlDocument
    {
        public UIFreeonlinecasinogameDocument2(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "True";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Free online casino games";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/en/index.php";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.joylandcasino.com/en/index.php";
            this.WindowTitles.Add("Get Free Online Casino Bonus - Today Only!");

            #endregion Search Criteria
        }

        #region Properties

        public HtmlHyperlink UIGettingstartedHyperlink
        {
            get
            {
                if ((this.mUIGettingstartedHyperlink == null))
                {
                    this.mUIGettingstartedHyperlink = new HtmlHyperlink(this);

                    #region Search Criteria

                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIGettingstartedHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Getting started";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/en/getting_started.php";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Instructions how to download and play at Joyland Online Casino";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.joylandcasino.com/en/getting_started.php";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "top_menu";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=top_menu title=\"Instructions how t";
                    this.mUIGettingstartedHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "23";
                    this.mUIGettingstartedHyperlink.WindowTitles.Add("Get Free Online Casino Bonus - Today Only!");

                    #endregion Search Criteria
                }
                return this.mUIGettingstartedHyperlink;
            }
        }

        #endregion Properties

        #region Fields

        private HtmlHyperlink mUIGettingstartedHyperlink;

        #endregion Fields
    }
}