version: '2'
services:
    microservicemongomvn-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/microServiceMongoMvn/mongodb/:/data/db/
