version: '2'
services:
    ang2mongmvn-app:
        image: ang2mongmvn
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://ang2mongmvn-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=Ang2MongMvn
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ang2mongmvn-mongodb:
        extends:
            file: mongodb.yml
            service: ang2mongmvn-mongodb
