version: '2'
services:
    tests_manager-app:
        image: tests_manager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tests_manager-mysql:3306/tests_manager?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tests_manager-elasticsearch:9300
        ports:
            - 8080:8080
    tests_manager-mysql:
        extends:
            file: mysql.yml
            service: tests_manager-mysql
    tests_manager-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tests_manager-elasticsearch
