// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Threading;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class UIMap
    {
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations

            HtmlSpan uISpin2MillionPane = this.UICasinoOnlinecasinogaWindow.UICasinoOnlinecasinogaDocument.UIMostpopularCustom.UISpin2MillionPane;
            HtmlDiv uIGameRulesPlayNowPracPane = this.UICasinoOnlinecasinogaWindow.UICasinoOnlinecasinogaDocument.UIMostpopularCustom.UIGameRulesPlayNowPracPane;

            #endregion Variable Declarations

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Spin 2 Million $™' pane at (12, 4)
            Mouse.Hover(uISpin2MillionPane, new Point(12, 4));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Game Rules Play NowPractice' pane
            Mouse.Click(uIGameRulesPlayNowPracPane, new Point(139, 52));
        }

        /// <summary>
        /// RecordedMethod2
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations

            HtmlImage uICmsimagescasinolibraImage = this.UICasinoOnlinecasinogaWindow.UICasinoOnlinecasinogaDocument.UIMostpopularCustom.UICmsimagescasinolibraImage;
            HtmlDiv uIGameRulesPlayNowPracPane = this.UICasinoOnlinecasinogaWindow.UICasinoOnlinecasinogaDocument.UIMostpopularCustom.UIGameRulesPlayNowPracPane;

            #endregion Variable Declarations

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover '/cms/images/casino/library/QuickGames/Iron-Man.jpg' image at (131, 65)
            Mouse.Hover(uICmsimagescasinolibraImage, new Point(131, 65));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Game Rules Play NowPractice' pane
            Mouse.Click(uIGameRulesPlayNowPracPane, new Point(120, 74));
        }

        /// <summary>
        /// RecordedMethod3 - Use 'RecordedMethod3Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations

            HtmlHyperlink uIPlayNowHyperlink = this.UICasinoOnlinecasinogaWindow.UICasinoOnlinecasinogaDocument.UIMostpopularCustom.UIPlayNowHyperlink;
            HtmlDiv uIGameRulesPlayNowPracPane = this.UICasinoOnlinecasinogaWindow.UICasinoOnlinecasinogaDocument.UIMostpopularCustom.UIGameRulesPlayNowPracPane;

            #endregion Variable Declarations

            // Go to web page 'http://casino.williamhill.com/' using new browser instance
            BrowserWindow casinowilliamhillcomBrowser = BrowserWindow.Launch(new System.Uri(this.RecordedMethod3Params.Url));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Play Now' link at (66, 22)
            Mouse.Hover(uIPlayNowHyperlink, new Point(66, 22));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Right-Click 'Game Rules Play NowPractice' pane
            Mouse.Click(uIGameRulesPlayNowPracPane, MouseButtons.Right, ModifierKeys.None, new Point(119, 73));
        }

        /// <summary>
        /// RecordedMethod4 - Use 'RecordedMethod4Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod4()
        {
            #region Variable Declarations

            HtmlDiv uIGameRulesPlayNowPracPane = this.UICasinoOnlinecasinogaWindow.UICasinoOnlinecasinogaDocument.UIMostpopularCustom.UIGameRulesPlayNowPracPane;
            HtmlHyperlink uIPlayNowHyperlink = this.UICasinoOnlinecasinogaWindow.UICasinoOnlinecasinogaDocument.UIMostpopularCustom.UIPlayNowHyperlink;

            #endregion Variable Declarations

            // Go to web page 'http://casino.williamhill.com/' using new browser instance
            BrowserWindow casinowilliamhillcomBrowser = BrowserWindow.Launch(new System.Uri(this.RecordedMethod4Params.Url));

            // Click 'Game Rules Play NowPractice' pane
            Mouse.Click(uIGameRulesPlayNowPracPane, new Point(125, 75));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Game Rules Play NowPractice' pane at (71, 21)
            Mouse.Hover(uIGameRulesPlayNowPracPane, new Point(71, 21));

            // Mouse hover 'Play Now' link at (55, 4)
            Mouse.Hover(uIPlayNowHyperlink, new Point(55, 4));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;
        }

        /// <summary>
        /// RecordedMethod5
        /// </summary>
        public bool RecordedMethod5()
        {
            #region Variable Declarations

            HtmlImage uICmsimagescasinolibraImage = this.UICasinoOnlinecasinogaWindow.UICasinoOnlinecasinogaDocument.UIMostpopularCustom.UICmsimagescasinolibraImage;
            HtmlDiv uIGameRulesPlayNowPracPane = this.UICasinoOnlinecasinogaWindow.UICasinoOnlinecasinogaDocument.UIMostpopularCustom.UIGameRulesPlayNowPracPane;
            HtmlDiv Detail = this.UICasinoOnlinecasinogaWindow.UICasinoOnlinecasinogaDocument.UIMostpopularCustom.UIGameRulesPlayNowPracPane1Iron;

            #endregion Variable Declarations

            // Go to web page 'http://casino.williamhill.com/' using new browser instance
            BrowserWindow casinowilliamhillcomBrowser = BrowserWindow.Launch(new System.Uri(this.RecordedMethod4Params.Url));
            Thread.Sleep(20000);
            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;
            string Befor = ((mshtml.HTMLDivElement)(((UITestControl)(Detail)).NativeElement)).currentStyle.visibility;
            // Mouse hover '/cms/images/casino/library/QuickGames/Iron-Man.jpg' image at (100, 52)
            Mouse.Hover(uICmsimagescasinolibraImage, new Point(100, 52));
            string after = ((mshtml.HTMLDivElement)(((UITestControl)(Detail)).NativeElement)).currentStyle.visibility;
            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;
            if (Befor == after)
                return false;
            else
                return true;
            // Click 'Game Rules Play NowPractice' pane
            //Mouse.Click(uIGameRulesPlayNowPracPane, new Point(80, 22));
        }

        #region Properties

        public virtual RecordedMethod3Params RecordedMethod3Params
        {
            get
            {
                if ((this.mRecordedMethod3Params == null))
                {
                    this.mRecordedMethod3Params = new RecordedMethod3Params();
                }
                return this.mRecordedMethod3Params;
            }
        }

        public virtual RecordedMethod4Params RecordedMethod4Params
        {
            get
            {
                if ((this.mRecordedMethod4Params == null))
                {
                    this.mRecordedMethod4Params = new RecordedMethod4Params();
                }
                return this.mRecordedMethod4Params;
            }
        }

        public UICasinoOnlinecasinogaWindow UICasinoOnlinecasinogaWindow
        {
            get
            {
                if ((this.mUICasinoOnlinecasinogaWindow == null))
                {
                    this.mUICasinoOnlinecasinogaWindow = new UICasinoOnlinecasinogaWindow();
                }
                return this.mUICasinoOnlinecasinogaWindow;
            }
        }

        #endregion Properties

        #region Fields

        private RecordedMethod3Params mRecordedMethod3Params;

        private RecordedMethod4Params mRecordedMethod4Params;

        private UICasinoOnlinecasinogaWindow mUICasinoOnlinecasinogaWindow;

        #endregion Fields
    }

    /// <summary>
    /// Parameters to be passed into 'RecordedMethod3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class RecordedMethod3Params
    {
        #region Fields

        /// <summary>
        /// Go to web page 'http://casino.williamhill.com/' using new browser instance
        /// </summary>
        public string Url = "http://casino.williamhill.com/";

        #endregion Fields
    }

    /// <summary>
    /// Parameters to be passed into 'RecordedMethod4'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class RecordedMethod4Params
    {
        #region Fields

        /// <summary>
        /// Go to web page 'http://casino.williamhill.com/' using new browser instance
        /// </summary>
        public string Url = "http://casino.williamhill.com/";

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UICasinoOnlinecasinogaWindow : BrowserWindow
    {
        public UICasinoOnlinecasinogaWindow()
        {
            #region Search Criteria

            this.SearchProperties[UITestControl.PropertyNames.Name] = "Casino – Online casino gambling – William Hill Online";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Casino – Online casino gambling – William Hill Online");

            #endregion Search Criteria
        }

        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }

        #region Properties

        public UICasinoOnlinecasinogaDocument UICasinoOnlinecasinogaDocument
        {
            get
            {
                if ((this.mUICasinoOnlinecasinogaDocument == null))
                {
                    this.mUICasinoOnlinecasinogaDocument = new UICasinoOnlinecasinogaDocument(this);
                }
                return this.mUICasinoOnlinecasinogaDocument;
            }
        }

        #endregion Properties

        #region Fields

        private UICasinoOnlinecasinogaDocument mUICasinoOnlinecasinogaDocument;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UICasinoOnlinecasinogaDocument : HtmlDocument
    {
        public UICasinoOnlinecasinogaDocument(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "casino_site";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Casino – Online casino gambling – William Hill Online";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://casino.williamhill.com/";
            this.WindowTitles.Add("Casino – Online casino gambling – William Hill Online");

            #endregion Search Criteria
        }

        #region Properties

        public UIMostpopularCustom UIMostpopularCustom
        {
            get
            {
                if ((this.mUIMostpopularCustom == null))
                {
                    this.mUIMostpopularCustom = new UIMostpopularCustom(this);
                }
                return this.mUIMostpopularCustom;
            }
        }

        #endregion Properties

        #region Fields

        private UIMostpopularCustom mUIMostpopularCustom;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIMostpopularCustom : HtmlCustom
    {
        public UIMostpopularCustom(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties["Id"] = "most-popular";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "UL";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "style=\"DISPLAY: block\" id=most-popular";
            this.FilterProperties["TagInstance"] = "17";
            this.WindowTitles.Add("Casino – Online casino gambling – William Hill Online");

            #endregion Search Criteria
        }

        #region Properties

        public HtmlSpan UISpin2MillionPane
        {
            get
            {
                if ((this.mUISpin2MillionPane == null))
                {
                    this.mUISpin2MillionPane = new HtmlSpan(this);

                    #region Search Criteria

                    this.mUISpin2MillionPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUISpin2MillionPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUISpin2MillionPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Spin 2 Million $™";
                    this.mUISpin2MillionPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUISpin2MillionPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "gameName";
                    this.mUISpin2MillionPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=gameName";
                    this.mUISpin2MillionPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "21";
                    this.mUISpin2MillionPane.WindowTitles.Add("Casino – Online casino gambling – William Hill Online");

                    #endregion Search Criteria
                }
                return this.mUISpin2MillionPane;
            }
        }

        public HtmlDiv UIGameRulesPlayNowPracPane
        {
            get
            {
                if ((this.mUIGameRulesPlayNowPracPane == null))
                {
                    this.mUIGameRulesPlayNowPracPane = new HtmlDiv(this);

                    #region Search Criteria

                    this.mUIGameRulesPlayNowPracPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIGameRulesPlayNowPracPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIGameRulesPlayNowPracPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Game Rules\r\nPlay NowPractice";
                    this.mUIGameRulesPlayNowPracPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIGameRulesPlayNowPracPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "gameLinks";
                    this.mUIGameRulesPlayNowPracPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=gameLinks";
                    this.mUIGameRulesPlayNowPracPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "64";
                    this.mUIGameRulesPlayNowPracPane.WindowTitles.Add("Casino – Online casino gambling – William Hill Online");

                    #endregion Search Criteria
                }
                return this.mUIGameRulesPlayNowPracPane;
            }
        }

        public HtmlDiv UIGameRulesPlayNowPracPane1Iron
        {
            get
            {
                if ((this.mUIGameRulesPlayNowPracPane1Iron == null))
                {
                    this.mUIGameRulesPlayNowPracPane1Iron = new HtmlDiv(this);

                    #region Search Criteria

                    this.mUIGameRulesPlayNowPracPane1Iron.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIGameRulesPlayNowPracPane1Iron.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIGameRulesPlayNowPracPane1Iron.FilterProperties[HtmlDiv.PropertyNames.InnerText] = " Game Rules\r\nPlay NowPractice";
                    this.mUIGameRulesPlayNowPracPane1Iron.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIGameRulesPlayNowPracPane1Iron.FilterProperties[HtmlDiv.PropertyNames.Class] = "gameDetails";
                    this.mUIGameRulesPlayNowPracPane1Iron.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=gameDetails";
                    this.mUIGameRulesPlayNowPracPane1Iron.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "62";
                    this.mUIGameRulesPlayNowPracPane1Iron.WindowTitles.Add("Casino – Online casino gambling – William Hill Online");

                    #endregion Search Criteria
                }
                return this.mUIGameRulesPlayNowPracPane1Iron;
            }
        }

        public HtmlImage UICmsimagescasinolibraImage
        {
            get
            {
                if ((this.mUICmsimagescasinolibraImage == null))
                {
                    this.mUICmsimagescasinolibraImage = new HtmlImage(this);

                    #region Search Criteria

                    this.mUICmsimagescasinolibraImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUICmsimagescasinolibraImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUICmsimagescasinolibraImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUICmsimagescasinolibraImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/cms/images/casino/library/QuickGames/Iron-Man.jpg";
                    this.mUICmsimagescasinolibraImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://whdn.williamhill.com/cms/images/casino/library/QuickGames/Iron-Man.jpg";
                    this.mUICmsimagescasinolibraImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "whLaunch.launchCasino(\'irm2\');";
                    this.mUICmsimagescasinolibraImage.FilterProperties[HtmlImage.PropertyNames.Href] = "javascript:whLaunch.launchCasino(\'irm2\');";
                    this.mUICmsimagescasinolibraImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUICmsimagescasinolibraImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "style=\"WIDTH: 143px; HEIGHT: 92px\" src=\"";
                    this.mUICmsimagescasinolibraImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "10";
                    this.mUICmsimagescasinolibraImage.WindowTitles.Add("Casino – Online casino gambling – William Hill Online");

                    #endregion Search Criteria
                }
                return this.mUICmsimagescasinolibraImage;
            }
        }

        public HtmlHyperlink UIPlayNowHyperlink
        {
            get
            {
                if ((this.mUIPlayNowHyperlink == null))
                {
                    this.mUIPlayNowHyperlink = new HtmlHyperlink(this);

                    #region Search Criteria

                    this.mUIPlayNowHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIPlayNowHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIPlayNowHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIPlayNowHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Play Now";
                    this.mUIPlayNowHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "whLaunch.launchCasino(\'irm2\');";
                    this.mUIPlayNowHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIPlayNowHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:whLaunch.launchCasino(\'irm2\');";
                    this.mUIPlayNowHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "play";
                    this.mUIPlayNowHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=play onclick=\"\" href=\"javascript:w";
                    this.mUIPlayNowHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "38";
                    this.mUIPlayNowHyperlink.WindowTitles.Add("Casino – Online casino gambling – William Hill Online");

                    #endregion Search Criteria
                }
                return this.mUIPlayNowHyperlink;
            }
        }

        #endregion Properties

        #region Fields

        private HtmlSpan mUISpin2MillionPane;

        private HtmlDiv mUIGameRulesPlayNowPracPane;

        private HtmlDiv mUIGameRulesPlayNowPracPane1Iron;

        private HtmlImage mUICmsimagescasinolibraImage;

        private HtmlHyperlink mUIPlayNowHyperlink;

        #endregion Fields
    }
}