// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CICacheTesting
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;

    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public partial class UIMap
    {
        /// <summary>
        /// ChachTest - Use 'ChachTestParams' to pass parameters into this method.
        /// </summary>
        bool firstEnter = true;
        mshtml.HTMLDocument document;

        public mshtml.HTMLDocument ChachTest(string URL)//, out int time)
        {
            #region Variable Declarations

            HtmlInputButton uIImFeelingLuckyButton = this.UIGoogleWindowsInterneWindow.UIGoogleDocument.UIImFeelingLuckyButton;

            #endregion Variable Declarations

            this.ChachTestParams.UIGoogleWindowsInterneWindowUrl = URL;
            // Go to web page 'https://www.google.com/' using new browser instance
            if (firstEnter)
            {
                this.UIGoogleWindowsInterneWindow.LaunchUrl(new System.Uri(this.ChachTestParams.UIGoogleWindowsInterneWindowUrl));
                firstEnter = false;
            }
            else
            {
                this.UIGoogleWindowsInterneWindow.NavigateToUrl(new System.Uri(this.ChachTestParams.UIGoogleWindowsInterneWindowUrl));
            }
            string str = "yaniv";
            //long PrivateMemorySize = Process.GetProcessesByName(UIGoogleWindowsInterneWindow.Process.ProcessName)[0].PrivateMemorySize64;

            document = ((mshtml.HTMLBody)this.UIGoogleWindowsInterneWindow.UIGoogleDocument.NativeElement).document;
            return document;
            // Click 'I'm Feeling Lucky' button
            //Mouse.Click(uIImFeelingLuckyButton, new Point(63, 18));
        }

        /// <summary>
        /// CICacheTest1 - Use 'CICacheTest1Params' to pass parameters into this method.
        /// </summary>
        public void CICacheTest1()
        {
            #region Variable Declarations

            BrowserWindow uIOnlineCasinoatEuroGrWindow = this.UIOnlineCasinoatEuroGrWindow;

            #endregion Variable Declarations

            //uIOnlineCasinoatEuroGrWindow.Process.PrivateMemorySize
            // Go to web page 'http://www.eurogrand.com/'
            uIOnlineCasinoatEuroGrWindow.NavigateToUrl(new System.Uri(this.CICacheTest1Params.UIOnlineCasinoatEuroGrWindowUrl));
        }

        /// <summary>
        /// CICacheTest2 - Use 'CICacheTest2Params' to pass parameters into this method.
        /// </summary>
        public void CICacheTest2()
        {
            // Go to web page 'https://www.google.com/' using new browser instance
            BrowserWindow googlecomBrowser = BrowserWindow.Launch(new System.Uri(this.CICacheTest2Params.Url));
        }

        /// <summary>
        /// RecordedMethod2
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations

            HtmlSpan uIGladiatorPane = this.UIOnlineCasinoatEuroGrWindow.UIOnlineCasinoatEuroGrDocument.UIFooterPane.UIGladiatorPane;
            HtmlSpan uIMegaballPane = this.UIOnlineCasinoatEuroGrWindow.UIOnlineCasinoatEuroGrDocument.UIFooterPane.UIMegaballPane;

            #endregion Variable Declarations

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'Gladiator' pane at (21, 9)
            Mouse.Hover(uIGladiatorPane, new Point(21, 9));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Megaball' pane
            Mouse.Click(uIMegaballPane, new Point(18, 8));
        }

        #region Properties

        public virtual CICacheTest1Params CICacheTest1Params
        {
            get
            {
                if ((this.mCICacheTest1Params == null))
                {
                    this.mCICacheTest1Params = new CICacheTest1Params();
                }
                return this.mCICacheTest1Params;
            }
        }

        public virtual CICacheTest2Params CICacheTest2Params
        {
            get
            {
                if ((this.mCICacheTest2Params == null))
                {
                    this.mCICacheTest2Params = new CICacheTest2Params();
                }
                return this.mCICacheTest2Params;
            }
        }

        public virtual ChachTestParams ChachTestParams
        {
            get
            {
                if ((this.mChachTestParams == null))
                {
                    this.mChachTestParams = new ChachTestParams();
                }
                return this.mChachTestParams;
            }
        }

        public UIOnlineCasinoatEuroGrWindow UIOnlineCasinoatEuroGrWindow
        {
            get
            {
                if ((this.mUIOnlineCasinoatEuroGrWindow == null))
                {
                    this.mUIOnlineCasinoatEuroGrWindow = new UIOnlineCasinoatEuroGrWindow();
                }
                return this.mUIOnlineCasinoatEuroGrWindow;
            }
        }

        public UIGoogleWindowsInterneWindow UIGoogleWindowsInterneWindow
        {
            get
            {
                if ((this.mUIGoogleWindowsInterneWindow == null))
                {
                    this.mUIGoogleWindowsInterneWindow = new UIGoogleWindowsInterneWindow();
                }
                return this.mUIGoogleWindowsInterneWindow;
            }
        }

        #endregion Properties

        #region Fields

        private CICacheTest1Params mCICacheTest1Params;

        private CICacheTest2Params mCICacheTest2Params;

        private ChachTestParams mChachTestParams;

        private UIOnlineCasinoatEuroGrWindow mUIOnlineCasinoatEuroGrWindow;

        private UIGoogleWindowsInterneWindow mUIGoogleWindowsInterneWindow;

        #endregion Fields
    }

    /// <summary>
    /// Parameters to be passed into 'CICacheTest1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class CICacheTest1Params
    {
        #region Fields

        /// <summary>
        /// Go to web page 'http://www.eurogrand.com/'
        /// </summary>
        public string UIOnlineCasinoatEuroGrWindowUrl = "http://www.eurogrand.com/";

        #endregion Fields
    }

    /// <summary>
    /// Parameters to be passed into 'CICacheTest2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class CICacheTest2Params
    {
        #region Fields

        /// <summary>
        /// Go to web page 'https://www.google.com/' using new browser instance
        /// </summary>
        public string Url = "https://www.google.com/";

        #endregion Fields
    }

    /// <summary>
    /// Parameters to be passed into 'ChachTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class ChachTestParams
    {
        #region Fields

        /// <summary>
        /// Go to web page 'https://www.google.com/' using new browser instance
        /// </summary>
        public string UIGoogleWindowsInterneWindowUrl = "https://www.google.com/";

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIOnlineCasinoatEuroGrWindow : BrowserWindow
    {
        public UIOnlineCasinoatEuroGrWindow()
        {
            #region Search Criteria

            this.SearchProperties[UITestControl.PropertyNames.Name] = "Online Casino at EuroGrand.com - A Grand Way to Play";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Online Casino at EuroGrand.com - A Grand Way to Play");

            #endregion Search Criteria
        }

        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }

        #region Properties

        public UIOnlineCasinoatEuroGrDocument UIOnlineCasinoatEuroGrDocument
        {
            get
            {
                if ((this.mUIOnlineCasinoatEuroGrDocument == null))
                {
                    this.mUIOnlineCasinoatEuroGrDocument = new UIOnlineCasinoatEuroGrDocument(this);
                }
                return this.mUIOnlineCasinoatEuroGrDocument;
            }
        }

        #endregion Properties

        #region Fields

        private UIOnlineCasinoatEuroGrDocument mUIOnlineCasinoatEuroGrDocument;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIOnlineCasinoatEuroGrDocument : HtmlDocument
    {
        public UIOnlineCasinoatEuroGrDocument(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Online Casino at EuroGrand.com - A Grand Way to Play";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.eurogrand.com/";
            this.WindowTitles.Add("Online Casino at EuroGrand.com - A Grand Way to Play");

            #endregion Search Criteria
        }

        #region Properties

        public UIFooterPane UIFooterPane
        {
            get
            {
                if ((this.mUIFooterPane == null))
                {
                    this.mUIFooterPane = new UIFooterPane(this);
                }
                return this.mUIFooterPane;
            }
        }

        #endregion Properties

        #region Fields

        private UIFooterPane mUIFooterPane;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIFooterPane : HtmlDiv
    {
        public UIFooterPane(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "footer";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "\r\nCARD GAMESIron Man 2 | Blackjack UK | ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"footer\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "225";
            this.WindowTitles.Add("Online Casino at EuroGrand.com - A Grand Way to Play");

            #endregion Search Criteria
        }

        #region Properties

        public HtmlSpan UIGladiatorPane
        {
            get
            {
                if ((this.mUIGladiatorPane == null))
                {
                    this.mUIGladiatorPane = new HtmlSpan(this);

                    #region Search Criteria

                    this.mUIGladiatorPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIGladiatorPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIGladiatorPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Gladiator";
                    this.mUIGladiatorPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIGladiatorPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIGladiatorPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "gatag=\"fgl_TABLE GAMES__glr\" fimtag=\"fgl";
                    this.mUIGladiatorPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "19";
                    this.mUIGladiatorPane.WindowTitles.Add("Online Casino at EuroGrand.com - A Grand Way to Play");

                    #endregion Search Criteria
                }
                return this.mUIGladiatorPane;
            }
        }

        public HtmlSpan UIMegaballPane
        {
            get
            {
                if ((this.mUIMegaballPane == null))
                {
                    this.mUIMegaballPane = new HtmlSpan(this);

                    #region Search Criteria

                    this.mUIMegaballPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIMegaballPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIMegaballPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Megaball";
                    this.mUIMegaballPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIMegaballPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIMegaballPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "gatag=\"fgl_TABLE GAMES__bls\" fimtag=\"fgl";
                    this.mUIMegaballPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "38";
                    this.mUIMegaballPane.WindowTitles.Add("Online Casino at EuroGrand.com - A Grand Way to Play");

                    #endregion Search Criteria
                }
                return this.mUIMegaballPane;
            }
        }

        #endregion Properties

        #region Fields

        private HtmlSpan mUIGladiatorPane;

        private HtmlSpan mUIMegaballPane;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIGoogleWindowsInterneWindow : BrowserWindow
    {
        public UIGoogleWindowsInterneWindow()
        {
            #region Search Criteria

            //this.SearchProperties[UITestControl.PropertyNames.Name] = "Google";
            //this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            //this.WindowTitles.Add("Google");
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Blank Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Blank Page");

            #endregion Search Criteria
        }

        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }

        #region Properties

        public UIGoogleDocument UIGoogleDocument
        {
            get
            {
                if ((this.mUIGoogleDocument == null))
                {
                    this.mUIGoogleDocument = new UIGoogleDocument(this);
                }
                return this.mUIGoogleDocument;
            }
        }

        #endregion Properties

        #region Fields

        private UIGoogleDocument mUIGoogleDocument;

        #endregion Fields
    }

    [GeneratedCode("Coded UITest Builder", "10.0.40219.1")]
    public class UIGoogleDocument : HtmlDocument
    {
        public UIGoogleDocument(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria

            //this.SearchProperties[HtmlDocument.PropertyNames.Id] = "gsr";
            //this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            //this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            //this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Google";
            //this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            //this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.google.com/";
            //this.WindowTitles.Add("Google");

            #endregion Search Criteria
        }

        #region Properties

        public HtmlInputButton UIImFeelingLuckyButton
        {
            get
            {
                if ((this.mUIImFeelingLuckyButton == null))
                {
                    this.mUIImFeelingLuckyButton = new HtmlInputButton(this);

                    #region Search Criteria

                    this.mUIImFeelingLuckyButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIImFeelingLuckyButton.SearchProperties[HtmlButton.PropertyNames.Name] = "btnI";
                    this.mUIImFeelingLuckyButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "I\'m Feeling Lucky";
                    this.mUIImFeelingLuckyButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIImFeelingLuckyButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIImFeelingLuckyButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUIImFeelingLuckyButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "onclick=\"if(this.form.q.value)this.check";
                    this.mUIImFeelingLuckyButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "7";
                    this.mUIImFeelingLuckyButton.WindowTitles.Add("Google");

                    #endregion Search Criteria
                }
                return this.mUIImFeelingLuckyButton;
            }
        }

        #endregion Properties

        #region Fields

        private HtmlInputButton mUIImFeelingLuckyButton;

        #endregion Fields
    }
}